### ISSUE TITLE
Unable to build on NixOS

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/Cardinal#108]
When I try to build Cardinal on NixOS, I get: https://termsend.pl/o/ouot9
Any ideas on how to troubleshoot further?

Thanks!

**Comment by falkTX** [comment]
I would make sure the submodules point to the correct versions, `src/Rack` stuff seems to have some issues.

**Comment by magnetophon** [comment]
Yes, that [did the trick](https://github.com/NixOS/nixpkgs/pull/149739), thanks!
