### ISSUE TITLE
Cardinal Host Time - Clock not receiving the BPM from Reaper (LV2 plugin)

### ISSUE THREAD

**Issue by jp-gorman** [DISTRHO/Cardinal#109]
Scenario:
------------
Load cardinal Host as a module within cardinal
Load Clocked module and link cardinal host time "Clock" to Clocked modules BPM (to try and synch them)

Expected
------------
Correct BPM should be received from Reaper (displayed when hovered over the output from TimeHost, the clock should synch with reaper)

Actual
------------
0 is shown on the Clock and Beat Output and the "clkd" module's BPM is not synched.

Note 1: As a test, I swapped for the "Playing" to see if any comms was working and it did send 10v when reaper was playing and 0 when stopped. I also tried the other bar phrases etc. and they all changed the BPM (wildly as expecte, but it worked)

Note 2: It appears to be the Beat that takes on the actual BPM from Reaper (from some experiments) watching the flashing led on the HostTime module. What does the clock represent ?

Note 3: I tried swapping the Mode to P16/P24/CV etc. (nt that I really know the reasoning, but had lno effect to synch reaper and host (did change the values however)

**Comment by jp-gorman** [comment]
I changed the Model in CLKD to P4 and it seemed to synch, but yet still shows 0 on the hover over the Host Time Clock port. Perhap this is by design because it sends some non descript values that ony the clock modules understand?

Anyhow, I am not sure where reaper set's it's "pulses per step", but given one of the mode appears to synch eventually consistantly with changes in BPM in reaper, I'm happy to close this if not displaying the values on the port is by design.

**Comment by falkTX** [comment]
perhaps some docs on this will be needed.
"clock" there is just every single beat step, I just dont know how else to name it.

The large/long pulse is "bar", so on 4/4 it would trigger every 4 beats.
Then is "beat", which triggers every beat, aka there will be 4 beats in a bar.
Then is "clock" (or we can call it "step") which is every step of the beat. This means 4 steps per beat, and 16 steps per bar.

Should it be renamed to "beat step" perhaps?

**Comment by falkTX** [comment]
I renamed the "Clock" as "Step", added a little display to help demonstrate what these values map to.

![Screenshot_20220201_211851](https://user-images.githubusercontent.com/1334853/152053182-84135477-e7e1-4604-98a9-0f908d1ee443.png)

So I consider this one fixed.

**Comment by jp-gorman** [comment]
Great Thanks
