### ISSUE TITLE
Host Params in DuoX build doesn't seem to work

### ISSUE THREAD

**Issue by dromer** [DISTRHO/Cardinal#116]
Loading patches to `CardinalFX.lv2` inside MOD works great, however it seems that mappings to the Host Params module are not functional.

This works fine for lv2/vst2/vst3 on desktop DAWs, so something is off.

I have noticed once that the Host Params on vst2 in Bitwig became unresponsive (keeping its current setting), but not anything consistent like on DuoX.

**Comment by falkTX** [comment]
Fixed on f80cf75e30fc9342ef4a987ea4eaefb6a02eab7d
