### ISSUE TITLE
Add FPS rate limiter (none, 2x or 4x)

### ISSUE THREAD

**Issue by jypma** [DISTRHO/Cardinal#117]
After discovering high CPU usage on one of my (reasonably simple) patches, I ran a few tests of Cardinal+Carla vs. plain VCV Rack (both on PulseAudio output). Since I have a HiDPI laptop (i7-10875H CPU @ 2.30GHz, 3840x2160) with struggling Intel graphics, I've limited VCV Rack to 15 fps.

The patch uses 60% of one core in plain VCV rack (shown in `top`).

The same patch uses 100% of one core (shown in `top`) in Cardinal, with the plugin window open. At that time, Carla's DSP load only goes up to 60-70%. If I close the plugin window, the same patch then drops to 50% (in `top`) of one core (DSP load shows 40-50%), which leads me to conclude it's graphics-related.

The patch is attached, but I don't think it depends on the patch.
[snare.zip](https://github.com/DISTRHO/Cardinal/files/7887707/snare.zip)

**Comment by falkTX** [comment]
This is a clear and direct "wont fix".
The update rate of the plugin GUI comes from the host, not the plugin. Only exception being VST3, but even that one can be limited by the host.

In carla you can tweak the update rate on the 1st page of carla settings.

**Comment by falkTX** [comment]
Alternatively though, we can make the UI run 2x or 4x slower than the host.
Let me reopen but change the title then.

**Comment by jypma** [comment]
Thanks a lot for the quick feedback though! I'll be sure to tweak Carla's update rate. And good idea, since I'm not sure we can expect similar settings from Ardour, ZRythm, and more commercial hosts.
