### ISSUE TITLE
build #568 crashes ableton on loading older projects

### ISSUE THREAD

**Issue by offthesky** [DISTRHO/Cardinal#118]
crashes when loading projects that use patches made with build #565 or lower. seems to occur in ableton win10.

**Comment by offthesky** [comment]
found a work around: just rename the folder and dlls for any newer builds. for me, i renamed CardinalSynth.vst to CardinalSynth2.vst and the dlls within: CardinalFX.dll < CardinalFX2.dll, CardinalSynth.dll < CardinalSynth2.dll. upon rescan they show up like:
![image](https://user-images.githubusercontent.com/95579081/150650406-c4e39e66-da7f-4fe3-bcb4-dbcc506295c2.png)
and so now projects using older builds (#568 and below) will open without crashes and still work fine.  

this same technique also works for reaper. with reaper older projects wouldn't crash, but there would be no audio out from the cardinal instances (as the old audio out module seems to be disabled w newer builds).

**Comment by falkTX** [comment]
is this still an issue?

**Comment by offthesky** [comment]
the ableton projects with older (b656 and lower) patches load now without crashes however none of the patches produce any sound due to so many removed modules missing. i know this is not a bug but rather a licensing issue.  will we see the vortico or AS ones return?  also, perhaps the info for the work around i posted above (pre 656 and post 656 releases working together) - do you think it would be ideal for me to move that to the discussion area for other users?

**Comment by falkTX** [comment]
> will we see the vortico or AS ones return?

"vortico" as in Fundamental will return, but only when we have replacement panels.
There are a few direct module replacements we can setup, like fundamental merge -> aria smerge, which I will setup soon.
See https://github.com/DISTRHO/Cardinal/wiki/Fundamental-replacements
If you know of more direct replacements, please edit the page accordingly.

The rest will either be have a panel done on time before initial release, or just be missing.

For AS, I removed it altogether now. I contacted the miRack author which has made a direct artwork replacement to ask about license for that, but no answer from their side yet.

It is best to have 1 ticket per issue, so I will close this one.
For older builds, I rather not have publicly mentioned how to fetch them. GitHub will automatically delete them soon anyway
