### ISSUE TITLE
build #573 - vst2 instrument - crashes ableton and no audio out in reaper

### ISSUE THREAD

**Issue by offthesky** [DISTRHO/Cardinal#124]
x64 win 10 ableton/reaper (latest). loading an instance of the vsti causes ableton to cpu spike, then ultimately crash. in reaper, there is no crash, but no audio out when connecting to the 'cardinal host audio' module's outputs. the 'fx' .dll of the vst2 still works just fine in all ways afaict.

**Comment by dromer** [comment]
There have been some reports of the vst2 loading in ableton but not having a functional engine. Do you still see crashes with the latest builds?

There certainly seems to be something off with the vst2 synth plugin in combination with ableton live.

**Comment by schneider-dan** [comment]
Neraly same Issue on Win 10 with Ableton Live 11 and VST2 Plugin.
FX Plugin seems to work as expected: Host Time indicators blinking, etc. Sound working.
The Synth Plugin doesen't seem to have a connection to the VST Host (Live 11).
"Host Time" Module doesn't do anything. No CV and Gate Signals from "Host Midi" and "Host params".

I've got the exact same behaviour on 2 different machines.

**Comment by falkTX** [comment]
Might be fixed in de63835867f775b82523a0a245570da2dab4e8c4
Please test later on, after builds are done.
Thanks

**Comment by schneider-dan** [comment]
wow, folks. It works.
This was the best bugfixing experience in my whole life. Thank you so very much.
Tested with build d24ad09f.

Since I'm new to VCV Rack, I can't test everything in detail (yet) but if I can help you in any way just let me know.
Big HUUUUUG :-)

**Comment by falkTX** [comment]
@offthesky since you were the original reporter, can you try the new builds as well?
thanks!

**Comment by offthesky** [comment]
seems to be working great on my end now. tyty!

**Comment by falkTX** [comment]
Cool, closing as fixed then.
