### ISSUE TITLE
Issues in Cakewalk by Bandlab on Windows 10

### ISSUE THREAD

**Issue by ThePython10110** [DISTRHO/Cardinal#125]
1. The VST3 plugins crash it, which is not unexpected, since they are experimental.
2. I can't resize the window.
3. In the Carla VST host (which may be what is being used to test, as it's a dependency), ~~everything works fine~~ it works exactly the same way, except I can resize it.

**Comment by falkTX** [comment]
cant resize window in which format? which host?

The VST version works fine in all hosts I tested so far, with only keyboard focus being a problem sometimes.

**Comment by ThePython10110** [comment]
In Cakewalk by Bandlab, I can't resize the CardinalFX VST2. Also, the CardinalSynth VST2 crashes Cakewalk.

**Comment by falkTX** [comment]
The resizing issues should be fixed on the latest builds, please test.

**Comment by falkTX** [comment]
vst3 crash should be fixed, though it doesnt handle audio/CV buses correctly yet.

**Comment by falkTX** [comment]
Resize issues are fixed, the vst3 related issues should be discussed on its own dedicated ticket.
Closing
