### ISSUE TITLE
Vst3 versions problems in window 10

### ISSUE THREAD

**Issue by jojo535275** [DISTRHO/Cardinal#126]
Hello,

First, thank for Cardinal!
For a project i want to use a vcv rack embedded in a DAW with customized gui panels, so i need an access to the sources which is only available (in the hosted vst configuration) in Cardinal !

So i am trying tu use Cardinal on window 10 pro 64bit 

( copied the three vst3 " directories in C:\Program Files\Common Files\VST3 )

- When trying to load  " CardinalFX.vst3"  or  "CardinalSynth.vst3"  in reaper, i see the following message:

![problem cardinal](https://user-images.githubusercontent.com/65027759/150959526-339dfa00-76d8-419f-b1ac-b6e2ea332ebe.JPG)
 
- When trying to load  " Cardinal.vst3"  in reaper, it crashes reaper.

Alternatively, i tried with  VSThost (Hermann Seib) and i am getting the same message for the three .vst3 ( no crash with Cardinal.vst3 )

This path seems to be a "building path", we ca see it in GitHub actions !

Remark: for the "vst" version, no problem! When loading the two vst version ( CardinalFX.vst, CardinalSynth.vst ), in reaper, it works fine !

Muinto Obrigado

Joaquim

**Comment by falkTX** [comment]
Yeah the vst3 version is still experimental, as mentioned in the readme.

**Comment by jojo535275** [comment]
All right for me, i can play with the "vst" versions!
Thanks and have a nice day.

**Comment by falkTX** [comment]
This was fixed in fe748326f7b77a72567c880a25215b149d3c337e

**Comment by jojo535275** [comment]
Great, 
i just tested, and loaded successfully the 3 Vst3 plugins (with no Reaper DAW crash) on win10 !
Thanks falkTX for all that amazing work !
