### ISSUE TITLE
Linux/X11: can't alt-tab away from window since latest build

### ISSUE THREAD

**Issue by dromer** [DISTRHO/Cardinal#127]
Happens to be on fluxbox with debian 11/stable with `95a97b35dc8be044068f9ebb4a4630e93763f384`.

Verified on two separate machines (one intel onboard, other nvidia drivers).

**Comment by falkTX** [comment]
standalone, lv2, vst2 or vst3? which host?

**Comment by dromer** [comment]
Sorry, standalone.
