### ISSUE TITLE
Windows 64bit LV2 and VST2 crashes when scrolling pass QuantEyes

### ISSUE THREAD

**Issue by RCJacH** [DISTRHO/Cardinal#129]
As the title suggests, the plugin crashes when I try to scroll down in the module list window.
I can't figure out which plugin crashes Cardinal, but when sorting by module name, the last plugin that I can see the name of is QuantEyes, so it's likely the next few that's the cause of the crash.

**Comment by falkTX** [comment]
A side effect from 29122b180b63da45afcdc0ae12aa316cd371a98e
Doesnt happen on source builds, so I didnt notice. Will fix soon

**Comment by falkTX** [comment]
This is fixed on latest builds
