### ISSUE TITLE
VERBOSE=yes at the top level doesn't propagate to all commands

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/Cardinal#132]
It's customary that ```VERBOSE=yes``` causes all commands to be printed.

For Cardinal this flag doesn't propagate to a lot of directories and only some commands are printed.

(I tried to print the command that builds CardinalFX.so and it doesn't get printed with VERBOSE=yes.)

**Comment by falkTX** [comment]
dpf stuff uses VERBOSE=true

**Comment by yurivict** [comment]
I think the check should be VERBOSE!="".
This covers all possible situations.

**Comment by falkTX** [comment]
it doesnt cover the `VERBOSE=false` case ;)

**Comment by yurivict** [comment]
Then comparison should be with "1", "yes", or "true".
