### ISSUE TITLE
Current configuration should be saved as it's altered by user

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/Cardinal#134]
When Cardinal crashed for some reason - next restart brought back the initial screen and all modifications were lost.

**Comment by falkTX** [comment]
That is also a wont do.
Cardinal is a plugin and not meant to save any configuration besides what is saved within the host.

**Comment by falkTX** [comment]
Sorry to close tickets like this, but scope for Cardinal needs to be set from the start otherwise it quickly grows into a big beast.
And it is already complex enough as it is.

**Comment by yurivict** [comment]
The Cardinal executable when it's connected to Jack works essentially as plugin.

**Comment by falkTX** [comment]
Yes and that is the point. These standalones just dont have an actual way to store configuration, it is not something I implemented in DPF (the underlying plugin implementation).
Might change in the future, but it is not something I will deal for the time being. Consider the JACK standalone a convenient bonus, not the main product.
If you use Cardinal as intended, inside a host, the configuration will be saved as part of the host/project state.
