### ISSUE TITLE
VST3 on Win 7 doesn't run at all

### ISSUE THREAD

**Issue by bambax** [DISTRHO/Cardinal#136]
When launching the VST3 implementation one gets the error: 

    System directory Z:\home\runner\work\Cardinal\Cardinal\src\Rack does not exist. Make sure Cardinal was downloaded and installed correctly.

There is a "Dismiss" button but after that nothing loads.

(Win7, Reaper, VST3).

**Comment by falkTX** [comment]
duplicate of #126
