### ISSUE TITLE
Special characters in username in Windows

### ISSUE THREAD

**Issue by bambax** [DISTRHO/Cardinal#137]
My Windows username has non-ascii characters. The save as dialog points to the wrong user directory -- ie, the directory name is based on the username, but with wrong characters. (Win7, Reaper, LV2).

**Comment by falkTX** [comment]
This was likely fixed in 56305eb03710dfe1a9d88d210a86a8436b0377f0.
Confirmation with the latest builds would be very welcome, thanks.

**Comment by bambax** [comment]
This is indeed fixed for me with build 915 (same config as initial report). Thanks!

**Comment by falkTX** [comment]
Cool, closing the ticket then.
