### ISSUE TITLE
compilation error under ubuntu 20.04

### ISSUE THREAD

**Issue by michal-cab** [DISTRHO/Cardinal#138]
hello,
just installed all necessary deps but compilation process ends with following error:

Creating VST3 plugin for Cardinal
make[2]: *** No rule to make target 'resources', needed by 'all'.  Stop.
make[2]: Leaving directory '/home/tao/source/Cardinal/src/Cardinal'
make[1]: *** [Makefile:171: all] Error 2
make[1]: Leaving directory '/home/tao/source/Cardinal/src'
make: *** [Makefile:159: cardinal] Error 2

**Comment by falkTX** [comment]
was temporarily broken, just fixed on latest commit
