### ISSUE TITLE
host midi gate module / output 17 and 18 not working?

### ISSUE THREAD

**Issue by michal-cab** [DISTRHO/Cardinal#140]
it seems there is an issue with module Host MIDI Gate - it is not sending anything from gate 17 and 18 outputs. was testing it in ardour, reinitialized module, sent midi from pianoroll/virtaul keybord but there is just nothing on output. all other 16 is working just fine.

thnx for your work and keep rollin' :)

**Comment by falkTX** [comment]
Good catch! Fix right up
