### ISSUE TITLE
[X11] Copy paste between plugin instances crashes the UI

### ISSUE THREAD

**Issue by dromer** [DISTRHO/Cardinal#147]
Tried with both LV2 and VST2 in both Carla and Bitwig.

Works fine in 2 separate JACK instances.

**Comment by falkTX** [comment]
On Linux right?
There is something wrong with the x11 clipboard setup in pugl. there is a new branch to try, but I didnt switch as to not potentially break other things as regression

**Comment by falkTX** [comment]
Fixed in bcd1b9e2733d6a0b2e5392b8e4bd9616a5a2bec3
