### ISSUE TITLE
20.2: Fails to install: bin/Cardinal.vst3/Contents/*-*: No such file or directory

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/Cardinal#148]
```
cp -rL bin/Cardinal.vst3/Contents/*-*      /usr/ports/audio/cardinal/work/stage/usr/local/lib/vst3/Cardinal.vst3/Contents/
cp: bin/Cardinal.vst3/Contents/*-*: No such file or directory
```

**Comment by yurivict** [comment]
```bin/Cardinal.vst3/Contents/``` only has the ```Resources``` folder in it.

**Comment by falkTX** [comment]
I guess because it doesnt build for BSD at all.
See https://github.com/DISTRHO/DPF/blob/update-state-value/Makefile.plugins.mk#L104 for the relevant code part

I asked steinberg to give input on this, but so far nothing https://github.com/steinbergmedia/vst3sdk/issues/86

**Comment by yurivict** [comment]
> I guess because it doesnt build for BSD at all.

We do have the vst3sdk-3.7.4_build_25 package.
Any way to use it instead?

**Comment by falkTX** [comment]
No, Cardinal does not use the Steinberg VST3 SDK.
And it doesn't matter here anyway, this is just about a missing definition on what filename to use.

What are you using on BSD? "-linux" as string?

**Comment by yurivict** [comment]
> What are you using on BSD? "-linux" as string?

"-freebsd" can be used, I guess.

**Comment by falkTX** [comment]
It needs to be consistent, because otherwise plugin hosts will fail to load such plugins.
Consider creating a page, maybe a wiki entry, just to specify this for freebsd builds.

**Comment by yurivict** [comment]
> It needs to be consistent, because otherwise plugin hosts will fail to load such plugins.

I never used vst3. What apps work as hosts for it?

**Comment by falkTX** [comment]
Carla does but not on BSD. Maybe Ardour? Qtractor supports it too, via VST3 SDK.
In any case, the VST3 SDK itself has some example/test hosts I believe.

Eventually Carla will support it natively without JUCE, so we could support BSD, Haiku and all others at the same time.
But will take some time for that still.

**Comment by yurivict** [comment]
Juce is also available on FreeBSD.

**Comment by falkTX** [comment]
> Juce is also available on FreeBSD.

I know, but support still incomplete. And on Carla I am on an earlier version before some BSD changes were applied anyway.

Regardless, unless the VST3 SDK sources are patched, they will be looking for "-linux" prefix on the VST3 bundle which is wrong.

**Comment by yurivict** [comment]
Can VST be disabled during build for the time being?

**Comment by falkTX** [comment]
Right yes, just pushed b7d4847e1920a3d9c22e97dcd901360188e4c5a8 for that

**Comment by falkTX** [comment]
Forgot to close this, since it is fixed now.
I am open to build cardinal vst3 for freebsd though, we just need to pick a suffix name and stick with it in some official form.
