### ISSUE TITLE
No text input on MacOS in Reaper and Element

### ISSUE THREAD

**Issue by Nek** [DISTRHO/Cardinal#150]
When I try to enter text into the module search input I hear the system "input blocked" beep and nothing happens.
What's a recommended DAW to use to have text input working?
Also, would be nice to have it working in Reaper.

MacOS Monterey 12.1
Reaper 6.47

Element is a rather uncommon but useful VST/AU host. I think it's ok to ignore it for now.

**Comment by falkTX** [comment]
This is pretty much the same as #24 

Haven't had a single issue in Carla, FLStudio or Renoise about input.
On reaper some hide-ui, show-ui again might do the trick.
But anyway, let's centralize the discussions.
I will close this one, continue over at #24 please

**Comment by Nek** [comment]
Sure! Thanks for the quick answer and great product.
