### ISSUE TITLE
How to even install?..

### ISSUE THREAD

**Issue by TomasFaDZ** [DISTRHO/Cardinal#155]
Hi everyone, 
I know, this is lame, but I am having issues even installing Cardinal. I have windows 10/64bit version. I downloaded according release, pasted all the files into vst plugins directory and all i got is an error when loading plugin that says "Z:/home/runner/work/Cardinal/Cardinal/src"Rack" does not exist. make sure Cardinal was downloaded and installed correctly." what does this even mean? I dont even have a disk Z on my pc. Install instructions are very vague and I simply dont know what to do to make it work. I tried to paste it literally into every folder in my computer with vst plugins (program files etc), but still the same error. when i click on dismiss, it opens up completely empty, with no available modules. please help
![cardinal screenshot](https://user-images.githubusercontent.com/99922465/154576806-2a82d8f3-61f5-4570-98f8-8e78c9052d5f.jpg)
!

**Comment by falkTX** [comment]
Any success?

**Comment by illocanblo** [comment]
i have an error too.
has unpacked zip with files and copied a vst3 file to my vst3 plugins folder.
Ableton has found a plugin but cannot load it.
what did I miss?
![image](https://user-images.githubusercontent.com/99983924/154721324-d06b6387-1262-4ac7-9d61-5832c8594fd3.png)
![image](https://user-images.githubusercontent.com/99983924/154721405-8db8a6ab-cd91-4358-9fba-9511665f38f5.png)
the initial folder has contain a resources folder, but where should I place it? IDK

**Comment by illocanblo** [comment]
@falkTX thank you! vst2 has loaded perfectly in Ableton.

**Comment by falkTX** [comment]
Cool, glad it works now.
Closing the ticket then.
