### ISSUE TITLE
Keyboard input not working (Linux/Bitwig)

### ISSUE THREAD

**Issue by fractalf** [DISTRHO/Cardinal#159]
Hi,
input fields (search ++) are not receiving proper keyboard input. 

The most obvious is the search field which only receives `n` (and sometimes some weird chars)
![image](https://user-images.githubusercontent.com/5707457/154848618-0807c618-44a6-4638-8146-c3c52af906f2.png)

..but I also encountered this for other plugins
![image](https://user-images.githubusercontent.com/5707457/154848597-76fceecd-a117-41a2-a0d3-4b3770ab6ad3.png)

I'm on Linux Mint 20.3 (kernel 5.4.0-99-lowlatency)

**Comment by dromer** [comment]
Is that the VST2 or VST3? Which version of bitwig?
Plugin and Host are more important to mention than Distro and Kernel versions.

VST2 works fine in BW (4.1.6) here:

![](https://i.imgur.com/gboQ43n.png)

**Comment by fractalf** [comment]
@dromer Yea, same as you, VST2 and BW 4.1.6. 
ok....so maybe it's some weird local stuff going on here. I should reinstall my studio partition soon :/

**Comment by dromer** [comment]
Which window manager are you using btw? (could be related)

**Comment by fractalf** [comment]
> Which window manager are you using btw? (could be related)

I'm using Cinnamon (based on Gnome). Also I have the same setup on my laptop, but no weird stuff going on there..

Here's an example of one of the weirdest thing. Sometimes when recording audio in Bitwig parts of the **visual** waveform dissapairs!  :D

![Linux-waveform-bug](https://user-images.githubusercontent.com/5707457/154877700-95197c6f-1196-4022-95b4-0db92a8f8454.gif)

..anyway, very off topic here now
