### ISSUE TITLE
Knob/midi parameters not showing up in Bitwig

### ISSUE THREAD

**Issue by fractalf** [DISTRHO/Cardinal#160]
Normally when tweaking a UI knob it will show/activate in bitwig internal ui so that it can be modulated.
I believe I've seen this working fine in a vid about VCV vst in Bitwig.

Not working here however. Tweaking knobs for modules in Cardinal are not activated/shown in Bitwig
![image](https://user-images.githubusercontent.com/5707457/154848881-ce6bfa31-087e-4171-bbd7-1d1b38f679b0.png)

**Comment by falkTX** [comment]
That is not how it works in Cardinal.
The exposed parameters are only accessible at the moment through "Host Params" module, nothing else.

**Comment by fractalf** [comment]
Ah, thank you :) 
Now I understand

posting an image for reference, in case anyone else dont get this

![image](https://user-images.githubusercontent.com/5707457/154858888-03e99006-ed75-471e-8a5a-f39bf04df10a.png)
