### ISSUE TITLE
 OpenGL dependency on MSYS2/Mingw64

### ISSUE THREAD

**Issue by CommanderAsdasd** [DISTRHO/Cardinal#161]
Hi! Thank you for your wonderful work.

Can't figure out from docs how to build it myself on MSYS2/MinGW, drops with error:
`Makefile:96: *** OpenGL dependency not installed/available.  Stop.`
https://github.com/DISTRHO/Cardinal/blob/1260ca840f0b5ecd16751388d6f430de7d684304/Makefile#L96
Did a `git submodule update --init --recursive`, gcc should in theory compile it with `-lopengl` option
everything that I found regarding opengl in pacman:

```
pacman -Ss opengl | grep installed

mingw32/mingw-w64-i686-cglm 0.8.4-2 [installed: 0.8.3-1]
mingw32/mingw-w64-i686-freeglut 3.2.1-2 [installed]
mingw32/mingw-w64-i686-glm 0.9.9.8-1 [installed]
mingw32/mingw-w64-i686-openal 1.21.1-3 [installed: 1.21.0-1]
mingw64/mingw-w64-x86_64-freeglut 3.2.1-2 [installed]
mingw64/mingw-w64-x86_64-glfw 3.3.6-1 [installed]
mingw64/mingw-w64-x86_64-glslang 11.6.0-1 [installed]
mingw64/mingw-w64-x86_64-libepoxy 1.5.9-1 [installed]
mingw64/mingw-w64-x86_64-openal 1.21.1-3 [installed]
mingw64/mingw-w64-x86_64-python-pyopengl 3.1.5-2 [installed]

```
maybe somebody will be so kind and will commit dependency list here (or in comments):
https://github.com/DISTRHO/Cardinal/blob/7f98c0731cdf2a8f5f7f42a2e2132f4ef2e0183e/docs/BUILDING.md?plain=1#L121

**Comment by falkTX** [comment]
hmm that is unusual. this check comes from DPF, and if using windows it always enables opengl.
what is your output of `gcc -dumpmachine` ?

you might need to set CC and CXX explicitely, in case the default $CC and $CXX are not producing windows executables

**Comment by falkTX** [comment]
Closing due to lack of response. Will fix the build for symlinks under msys2/windows later on.
