### ISSUE TITLE
Ildaeil should ask for Carla's path on Windows...

### ISSUE THREAD

**Issue by ThePython10110** [DISTRHO/Cardinal#169]
It might be easier to simply have Ildaeil ask for Carla's path on Windows than to ship Carla with Cardinal.
After 'asking' through a file select menu or something, it could just store the path in a file... I haven't checked the code to see how easy that would be... but it might work.

**Comment by falkTX** [comment]
I dislike the idea of Cardinal saving things on disk, it shouldn't need those.
If future Carla releases get an installer, it would solve this matter.

**Comment by falkTX** [comment]
As per #192 Windows builds now have an installer, which includes Carla.
The regular zip with the dlls does not, as that would duplicate too much data, but seems on Windows people really want an installer anyway.
I consider this fixed now. This change will be part of 22.03 release.
