### ISSUE TITLE
cardinal.vst is missing in 22.02 built Cardinal-win64-22.02.zip

### ISSUE THREAD

**Issue by DirkOlten** [DISTRHO/Cardinal#181]
Hey nice work, but I cannot try. (the vst3 are not working on my Abeton Live 11 (lite) /Win10)

In the current download of release 22.02 the cardinal.vst seems not included.

https://github.com/DISTRHO/Cardinal/releases/download/22.02/Cardinal-win64-22.02.zip

![grafik](https://user-images.githubusercontent.com/11752344/155850095-c838a7b7-9092-46d0-a5b0-584a52cbda22.png)

Dirk

**Comment by falkTX** [comment]
Please see the README.

> **Main**
>
> This variant provides 8 audio inputs and outputs and 10 CV inputs and outputs.
>
> NOTE: Due to VST2 format not supporting CV ports, this variant is not available for VST2.
