### ISSUE TITLE
Resolve Substation and BSD-3-CA potential conflict with GPLv3

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#182]
Just leaving a note about this.

**Comment by Simon-L** [comment]
Related commits, for reference:
https://github.com/DISTRHO/Cardinal/commit/ba48ef0b27bf7e4455c7b456ec516ba9da597073
https://github.com/DISTRHO/Cardinal/commit/dd661db6b8c3c13d1fdea9eb8c8821840fee9aec
(Search: https://github.com/DISTRHO/Cardinal/search?q=substation&type=commits)

Next step is contacting the original author?

**Comment by falkTX** [comment]
Yes, please do so.
There is no way to do that over the gitlab project, as https://gitlab.com/slimechild/substation-opensource does not have tickets/issues enabled

**Comment by falkTX** [comment]
I am closing this ticket since it is not something for Cardinal to do, issue is somewhere else.
Just to keep the issue tracker clean
