### ISSUE TITLE
Binary Installer (msi) format for windows, and duplication of assets in the downloaded binary zips

### ISSUE THREAD

**Issue by wpostma** [DISTRHO/Cardinal#185]
I may be able to assist with creation of a windows installer in msi format, if you have that in your roadmap.

It seems the binary zip contains three formats in one zip file at least for the windows target. That seems highly wasteful of the download size, if there is a common set of resource assets, surely an installer (even a shell script for linux) would make a large amount of sense versus a zip file with three times the assets copied.

**Comment by wpostma** [comment]
Alternatively separate Win64-LV2,  Win64-VST3,  Win64-VST downloads would make sense. 99% of win64 daw users are going to want VST3 frankly, in 2022.

**Comment by falkTX** [comment]
Windows installer has been added in #192
