### ISSUE TITLE
Deploy Failed fron Ableton to MODULARE DUO X

### ISSUE THREAD

**Issue by aveniridm** [DISTRHO/Cardinal#188]
Hi, since update 22.3 / 22.4 simply cardianl no longer works for my MOD DUO X. I tried to make any patch (even very simple) by putting a normal Plateau reverb and saving to MOD. When I restart, the pedal board loads but there will be no more audio and therefore it does not work. Also useless for anything else concerning cardinal, midi sync, internal midi.

Error is always the same: I do a patch on Ableton through the VST, I execute the deploy that works, sending audio to the MOD duo (for example a simple connected VCO). I run the save inside the pacth bank and after reboot it won’t work anymore. To get it working again I will have to open ableton again, load the VST and deploy again. Needless to say, it doesn’t work without a computer.

this is an example of a simple patch I made to test but it doesn’t work
https://pedalboards.moddevices.com/pedalboards/62296d22c21e5a25880ccbd6
plus the prints have never been able to view the print screens inside Cardinal MINI.

Tried to uninstall everything and install again, it just doesn’t work in my case anymore.

From the video you can see clearly, it works as long as you do not turn off the device, even saving as you can see there will be no more way to make the clock emit, both internal and external

https://www.youtube.com/watch?v=5yI3FDOmPt8&feature=youtu.be

thanks for any help

attached a simple pact made on the vst
[TEST_VCO.vcv.zip](https://github.com/DISTRHO/Cardinal/files/8221353/TEST_VCO.vcv.zip)

Tried using the VST on reaper but no results

**Comment by falkTX** [comment]
> since update 22.3 / 22.4

what update in specific are you talking about here?

**Comment by aveniridm** [comment]
> > since update 22.3 / 22.4
> 
> what update in specific are you talking about here?

Sorry, The update of Cardinal Mini on MOD DUO X
![Schermata 2022-03-10 alle 11 16 21](https://user-images.githubusercontent.com/66583982/157641091-1bca84f9-6df4-4b82-b67a-fa29f981c16a.jpg)

**Comment by aveniridm** [comment]
I tried to save 3 presets, assign all but nothing works, I would like to understand if it is only me who has this problem and I believe it is on the device

**Comment by dromer** [comment]
Hmm, of the 3 pedalboards currently available only the one from @falkTX works -> https://pedalboards.moddevices.com/?https%3A//distrho.kx.studio/plugins/cardinal%23fx&unstable=true

Can you check that it loads for you as well?
Would then have to debug the ones you shared of course.

**Comment by falkTX** [comment]
I can reproduce this issue on a duox and the patch uploaded.
the duox is not saving the patch data.

**Comment by falkTX** [comment]
I am saying that I can trigger the issue here on my side too. That is the first step, now need to see what is going wrong...

**Comment by aveniridm** [comment]
> Sto dicendo che posso innescare il problema anche qui dalla mia parte. Questo è il primo passo, ora devo vedere cosa sta andando storto...

**Comment by aveniridm** [comment]
> I am saying that I can trigger the issue here on my side too. That is the first step, now need to see what is going wrong...

thanks

**Comment by aveniridm** [comment]
> Hmm, of the 3 pedalboards currently available only the one from @falkTX works for me -> https://pedalboards.moddevices.com/?https%3A//distrho.kx.studio/plugins/cardinal%23fx&unstable=true
> 
> Can you check that it loads for you as well? Would then have to debug the ones you shared of course.

it works for me too until I restart MOD DUO

**Comment by dromer** [comment]
Save the patch locally first, then it should have all the assets needed stored on the unit. Otherwise it will have things in `/tmp/` directory that is empty after a reboot. (I didn't test rebooting yet, but that could be it)

**Comment by aveniridm** [comment]
> Save the patch locally first, then it should have all the assets needed stored on the unit. Otherwise it will have things in `/tmp/` directory that is empty after a reboot. (I didn't test rebooting yet, but that could be it)

OK
In the meantime I recorded a video with the procedure I do

https://youtu.be/uKc2jfOmsK8

now i debug and place here

**Comment by aveniridm** [comment]
in attach the Cardinal patch
[test.vcv.zip](https://github.com/DISTRHO/Cardinal/files/8226884/test.vcv.zip)

**Comment by falkTX** [comment]
I found the problem. It is with Cardinal, not in MOD.
Will push a new build soon, either later today or tomorrow.

**Comment by aveniridm** [comment]
> I found the problem. It is with Cardinal, not in MOD. Will push a new build soon, either later today or tomorrow.

I am really relieved (: happy that I will be able to use it again soon :)) thanks..

**Comment by falkTX** [comment]
Builds are under way, but they will take a while.
I will do the update tomorrow.

**Comment by aveniridm** [comment]
all the time you need for sure, thanks again:)

**Comment by falkTX** [comment]
Fix has been pushed to the MOD plugin store.
Go to the plugin store on the web gui, then utilities, then cardinal mini, and click to update.
Device might need a reboot if you already had loaded cardinal previously.
