### ISSUE TITLE
Host Time does not work on MOD builds

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#190]
Maybe due to single-precision optimizations, need to investigate

**Comment by dromer** [comment]
They have worked before for me though. Single-precision builds from some weeks ago.

**Comment by falkTX** [comment]
Ok it works for me on a Dwarf too.
not sure what went wrong before. Will check later between all units to ensure it works on all 3.

**Comment by dromer** [comment]
Works fine for me on DuoX at the moment.

**Comment by falkTX** [comment]
yeah, couldn't reproduce anymore. will close now and open if it happens again
