### ISSUE TITLE
Knob rotation/fader position doesn't update

### ISSUE THREAD

**Issue by Vlusky** [DISTRHO/Cardinal#195]
note: the recording is in REAPER v6.38 but it's still there after i updated it

Windows 10, Reaper v6.51, VST3 22.02

https://user-images.githubusercontent.com/90129039/159039570-a3ba90d5-7f3c-4c40-8d5b-c27347a8fdc0.mp4

**Comment by falkTX** [comment]
This supposedly is fixed on the latest builds, did you try those yet?

**Comment by Vlusky** [comment]
no i have not, i'm going to try those now. thanks!

**Comment by falkTX** [comment]
any news on that? 22.03 was also released, which supposedly fixes this issue.
would be nice to confirm, thanks

**Comment by dromer** [comment]
@Vlusky can you confirm whether or not 22.03, or latest build on gh-actions, works for you?

**Comment by falkTX** [comment]
Closing ticket due to lack of feedback.
