### ISSUE TITLE
Feature Request: MIDI Note Retrigger

### ISSUE THREAD

**Issue by Logos-Coder** [DISTRHO/Cardinal#200]
First of all, this is a wonderful project! it's getting me back into the world of VCV and modular synthesis!

One thing that I think is lacking from Cardinal that is in base VCV rack is MIDI note retrigger. While you don't really need this feature for polyphonic patches (as it is basically built-in to how polyphony works), it is almost essential if you are trying to make a monophonic synth patch for example. Retrigger is useful outside of that for other types of patches as well. A good use case is for re-triggering envelopes, or resetting oscillators.

**Comment by falkTX** [comment]
Wouldnt that work if the gate closes and opens quickly as well?
The gate not closing and reopening for monophonic mode is often very frustrating

**Comment by Logos-Coder** [comment]
> **falkTX**
> Wouldnt that work if the gate closes and opens quickly as well?

Yes that would work as well. Though it would not be ideal in all cases. you could get that functionality with how I describe the feature below and a XOR gate.

---------------

> **falkTX**
> The gate not closing and reopening for monophonic mode is often very frustrating.

Yes I agree with that. I am not wanting to change how the gate currently works. What I am suggesting is adding a new output to the 'Cardinal Host MIDI' plugin that sends a pulse/trigger every time a MIDI note is sent.

------------------------------

## Here is a basic example:

This is the demo patch from VCVRack 1.1.6.  My version is a bit out of date but the example still works:

![VCVRack-Demo-Patch](https://user-images.githubusercontent.com/47828239/160043506-f0b39cbe-b661-48f0-b69a-b0d0ab85a544.jpg)

Now if I wanted to create a patch in Cardinal with the same functionality as the VCV demo patch It would look something like this as of Cardinal 22.03:

![Cardinal-Demo-Patch](https://user-images.githubusercontent.com/47828239/160043482-7613da3e-c5ee-482c-965d-58faee49f4df.jpg)

**The top set of modules** Is for recreating the sound of the demo patch. The couple extra modules in the top row are there because the stock VCV modules have a slightly different feature set compared to the BogAudio modules.

**The bottom five modules** is how I can currently recreate the `RTRG` function on the stock VCVRack MIDI-CV module in Cardinal. While this works, and quite well, having it as a built-in feature would probably be more efficient then what I made here.

I can provide this patch if you are interested in seeing it.

---------

I don't know how time consuming this would be to implement, and I understand if you don't have the time to put this in. I just think it is a vary important feature that is currently lacking. I think I saw or heard somewhere that you are looking into getting the stock VCVRack plugins working in Cardinal. Is this true? If so, having there MIDI-CV module would fix my issue here. Is there a place to donate to you, falkTX? I wouldn't mind donating to help get the feature sooner.

~ Thanks; LogosCoder

**Comment by falkTX** [comment]
Ok yeah I can understand wanting the retrigger, makes sense for the multiple-notes-while-still-monophonic usecase. still think the default implementation (which is copied from original vcvrack) is not ideal, but for the sake of keeping compatibility the core modules (midi-cc, midi-map, midi-cv, etc) keep the same behaviour as much as possible.

that host midi module is the cardinal variant of midi-cv and cv-midi from vcvrack, I purposefully made them a tiny bit different so it is not a blatant copy, but still have the same functionality in the end.
what is coming are the fundamental modules, a work in progress at the moment.

for donations, due to artwork shipping with cardinal having "non commercial" clauses, I cannot provide direct links. but they will be easy to find if you look for any of my other projects.

anyway, back to the topic. on the retrigger I can add it to the host-midi output jacks. there wont be an input for it, but that is fine I guess. looking at the panel it seems an extra output still fits.

**Comment by Logos-Coder** [comment]
Understandable about the donations. If what you suggested works that sounds great to me.

I am curious of what you mean by `the default implementation ... is not ideal`.  Are you talking about cardinal's default implementation, or VCVRack's? I am all for improvements, and if you have a better way of implementing this, that is great.

The inputs on the host-midi sent out externally, Right? So yah, I guess there isn't much of a point in having an input, because midi probably doesn't have a note trigger as part of it's specification. I don't know much about the technical aspects of midi.

**Comment by falkTX** [comment]
> I am curious of what you mean by `the default implementation ... is not ideal`. Are you talking about cardinal's default implementation, or VCVRack's?

both, since as I said cardinal copies vcvrack stuff in order to try to remain compatible.



> I am all for improvements, and if you have a better way of implementing this, that is great.

eventually I will try to do a host-midi v2, where I feel free to break from how vcvrack works because the "old" module will still be there. but this is not something for the short term.

**Comment by Logos-Coder** [comment]
Ah Okay. That makes sense. Well I look forward for when host-midi v2 becomes a reality, and for what else is in store! You make great work!
