### ISSUE TITLE
Polyscope has about 1/5 (guesstimate) chance of crashing my DAW at load

### ISSUE THREAD

**Issue by rafaelferreiraql** [DISTRHO/Cardinal#201]
And it's the only oscilloscope module currently available, too. (**EDIT:** Well, I forgot Full Scope! Still jank for analysis and lacks the, well, *poly* aspect but yeah it exists) I'm using 64bit Reaper on Win8. I've been using VSTi primarily but I *think* I've gotten this issue on VST3 too.

Can also happen when duplicating an already placed instance.

**Comment by dromer** [comment]
Can you try the LV2 on Reaper? (although may not make much of a difference if it's related to the engine.

I have seen patches crash with some signals into Polyscope, although that was on Rack2Free and not Cardinal.

Can you please share/paste a patch that you can reliably get to crash?

**Comment by falkTX** [comment]
Just did a memory check on Polyscope but can't detect issues.
You used 22.02 perhaps? Or are you on 22.03?

**Comment by rafaelferreiraql** [comment]
> Just did a memory check on Polyscope but can't detect issues. You used 22.02 perhaps? Or are you on 22.03?
I'm using the same build you sent me earlier. However, it already used to crash on Stable.

> Can you try the LV2 on Reaper? (although may not make much of a difference if it's related to the engine.
I'll try it later! Reaper didn't recognize the LV2 so I just deleted that one, but thinking back I just didn't set a LV2 folder for Reaper, so that's my bad.

> I have seen patches crash with some signals into Polyscope, although that was on Rack2Free and not Cardinal.
I can tell some Amalgamated Harmonics modules used to crash a lot on VeeSeeVSTRack. Although in my case, Polyscope crashes upon loading, not after getting signal.

> Can you please share/paste a patch that you can reliably get to crash?
Unfortunately I can't quite *reliably* get it to crash. It feels very random. Also, it seems like if Cardinal is fully loaded and I have already successfully loaded Polyscope in it, the plugin won't crash anymore during that session.

**Comment by rafaelferreiraql** [comment]
UPDATE: Not out of the woods yet, but haven't gotten a crash from Polyscope since. Ihaven't been using it that often, but I'd think I would've crashed at this point. Will update if I do get a crash.

**Comment by falkTX** [comment]
> UPDATE: Not out of the woods yet, but haven't gotten a crash from Polyscope since. Ihaven't been using it that often, but I'd think I would've crashed at this point. Will update if I do get a crash.

It has been more than 1 month, I am coming back to this.
Since I could not reproduce, and not even see bad things with a memory checking tool, I am going to assume the issue was somewhere else. Maybe something got in the way of polyscope.

And you haven't reported a crash since, let's assume it is good. If not, feel free to reopen. (or leave a comment if GitHub is weird and doesn't allow to reopen in case the bug is still there)

On another note, Fundamental Scope is in now too!
Not yet in a stable release, but I am doing the last items for a new 22.05 release now.
So it is only a couple of days..

**Comment by rafaelferreiraql** [comment]
Yeah, I think we're good here! Haven't gotten a crash since at least.
