### ISSUE TITLE
Problems with adding my modules (unless_modules)

### ISSUE THREAD

**Issue by unlessgames** [DISTRHO/Cardinal#208]
I saw my modules on the list of possible additions and I'd like them to be included with Cardinal if possible.

I have trouble building the project with my modules added to the plugins.cpp. Below I paste my reply to @TheGuyWhoo asked me about this in [my repo](https://gitlab.com/unlessgames/unless_modules/-/tree/v2).

So I've looked briefly into this and started patching the plugins.cpp file following [the guide](https://github.com/DISTRHO/Cardinal/discussions/28).

The plugins.cpp file looks like [this](https://gitlab.com/unlessgames/unless_modules/-/snippets/2290877) after adding my modules

But the problem is I have a global theme defined inside my plugin header (it's called unless.hpp in my repo), which is being accessed by all of my modules. 
It is loaded from disk when the plugin is initialized (or written to disk if it doesn't exist) inside [unless.cpp](https://gitlab.com/unlessgames/unless_modules/-/blob/v2/src/unless.cpp). 

The `Theme` struct itself is in [src/theme.hpp](https://gitlab.com/unlessgames/unless_modules/-/blob/v2/src/theme.hpp) with a helper `ThemeFile` which does the read/write).

I understand I would need to somehow add it inside the Cardinal/plugins.cpp but I don't know how. 

Any help would be appreciated!

**Comment by falkTX** [comment]
Hi! thanks for the interest.

One of the goals for Cardinal is to have it be a proper plugin, loading and writing config files is something I am personally against for plugins to do.
So best would be for your plugin to stick with a dark theme by default. If you want, allow to have theme options but save it as part of the project/session, not as a global config please.

you can use the `USING_CARDINAL_NOT_RACK` compiler macro to make the code behave one way for Cardinal, and if undefined/unset do it the previous way for regular VCV Rack.

For the build issues, don't worry too much about them, it is likely just a minor conflict that will need very specific tweaks in very specific places. You can just submit a pull request and we will help on the final steps.

**Comment by unlessgames** [comment]
I see, thanks for the fast response!

I'm fine with omitting the config file and locking the theme to the default (which is a somewhat dark grey look) but I'd still need the global (plugin-wide) theme object to avoid rewriting a bunch of stuff (all my graphics are procedurally drawn and the theme object is being used inside every widget to get colors). 

Could that work or would this need restructuring to conform to Cardinal?

**Comment by falkTX** [comment]
I think that should work fine.

The best and simplest approach I see here is for you to create a dedicated function that initializes theme stuff (without referencing a theme object as argument) that you then call on your plugin init for vcv rack and on the custom plugin.cpp cardinal init too.

let me know if you need help on this.

**Comment by unlessgames** [comment]
Alright, I got the build working and I've submitted a pull request.
