### ISSUE TITLE
issues showing some modules

### ISSUE THREAD

**Issue by missnightwhore** [DISTRHO/Cardinal#210]
Hey Felipe, 
I've been following the evolution and the development of this project for quite some time already - and first of all, I just want to thank you for the efforts you added to develop this tool for us - the musicians and music producers.  I can feel there is hard work behind and your involvement is amazing. So I really appreciate a lot your work and the fact you keep this project alive involving that much by constantly improving it.

Considering that after 15 years of using Ableton as my main daw, I was about to abandon against for the incredible possibilities that these eurorack emulations opened for me, then I discovered Cardinal and I said that might be the right thing for me.  Because I started to use Cardinal as my main thing to create and generate new sounds + ideas for my productions - pretty much the whole creative process - I desperately wanted to be able to have a version with  Fundamental modules inside.
 I know this might sound odd, but I'm using these modules a lot in my projects,  helps me to save a lot of  CPU and by tweaking or messing around with them, it brings me the results I'm looking for.

So I've been waiting and researching on my own a lot - to find a possibility and resolution of my issue, as I never had the chance to see them in Cardinal 22.03 (the version I use to work with) ,  but many times I wondered if my daw got an issue (and maybe it's not able to read the vst file as supposed - at least older builds)  - and basically I just have no luck at all because of the .dll files might be glitching "communicating" proper along with daw.
I have to mention I'm quite new to this GitHub community and I don't do code at all, so I had to deal just with the built files I was able to find) . 

In the beginning, I just tough maybe there are not included and I believe that probably is not that easy, and I just preferred to  a few months for future releases hoping that will show up  (checking constantly the table with possible future add-ons to be included and a good reason for them) 

then I noticed that some youtube guys had them with cardinal -   so probably I considered that I might check a different version, I started to make some researches, and I tried some other versions you released,  having them scanned by the daw.

I ended up installing and testing about 10 versions and seems that only recent builds [22.03/ 22.04] are scanned and detected easily, but by checking the module lists (neither synth or fx)  there is no such thing in regards of the fundamental library.

However, in the older versions, Ableton stays on "scanning Cardinal...."   (for hours) -  and nothing happens even once I let them be "scanned" for 6 hours. I tough maybe my daw got stuck on this scanning process - just because I'm dealing with old versions that are a bit outdated, and the .dll files don't work in an optimized way along with the daw.
 I canceled the scan, reopened the daw, and these builts will show up in the VST lists, so the daw recognizes them, but it still look like something is messed up, and what I got confused me even more: 

v22.03 + some older releases actually contain the  "VCV" label in the library, the thing is that
in v22.03 inside was only one module - the filter VCF. (which has black skin and looked a bit different than the original, but the controls and positions of them were the same, but that was the only module ) . 

So, after so many attempts by downloading and scanning different builds/updates (of the same [or not] release version) giving me the same thing, I decided to install the .exe version,  -  but this one doesn't ask in the installation process to pick up a VST directory path and its not detected by my daw at all.  [even I included the default VSTPlugins folder for x64 vst 2 from Program Files]

After all this, 
I went searching for some even way older versions -  hoping that I will see the package there - no matter that the module base its limited;
 In the end,  I was able to find one version released around November last year [a00020e5 tagged], with about 400 modules, and with this one, I finally got the full Fundamental collection,  so I tough my problem its solved and I will use this
but shortly I realized that my daw is detecting this as an effect plugin, exactly like the FX version instead of Synth one -  [ and no matter how many trials for installations or workarounds I did thru scan process in my daw - I manage to get only one file -  
 there was no synth version and no FX version, just a single file called "Cardinal" - but behaving like an effect.

I almost gave up just to accept the fact I won't ever have them, but yesterday in the morning I  started to search again and I also saw somewhere something that we should forget about these modules as won't be ever available due to some policy of the VCV rack. ( I  believe that was the whole idea of that post, I might be wrong, but I'm not able to find that topic anymore. So, I kindly ask you if it's possible to recommend to me a version that got all this collection inside and behaves like the Synth? 
Did Cardinal use to have them only in primary versions and later on the collection was removed? If yes, might any small chance to see them in the future?
 I don't care If will have to use an initial version that only got a few collections as long as it contains the full Fundamental package on it.
 I don't know what else I could do,  and I feel so unlucky by struggling to resolve this, maybe reinstall my daw, rescan my stuff and try again, or I just have to forget completely about them as won't be any possibility to have these modules there. 
Thank you so much for your time checking this.
Maria

**Comment by missnightwhore** [comment]
Hey Felipe
Amazing info looking forward, great times will come for me!
I really " suffered" for them ))  and really didn't know what to believe anymore and was really confusing. 
cheers again for your work into this project

**Comment by dromer** [comment]
@missnightwhore there are of course many replacement, and functionally equivalent, modules inside Cardinal already. But I get that if you are really "used" to these default modules being there it would be confusing :)

**Comment by falkTX** [comment]
Fundamental modules are now present on the latest builds.
Unity and Viz are intentionally missing, I won't bother with those.
Also note that the new Fundamental panels are still a work in progress, you can check the status in https://github.com/CardinalModules/Fundamental/issues/2

Closing this ticket then.
