### ISSUE TITLE
Feature request: "Favorite" modules selection

### ISSUE THREAD

**Issue by rafaelferreiraql** [DISTRHO/Cardinal#211]
VCV Rack has, i believe (I don't actually use it, but I've seen it in some videos) a Favorites option for modules, so you can save a selection of favorite modules for quick access on the module browser.

I'm guessing Cardinal does not have it because it doesn't save config files in the first place; however, I've been saving settings (like plugin size, control preferences and the default patch) via updating the default VST preset... Thus, if a "favorite" system were to be implemented and could persist in a plugin preset, it would be immensely helpful, especially when keyboard support is still a little jank, which makes the search for modules that little bit more cumbersome in the first place.

**Comment by falkTX** [comment]
This has been implemented in 310cab2d6d9da48b959d736bfc2aa8e9b68126b9

Noticed a few extra things that were not being saved, added those as well.
