### ISSUE TITLE
Failed to load VST3 x64 in latest Ableton

### ISSUE THREAD

**Issue by Ariloum** [DISTRHO/Cardinal#212]
I installed Cardinal 22.04 x64 for windows and when I'm trying to load it in the Ableton 11.1.1 it fails
![2022-04-15 13_04_58-Untitled_ - Ableton Live 11 Suite](https://user-images.githubusercontent.com/6816952/163558364-b8f89e35-7cc9-44e3-a4b5-34d02947a82f.jpg)

**Comment by falkTX** [comment]
Yes, known issue. VST3 support is incomplete.
VST3 discussion should be kept in #41, closing this ticket.
