### ISSUE TITLE
48kHz sample rate and Host TIME module reset bug (VST2, MacOS Catalina)

### ISSUE THREAD

**Issue by someone89a** [DISTRHO/Cardinal#215]
Hi, just downloaded and the first thing I noticed is that when running the VST2 version of Cardinal in Ableton Live 11 at 48000hz, the reset trigger on the Host TIME module will act erractically, sending out triggers completely randomly. 

This does not occur on the AU version. I cannot comment on the VST3 version as that one will not load in Ableton Live.

**Comment by falkTX** [comment]
> Another issue - running the AU version at 48kHz makes the reset trigger occur every bar.

I have seen this in FLStudio too.
Will investigate soon.

For you case, does anything change/improve if you pick a different DAW BPM?

**Comment by falkTX** [comment]
Issue happened every time the host did a split cycle, this being processing audio in smaller chunks than the typical buffer size as set in the audio driver.
There was some wrong logic, corrected in https://github.com/DISTRHO/Cardinal/commit/c46d659340525f963c95a58747d06deabac9bd9b
