### ISSUE TITLE
View settings not persistent after UI reopening

### ISSUE THREAD

**Issue by dromer** [DISTRHO/Cardinal#22]
Things like room brightness etc.

**Comment by falkTX** [comment]
This needs more details.
Format and host.

Do you see the parameters assigned to this changing in the host?
They should be kept in sync.

**Comment by dromer** [comment]
What I mean is -> change view setting manually. close cardinal window. reopen cardinal window -> view settings have reset

**Comment by falkTX** [comment]
sure, but check what happens with plugin parameters exposed to the host.
though I guess I will be able to reproduce it once I load the lv2 here.

**Comment by dromer** [comment]
Ah! now I understand. And I found the parameters for these settings in the carla menu!

However this still doesn't restore the settings after re-opening the ui.

**Comment by dromer** [comment]
Just built `738a0c820e465a6feda0553f079f6301f5e657e8` and now it is persistent in vst2. Not in vst3 or lv2.
