### ISSUE TITLE
CPU spike when plugin is idle.

### ISSUE THREAD

**Issue by TheGuyWhoo** [DISTRHO/Cardinal#220]
If I have a section in my project where I'm not making use of cardinal, in those sections I experience crackling. It's not immediate and seems to get worse and worse the longer it's idle, until you feed it midi or something then the issue resolves.

**Comment by dromer** [comment]
Which version of the plugin? Which OS? Which DAW?

**Comment by TheGuyWhoo** [comment]
Latest version, 64 bit linux mint, reaper. Sorry about that.

**Comment by dromer** [comment]
Latest being release version or build from github CI?

**Comment by falkTX** [comment]
dont think version matters.

this is likely a daw feature that cuts on cpu processing time for plugins that reportedly are doing nothing.
for example, an FX on a mixer track that has not received any audio in the last 30s. or a synth/intrument/midi track without notes

not sure if there is anything we can do about it, seems the best way to go about this is to somehow tell the host to not auto-deactivate the plugin.
I have seen how some plugins try to counter this, by for example outputting very low-level inaudible noise or sending midi-sensing messages. but those are very ugly hacks we should not rely on in my opinion.

**Comment by TheGuyWhoo** [comment]
Turning that option off does seem to fix it. Sorry for late reply, kinda forgot.

**Comment by falkTX** [comment]
> Turning that option off does seem to fix it. Sorry for late reply, kinda forgot.

can you describe that in more details? perhaps a screenshot too if possible.
so we write about this on the faq, for posterity.

**Comment by TheGuyWhoo** [comment]
Yes, you tick off this option in vst settings

![Screenshot from 2022-05-07 19-26-17](https://user-images.githubusercontent.com/72744967/167265253-4f028dd9-68c2-45b5-8135-5dc4075e7d5a.png)

The one with the white square around it.

**Comment by falkTX** [comment]
Please try with the latest builds from https://github.com/DISTRHO/Cardinal/actions
for VST2, Cardinal will now say "no" when asked if it supports offline rendering (which is indeed correct, the dedicated offline render API is not implemented, but not needed either anyway)
Let me know if anything changes or remains the same, thanks!

**Comment by falkTX** [comment]
Closing due to lack of feedback, assuming fixed.
