### ISSUE TITLE
Unable to launch Cardinal Standalone on Windows 10/11 x64 due to communication error with jack server

### ISSUE THREAD

**Issue by sidec** [DISTRHO/Cardinal#221]
I used installer from Cardinal-win64-81ad41ad action build (the same issue was with the latest release) and chosed full installation, including jack, which adds ~50mb to installation btw. Trying to run Cardinal as standalone app doesn't work, as it complains about failling to create client and communication error with server.    but it couldn't find it. If running standalone app requires manual jack run then where is jack standalone installed on Windows 10/11? I run search on system disk for jack.exe,

**Comment by falkTX** [comment]
You need to have JACK installed and running, see https://jackaudio.org/ for details and downloads.

**Comment by sidec** [comment]
thanks, this is what I've done eventually. but why there is such option inside installer?

**Comment by falkTX** [comment]
why shouldnt there be?

**Comment by sidec** [comment]
I must not explained the problem correctly. I assumed that if there is an option checked in Cardinal installer to install jack alongside the standalone version of the plugin, jackd will be installed somewhere in the system. However, as far I am aware, no such thing happens and an user is required to install JACK from its website and run it him/herself. Upon this my question is based - why such option exists if its only function is to mislead users, as obviously it doesn't make installer to install jack despite what it says? Expected vs actual.

**Comment by dromer** [comment]
The binary is a "jack standalone" application. Afaik the installer doesn't say that it will install JACK.

Just like for a VST2 or LV2 plugin you'll need to install another application to run these plugins, for the jack-standalone you need to have JACK installed.

Makes sense to me.

**Comment by sidec** [comment]
Makes sense, thanks
