### ISSUE TITLE
open303 slide

### ISSUE THREAD

**Issue by seanjean3000** [DISTRHO/Cardinal#222]
Not sure if this is a Cardinal issue or an open303 issue, but slide doesn't work for me. I've tried sending MIDI with overlapping notes, pitchbend messages (does change pitch at note on, but no bending mid-note), and using the phrase-seq-16 module with note ties--that seems to behave as an accent, oddly.

Anyone else have this issue, or know how to get slides going?

**Comment by dromer** [comment]
Unfortunately Open303 is no longer being developed and currently marked "hidden" in the library (both in VCV and in Cardinal).
Only legacy patches can still be opened, but it can no longer be used directly.
