### ISSUE TITLE
Cardinal crashes when trying to load a saved patch

### ISSUE THREAD

**Issue by maxigaz** [DISTRHO/Cardinal#225]
Using Arch Linux and Pipewire, Cardinal crashes when I try to load a particular patch I saved earlier.

It happens both with Cardinal 22.04, installed from the Arch repo `community`, and the latest artifact binary, downloaded from GitHub.

See the patch attached to this issue here: [cardinal-patch.zip](https://github.com/DISTRHO/Cardinal/files/8662953/cardinal-patch.zip)

**Comment by dromer** [comment]
Can confirm the segfault. I unpacked the patch and started removing some modules to see if it would load.
After removing two of the Bogaudio VCO modules I could load it again.

**Comment by maxigaz** [comment]
> I unpacked the patch and started removing some modules to see if it would load.

Could you tell me how you did that? While this is a relatively simple patch that didn't take a lot of time to put together, I imagine it would be a very useful trick in case it happens again with a larger one.

I've noticed that Cardinal creates a directory in `/tmp`, whose content looks as if it was unpacked from a `.vcv` file, but I don't know how to use it.

**Comment by falkTX** [comment]
Fixed in e00515e69bfede42e075df5e5a750490111cc2fc
