### ISSUE TITLE
WIN64 automatic build issues

### ISSUE THREAD

**Issue by vcvrackideas** [DISTRHO/Cardinal#23]
Hi! So I tried VST2 and 3. VST3 got an error while loading - smth like unable to locate template.vcv
VST2 got succesed loading and I even saw GUI with some module and then it crashed Ableton and after that Ableton added it to the "blacklist"

**Comment by vcvrackideas** [comment]
I saw this https://github.com/DISTRHO/Cardinal/commit/86fbd84cf60086f9f648f7941ad42ce2f8bfc052 and tried the commit but it still doesn't fix crash on exit in Win64 Ableton :-( Just FYI

**Comment by falkTX** [comment]
Thanks for the heads up

**Comment by vcvrackideas** [comment]
Congratulations! No more crashes on exit with the last commit. Very happy with that. Perhaps you did some multithreading things you have mentioned before? Seems very stable now

**Comment by falkTX** [comment]
Oh nice, hard work pays off!
