### ISSUE TITLE
Opening and saving files in Ableton live not working in 22.05

### ISSUE THREAD

**Issue by Gsbrt** [DISTRHO/Cardinal#231]
I just updated to Cardinal 22.05 and saving and opening files does not work anymore in Ableton live 11.1.1 on macOS 11.6. Did work in the previous version.

**Comment by falkTX** [comment]
Define "doesnt work", more information please... what doesnt work and what does?

Dialog opens? Which plugin format?
Is it only file -> open, or picking files from modules too?

**Comment by Gsbrt** [comment]
I am not able to save or open files via the files menu. VST.
Adding modules works.

**Comment by falkTX** [comment]
VST2 or VST3? and adding modules is not what I asked, I asked about picking files from modules, they can trigger file dialogs too after all

**Comment by Gsbrt** [comment]
VST2... Let me check picking files from modules...

**Comment by Gsbrt** [comment]
I can access the menu of a module and open info, presets. Also, adding new modules via control+click works.

**Comment by steveparkerdj** [comment]
Same here , with Ableton on Mac with AU 
save or open projects doesn't work but right click do allow me to play with settings but doesn't let me load any samples to any sample players.

**Comment by dromer** [comment]
Are there any spaces or special characters (utf8) in the file-paths? (either the file-names themselves or any of the folders they reside in)>

**Comment by falkTX** [comment]
> Are there any spaces or special characters (utf8) in the file-paths? (either the file-names themselves or any of the folders they reside in).

that is a linux only problem. ableton doesnt run on linux

**Comment by dromer** [comment]
> that is a linux only problem. ableton doesnt run on linux

Hey you never know, more info == better ;)
There was an earlier issue with special characters in windows paths (I think the username?) that gave issues with save/open of files, so figured it wouldn't hurt to think out of the box and ask :)

**Comment by dinegredin** [comment]
Hello everyone

I'v got the same problem here inside logic pro as an AU or inside ableton as a VST.
Impossible to save or open projects and impossible to load sample in all the smapler I've tried :(
Despite this problem i really love this plug in it's really reactive and works much better than VCV on my macbook pro intel.
Thanks for your great work

**Comment by steveparkerdj** [comment]
Yes working here load and save patches also VCV loads samples now 
i only testesd AU i don't use VSTs
thanks

**Comment by falkTX** [comment]
Cool, thanks for confirming.

This sadly didnt make the 22.06 release, but will be part of 22.07 then.

**Comment by dinegredin** [comment]
It works in the vst version aswell  load and save patches, loads samples too !!!!
Youpeeeeeee !!!
Thanks a lot !
