### ISSUE TITLE
Keyboard focus in Logic 

### ISSUE THREAD

**Issue by armandvedel** [DISTRHO/Cardinal#232]
I can't use the keyboard at all when the AU is hosted in Logic (using latest Universal build of Cardinal). The main window retains focus  as if the plugin is not open.

**Comment by falkTX** [comment]
Please try with the latest builds from https://github.com/DISTRHO/Cardinal/actions/workflows/build.yml
I made it so that JUCE does not take the focus, which in theory could make Cardinal be able to take it instead.
Let me know how it works - if it works the same, better, or worse

**Comment by TiiPaa** [comment]
Hey, quite the same problem here on Studio One (Windows 10) with the latest build

**Comment by falkTX** [comment]
I am closing this ticket in favour of a global one for tracking keyboard input behaviour under many hosts and OSes.
See #304
Discussion should now go there.
