### ISSUE TITLE
Resizing GUI does not work in Reaper correctly (22.05)

### ISSUE THREAD

**Issue by MrJC11** [DISTRHO/Cardinal#233]
If I drag using the corner tool, it allows me to make the plugin window bigger, but its just empty white space that appears and the GUI remains the same. Unless, I drag to resize the bottom or sides of the window (but NOT the corner tool). I was able to resize the GUI by double clicking to make it full screen - in this case it does resize correctly. Odd behaviour, there is a chance you already know but I looked through the issues and didn't see anything obvious so I thought I'd report it. :).

EDIT: It turns out I can resize by the corner as long as I make sure that I click on the absolute pixel perfect corner of the window, and not the corner tool. It is also possible to resize the window so that the corner tool disappears entirely, then i have to resize the actual plugin window itself, and it refreshes. Hopefully this makes sense.

**Comment by falkTX** [comment]
The VST3 version is still experimental, the window sizing is not working correctly there yet.
Use VST2 if you want this to work proper, but then there is no host-side resizing.

**Comment by falkTX** [comment]
I am closing this ticket since all VST3 related issues should go into #41
