### ISSUE TITLE
cardinal dont work

### ISSUE THREAD

**Issue by socratesru** [DISTRHO/Cardinal#241]
cardinal just doesn't work for me, I did both types of installation and it doesn't appear in the vst list

**Comment by socratesru** [comment]
![image](https://user-images.githubusercontent.com/36715388/170094426-2ae84b10-df82-4a9a-af94-1d39ce2a1e13.png)
and when i try to open it standalone i get that error

**Comment by falkTX** [comment]
The JACK standalone requires JACK, see jackaudio.org/ for details.

For your first message, I have no idea what system or host you are using, so I cannot help at all

**Comment by falkTX** [comment]
Closing due to lack of feedback
