### ISSUE TITLE
VST3 window resize doesn't work on Windows 64x

### ISSUE THREAD

**Issue by alfonso73** [DISTRHO/Cardinal#242]
Hi, if i try to grab the bottom-right triangle to resize the Cardinal window nothing happens. The triangle isn't draggable.

**Comment by falkTX** [comment]
VST3 support is still experimental. Use ticket #41 for discussion around it.

**Comment by alfonso73** [comment]
> VST3 support is still experimental. Use ticket #41 for discussion around it.

oops sorry. thanks
