### ISSUE TITLE
Feature request: Knob and Slider sensitivity settings

### ISSUE THREAD

**Issue by rafaelferreiraql** [DISTRHO/Cardinal#243]
Being able to adjust mouse (or overall) sensitivity to slider and linear mode knob movement would be pretty neat; in my experience, sliders are currently quite slow to move around.

**Comment by falkTX** [comment]
Sorry I am going to close this one as "wont fix".
Such changes should be made in VCV Rack, and then have them trickle down into Cardinal.

So do a request for such feature in official Rack.
