### ISSUE TITLE
Keyboard input problem

### ISSUE THREAD

**Issue by geduardcatalindev** [DISTRHO/Cardinal#245]
I have installed both the stable and the nightly build into LMMS and Cakewalk and in both cases, when trying for example to search for a module in the module browser or any other keyboard related action, the window seems to not have focus and the input is sent to the DAW directly instead of Cardinal interface.

**Comment by NoiseExplorer** [comment]
I have a similar issue (Cakewalk) - my computer keyboard has no input within my Cardinal session, with no keystrokes being recognised, (e.g. keyboard shortcuts to delete, bypass, duplicate modules etc.), even after selecting option to 'give all keystrokes to plugin. I've also noticed that I'm unable to use the Search box in the Module browser as the field is in fact greyed out. I'm using the Synth variant as a VST3 (vers 22.05) running inside Cakewalk (Windows 10 x64 bit).  Other than that, so far Cardinal seems to be working well for me (albeit as a complete novice at modular) - big shout out to all involved for making this great instrument available and in so doing, encouraging more of us to explore this area of music production :-)

**Comment by PDCD1** [comment]
I've just tried Cardinal in Bitwig 4.3 and am having the same issue. 
No keyboard shortcuts are working. And I can't type into the module browser. 
Mouse control works but it is a bit too cumbersome to just rely on that. 

This is with the 22.06 cardinal release.

**Comment by dromer** [comment]
@PDCD1 on which OS? For me with BW4.3 on Linux (X11) it works fine. Both VST2 and VST3.

**Comment by falkTX** [comment]
I am closing this ticket in favour of a global one for tracking keyboard input behaviour under many hosts and OSes.
See #304
Discussion should now go there.
