### ISSUE TITLE
Feature request: add RJModules

### ISSUE THREAD

**Issue by fotisandstuff** [DISTRHO/Cardinal#247]
https://github.com/Miserlou/RJModules

MIT License. Also, did you receive my e-mail about the livestream where we mentioned Cardinal?

**Comment by dromer** [comment]
It was already on the list -> https://github.com/DISTRHO/Cardinal/wiki/Possible-modules-to-include

No need to open Issues for this stuff, just add it to that wiki page ^

**Comment by fotisandstuff** [comment]
Oops, I had no idea. Sorry. Thanks for the link!!
