### ISSUE TITLE
Resize issues under Windows with Nightly beta builds

### ISSUE THREAD

**Issue by subderground** [DISTRHO/Cardinal#251]
Hi, 
Just for info: In the "Another armhf fix build #1026 Nightly Cardinal-win64-e8613895", there is a important resizing bug (witch is not present in the good "nightly Cardinal-win64-62181c10 release where you introduced the fantastic Host Parameters Map" :-) ). 

Nb: Win 11 vst2 64bit Reaper

**Comment by falkTX** [comment]
resizing bug? you need to be more clear than that.

**Comment by subderground** [comment]
> 

It's difficut to explain but the cardinal window is cropped and not in the center (file, edit... are in the middle of the window and the Cardinal gui is cropped) + impossible to enlarge with the bottom-right handle, so it's unusable. You certainly have modified something... I've deleted this version & to backup the previous one.  If you need more infos, I can redownload this last nightly to take screenshots.

**Comment by dromer** [comment]
Which plugin format is this with? and if you can't explain with words can you show with a screenshot or screencast/video ?

**Comment by falkTX** [comment]
> Which plugin format is this with? 

he already mentioned.

no screencast needed, I will try it out soon in a VM, need to setup a new one.

**Comment by fotisandstuff** [comment]
I have a similar problem with the latest beta on Reaper (win64, vst2, cardinalsynth). A white border appears on the left of the window. When I move the window slider right and then left again, the pixels are repeated.

**Comment by roseweeks** [comment]
This is with the VST3 but I think same issue?  Win11/x64/Reaper v6.60

I can't resize the actual plugin inside the Reaper FX Host.

https://i.imgur.com/U6rppY3.mp4

**Comment by falkTX** [comment]
Issue should be fixed in latest builds, like https://github.com/DISTRHO/Cardinal/actions/runs/2521727889
Should be 1-2h more to have it finished building.

Please try and test when you can, thank you

**Comment by Semiote** [comment]
Tested this in Reaper v6.61 Win11 x64, regression fixed and resizing is working consistently, improvement over 22.05.

**Comment by fotisandstuff** [comment]
Tested this in Reaper v6.61 Win10 x64, regression is also fixed for me, both in VST2 and 3!

**Comment by falkTX** [comment]
cool, thanks for verifying. we can close this one then
