### ISSUE TITLE
Problem with host reset on nightly

### ISSUE THREAD

**Issue by fotisandstuff** [DISTRHO/Cardinal#253]
In win64 nightly [62181c10](https://github.com/DISTRHO/Cardinal/suites/6785323408/artifacts/260191951) , I have a problem with drum beats like the ones in the patch "falkTX_-_Salomonis-MonoRegen.vcv". The snare goes out of sync many times, and the Aria Salvatrice sequencers are also affected. I temporarily solved the problem by routing the snare and the sequencers' "Reset" inputs to Host Time's "Playing" output instead of its "Reset" output. I use VST2 CardinalSynth on Reaper v6.59 (Windows 10 x64).

**Comment by dromer** [comment]
Yup, I'm also seeing an issue with the reset output of Host Time. This is also with the 22.05 release for me, not just local or nightly builds.

In Carla it's only an issue with the VST2, and it seems there the Reset output triggers every bar.
In Bitwig however this is an issue with both VST2 and VST3 and and there the Reset output seems to be triggering a lot, and at random.

**Comment by fotisandstuff** [comment]
I tried the latest nightly in Reaper. The VST3's seem to work correctly, but the problem persists in the VST2's.

**Comment by dromer** [comment]
I somehow feel this is when it broke: https://github.com/DISTRHO/Cardinal/commit/c46d659340525f963c95a58747d06deabac9bd9b
However I see there is a new commit from last night, will test it when I get home.

**Comment by fotisandstuff** [comment]
The issue still exists in the latest nightly.

**Comment by dromer** [comment]
I tried to revert the commit I mentioned, but this gives the exact same result for me. Both VST2 and VST3 just have a super random reset output in bitwig.

**Comment by dromer** [comment]
Should be fixed by https://github.com/DISTRHO/Cardinal/commit/ec2222be8514140d8a935022d8e1bb00e17df340 

Works for me with vst2 and vst3 in both bitwig and reaper!

**Comment by fotisandstuff** [comment]
Yessss! It's fixed!!!
