### ISSUE TITLE
VST3 Rendering Issues Bespoke/Reaper

### ISSUE THREAD

**Issue by Semiote** [DISTRHO/Cardinal#254]
issue: display
os:  Win11x64
commit id: 62181c104704f457eb8cad83673a83f3986de82e 
reaper: v6.60
bespoke: 1.1.0 Nightly May 3 2022 (latest win release on download page)

Resizing and changing scaling settings appears to make no difference.

Screenshots: https://imgur.com/a/MoHe0Qj

Issue not seen with 22.05

**Comment by dromer** [comment]
All VST3 related issues should go into https://github.com/DISTRHO/Cardinal/issues/41

**Comment by Semiote** [comment]
Want me to delete and repost this over to the other issue?

**Comment by dromer** [comment]
Yes please, then we can keep all VST3 related issues in one place for now.

**Comment by falkTX** [comment]
yeah, vst3 stuff goes there. it is still experimental, so no point opening a bunch of tickets around it.
