### ISSUE TITLE
mac universal requires Rosetta

### ISSUE THREAD

**Issue by rshklarek** [DISTRHO/Cardinal#257]
Hi,

first of all thank you so much for this awesome plug-in.

The dedicated universal installer for mac still requires Rosetta. I don't want to install it, if possible.

Thanks for your help and best regards.
R

**Comment by falkTX** [comment]
This should be fixed in https://github.com/DISTRHO/Cardinal/actions/runs/2518108182 after it finishes building.
So in a couple of hours, try it out when available please

**Comment by rshklarek** [comment]
Hi, thanks for the response. The installation worked fine now but the plug-in doesn't render well. The window is shifted in all plug-in formats I tried within Ableton: AU, VST2 and VST3.
<img width="1512" alt="Screenshot 2022-06-18 at 13 48 46" src="https://user-images.githubusercontent.com/33123708/174436172-9588db96-f0ea-43b9-a88b-75912b1133f4.png">

**Comment by falkTX** [comment]
ok great, I will close this ticket since the installer specific issue is fixed now.

will check the display issue next
