### ISSUE TITLE
error: expected unqualified-id before ‘__int128’ { typedef unsigned __int128 type; };

### ISSUE THREAD

**Issue by TheGuyWhoo** [DISTRHO/Cardinal#26]
Trying to build on 32 bit linux mint 19 machine, this is the error I get. Any way around it? 

make all -C deps
make -C dpf/dgl opengl USE_NANOVG_FBO=true
make[1]: Entering directory '/home/nickelas/Cardinal/dpf/dgl'
make[1]: Entering directory '/home/nickelas/Cardinal/deps'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/nickelas/Cardinal/deps'
make all -C plugins
make[1]: Entering directory '/home/nickelas/Cardinal/plugins'
make[1]: Nothing to be done for 'opengl'.
make[1]: Leaving directory '/home/nickelas/Cardinal/dpf/dgl'
Compiling plugins.cpp
Compiling AmalgamatedHarmonics/src/MuxDeMux.cpp
In file included from /usr/include/c++/7/random:49:0,
                 from ../src/Rack/include/random.hpp:3,
                 from ../src/Rack/include/rack.hpp:13,
                 from AmalgamatedHarmonics/src/AH.hpp:5,
                 from plugins.cpp:23:
/usr/include/c++/7/bits/random.h:107:26: error: expected unqualified-id before ‘__int128’
       { typedef unsigned __int128 type; };
                          ^~~~~~~~
Compiling AmalgamatedHarmonics/src/Bombe.cpp
Makefile:402: recipe for target '../build/plugins/plugins.cpp.o' failed
make[1]: *** [../build/plugins/plugins.cpp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/nickelas/Cardinal/plugins'
Makefile:76: recipe for target 'plugins' failed
make: *** [plugins] Error 2

**Comment by falkTX** [comment]
I am closing this one as "wont fix", since I have no idea how to go about fixing this at all, and seems like a compiler issue anyway
