### ISSUE TITLE
Win64 standalone mode error

### ISSUE THREAD

**Issue by tomexx** [DISTRHO/Cardinal#266]
Hi all,

when I try to run fully installed standalone version of Cardinal, I get this error:
![image](https://user-images.githubusercontent.com/2822756/175170327-62965f4e-1b76-4e88-80ca-6d59e30f38bd.png)

VST version runs correctly inside DAW.

Any idea what is the problem?

Thanks

**Comment by falkTX** [comment]
There is no problem, the standalone relies on jack. Same as per #241
see jackaudio.org/ for details
