### ISSUE TITLE
Cardinal does not load in Ableton Live and standalone brings up error

### ISSUE THREAD

**Issue by TheGoldfish11** [DISTRHO/Cardinal#268]
I feel like I'm doing something critically wrong, when trying to load up the plugin, nothing happens in Ableton and when I try to open the standalone, an error "Failed to create JACK client, reason was: Communication error with JACK server."

I downloaded the Windows 64 bit exe installer and it did install the files to what I assume is the correct locations, but I'm completely lost on what to do to fix the error.

Please don't bash me too hard for making a dumb mistake, I'm very new to this kind of thing.

**Comment by falkTX** [comment]
Jack standalone requires jack. See https://jackaudio.org/

For the plugin version, the VST3 is still experimental and does not work in Ableton (known issue, though causes are unknown)
Use the VST2 version, that format works as far as I know

**Comment by TheGoldfish11** [comment]
I have downloaded jack and have installed it, same issue appears.

I also can't seem to find the VST2 version of Cardinal in Ableton despite install it, what should I try regarding that?

**Comment by falkTX** [comment]
> I have downloaded jack and have installed it, same issue appears.

jack needs to be setup and started



> I also can't seem to find the VST2 version of Cardinal in Ableton despite install it, what should I try regarding that?

Maybe it is automatically hiding the VST2 version..
You can try to uninstall Cardinal, and reinstall without the VST3

**Comment by TheGoldfish11** [comment]
I tried installing without the VST3 but now I can't see an instance of Cardinal anywhere on Ableton.

**Comment by TheGoldfish11** [comment]
I at least got the standalone to work :)

**Comment by TheGoldfish11** [comment]
I finally got it to work, I needed to manually put the VST2 folder into the VST folder that Ableton accesses, sorry for bothering you. Glad it's finally functioning.
