### ISSUE TITLE
vcv Wavetable Osc & Lfo

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#269]
Vcv module Wavetable Osc and wavetable Lfo doesn't load samples ... I'm on Mac Catalina , daw Ableton live 11. (Audiounit)
Thanks keep the good work.

**Comment by falkTX** [comment]
Same issue as #231 then, closing as duplicate.

I tried to reproduce, but cant. So I am unable to fix this for now.
