### ISSUE TITLE
Immediate crashes with demo patches in 22.06 (Mac)

### ISSUE THREAD

**Issue by NeonBC** [DISTRHO/Cardinal#272]
Hej

Ableton Live 11 crashes immediately to desktop, without any warnings or dialog when the patches:
**DRMR - Etherpad** and **DRMR - Interverb** are selected, all others work fine as expected

Only clue the msg in Terminal when it crashes "segmentation fault /Applications/Ableton\ Live\ 11\ Suite.app/Contents/MacOS/Live"

Platforms:
MacOS 12.4 (Intel i7 / 32GB Ram)
Ableton Live 11.1.6 Suite
Cardinal 22.6 VST2 (Mac Universal build)

thx and happy coding! :)

**Comment by rickympls** [comment]
Those 2 patches crash for me as well.
Logic 10.5.1 on Mojave 10.14.6  (Intel)

```
Crashed Thread:        36  com.apple.audio.IOThread.client

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [65200]
```

**Comment by dromer** [comment]
Can you please try again with latest nightly release?
There have been some fixes for uninitialized values (for instance in the Valley modules, which all of these patches use), which could be the reason you see this behavior.

There have also been many fixes on memory leaks, so substantial improvements for this kind of stuff.

**Comment by rickympls** [comment]
Hi, I installed build 1200 but those two patches still crash for me.

**Comment by dromer** [comment]
Universal or Intel build?

**Comment by rickympls** [comment]
> Universal or Intel build?

Intel build.

**Comment by falkTX** [comment]
this should be fixed in 22.11, please confirm

**Comment by rickympls** [comment]
Fixed!  :-)

**Comment by falkTX** [comment]
cool thanks for verifying
