### ISSUE TITLE
22.06 crashes reaper sometimes when removing the vst2

### ISSUE THREAD

**Issue by offthesky** [DISTRHO/Cardinal#273]
first noticed this on the 32bit win 10 pc, then moved the project over to the 64bit win 10 laptop and the same crashes were occurring (upon trying to remove the plugins individually).   not all instances of 22.06 cardinal in my project were doing this, just the instances contained in the reaper project in the .zip below (i removed everything else that would remove ok without crashes).  one instance of the vst2i in the .zip below is completely blank (all modules removed) yet it still crashes on remove.  i think both of these use, or used at some point, the new host param map module.
 
[cardinal crashes reaper when trying to remove the plugins.zip](https://github.com/DISTRHO/Cardinal/files/9021467/cardinal.crashes.reaper.when.trying.to.remove.the.plugins.zip)

**Comment by rafaelferreiraql** [comment]
I'm on Win 8.1 64bit and have been running into similar issues. I have a saved project using two instances of Cardinal, one crashes on removal and the other crashes upon saving after removal.

**Comment by iamsummoner** [comment]
Same issue on Win10 x64, Reaper 6.66, VST2i 22.06.
Happens only when multiple instances of Cardinal exists in a project.
Removing everything from Cardinal, disabling it before delete, disconnecting in-out channel mappings had no effect.
Removing everything still allows to save without troubles, so not a module issue, probably.

Workaround for now is:
* Open project in safe mode (bottom left checkbox in the project selection dialog on Reaper startup);
* Remove desired FX/Track;
* Close Reaper;
* Open project normally again.

Hope this helps for anyone searching for a quick fix for now.

**Comment by falkTX** [comment]
can you try with the latest build, those being https://github.com/DISTRHO/Cardinal/actions/runs/2899688692 today

22.06 is an old version already

**Comment by offthesky** [comment]
tried with build 1166 in latest reaper(v6.66) and problem still occurs 32b/64b win10 w the vst2

**Comment by offthesky** [comment]
> Same issue on Win10 x64, Reaper 6.66, VST2i 22.06. Happens only when multiple instances of Cardinal exists in a project. Removing everything from Cardinal, disabling it before delete, disconnecting in-out channel mappings had no effect. Removing everything still allows to save without troubles, so not a module issue, probably.
> 
> Workaround for now is:
> 
> * Open project in safe mode (bottom left checkbox in the project selection dialog on Reaper startup);
> * Remove desired FX/Track;
> * Close Reaper;
> * Open project normally again.
> 
> Hope this helps for anyone searching for a quick fix for now.

thanks for mention the workaround! didnt know recovery mode existed. very useful.

**Comment by falkTX** [comment]
I was able to reproduce the crash, it is a regression from a change in DPF a couple months ago.
Should be fixed with 0aa7c9ab289e6b77a95195e2a4984564450777e7 please confirm once builds are available. Thanks!

**Comment by offthesky** [comment]
tested in reaper 32bits vst2. seems to be working okay now afaict!

**Comment by falkTX** [comment]
Great, thanks for checking!
