### ISSUE TITLE
Cardinal for Windows won't run on Linux/Wine

### ISSUE THREAD

**Issue by lucmp** [DISTRHO/Cardinal#275]
I tried Cardinal for the first time today and... well, I didn't. It didn't run at all. I tried it on Mulab 9 running on Linux and Wine.

I also tried it with carla-single, and it crashes instantly. I dragged it into Carla and it loads, I can even play something in Carla's piano roll and hear sound, but the plugin crashes when I click the cogwheel icon to view its GUI.

At first, I tried the 32-bit version because I prefer 32-bit. I know you've had problems with Win 32-bit so I tried the 64-bit version. The 64-bit version won't even load in Carla or carla-single.

I know what you're thinking. "There is a native Linux version."

I downloaded that too, tried it on Waveform 11, and it failed the scanning process test so Waveform won't load it at all.

There is no way for me to run Cardinal.

Apart from the problem with the Linux version, I am very disappointed to see that Cardinal for Windows won't run on Wine. I am using Linux Waveform for now, but intend to use more Mulab than Waveform in the future. I think Mulab is a better DAW than Waveform and the fact that it's made for Windows only makes it more attractive for me. Plugins can run "natively" rather than on linvst therefore they're more stable, and Windows applications never expire. Linux applications expire. I am guessing that Linux Cardinal won't run for me because I am using Debian Stretch. Must be some library miismatch. There is none of that problem with Windows apps so I absolutely prefer them.

BTW, the Windows version of Carla won't load in Wine either.

It's reported, for whatever it's worth. Thank you for your attention.

**Comment by falkTX** [comment]
Rack uses some windows things which are not supported on Wine, through the use of libarchive zipping folder contents.
I have added a workaround to allow to run it, but any saved projects ended up as zero bytes.

Since this is not a Cardinal specific issue, it runs on real Windows after all, it is basically a "wont fix".
Considering building Cardinal yourself if the published binaries do not work for you, it takes some time but there is nothing special about Cardinal that makes it difficult to build.

**Comment by lucmp** [comment]
"Rack uses some windows things which are not supported on Wine"

This just makes me sad.

Meanwhile, some 98% of all other Windows plugins I ever tried (and I've tried hundreds) ran just fine and will probably run forever, even on Linux, whether I upgrade my distro or not. So much for the joys of open source.

**Comment by falkTX** [comment]
The joys of opensource is that now you have the chance of fixing things, instead of relying on others having to do it for you.
The starting point is https://github.com/DISTRHO/Cardinal/blob/main/src/override/common.cpp#L41

Good luck!
