### ISSUE TITLE
Please add PdArray modules.

### ISSUE THREAD

**Issue by TheGuyWhoo** [DISTRHO/Cardinal#279]
https://github.com/mgunyho/PdArray

Please add these if you get a chance, EUPL 1.2 license. Very cool module for drawing modulation.

**Comment by TheGuyWhoo** [comment]
Oh okay, this gave me the impression you didn't mind.

https://github.com/DISTRHO/Cardinal/issues/238

**Comment by TheGuyWhoo** [comment]
Alrighty. Well since we're here I'll bother you about Mojo modules too. I know they are very easy to add because I've done it before, and it has a really nice bass module I'm dying to use. Cheers ;)

**Comment by falkTX** [comment]
Sounds like a pull request is coming soon :)

**Comment by TheGuyWhoo** [comment]
Last time I tried that it was an absolute mess lmao. I'm monkey see monkey do, I don't know shit about code or git for that matter.

**Comment by TheGuyWhoo** [comment]
I will take a look, maybe tomorrow.
