### ISSUE TITLE
Failed to create JACK client

### ISSUE THREAD

**Issue by WilliamBgaming** [DISTRHO/Cardinal#280]
Edit: just me being stupid

Error message:
Failed to create JACK client, reason was:
Communication error with the JACK server.

I don't know how to fix this, I downloaded 22.06 and can't get past this error popup.

**Comment by falkTX** [comment]
You have jack installed and running?

**Comment by WilliamBgaming** [comment]
I see, where can i downolad JACK?

**Comment by falkTX** [comment]
https://jackaudio.org/ has all the details. the jack standalone uses that for audio and midi.
I assume that to be the problem here, since you are asking about it. Closing as invalid.
