### ISSUE TITLE
Getting an error about imgui_impl_opengl3_loader.h not being included.

### ISSUE THREAD

**Issue by TheGuyWhoo** [DISTRHO/Cardinal#286]
I can't remember the exact error, it just said there was no imgui_impl_opengl3_loader.h file because there wasn't, but I solved it by copying [this](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_opengl3_loader.h) and putting it in plugins/Cardinal/src/DearImgGui/imgui_impl_opengl3_loader.h

**Comment by falkTX** [comment]
Likely while wasm stuff was in the works and build not always succeeded properly.
I added a check in 9d71e370862ed2f822f573f7ecb997db69c7f0f4 to ensure this error won't appear anyhow.
