### ISSUE TITLE
terrorform

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#288]
Terrorform Crashes Ableton live Mac Catalina Au 
Thanks

**Comment by falkTX** [comment]
mac intel or m1/arm ?

**Comment by steveparkerdj** [comment]
Just and update
I've tried with VST3 but also crashes 
Thanks

**Comment by falkTX** [comment]
well yeah, I didnt fix this part, nothing in the changelog mentions it.
issue still there, I gave attention to vst3 and keyboard input issues instead.

if you have some time and coding skills, you can try to fix it yourself in the mean time.

**Comment by catalinux777** [comment]
I have the same issue.

**Comment by steveparkerdj** [comment]
Now it's fully working not a single crash
Vst3 and AU ...THANKS ! 🙏

**Comment by falkTX** [comment]
ah great, thanks for checking in and testing!
