### ISSUE TITLE
E340 cloud generator, no audio when density is set to 8.

### ISSUE THREAD

**Issue by TheGuyWhoo** [DISTRHO/Cardinal#289]
Linux mint 20 64 bit, reaper 6.44, affects all variants. When Cloud generator density is set to 8 there is no audio, and Cardinal needs to be reloaded in order for it to produce audio again. It works fine on density of 4 and 2.

**Comment by dromer** [comment]
It works fine for me in Reaper 6.61 (vst2 and lv2) maybe try updating?

**Comment by TheGuyWhoo** [comment]
If that was the problem it would not also be present in standalone, no?

**Comment by dromer** [comment]
Oh you didn't say it was also an issue in the standalone (you explicitly said Reaper).
Which OS is this? What sample size? (I'm on 256/48k myself) Thinking out loud here.

**Comment by TheGuyWhoo** [comment]
>Linux mint 20 64 bit, reaper 6.44, affects all variants.

Just tested it at the same sample size as you, still the same problem. I did discover something though. When I play it with my keyboard I'm not having any issues, however when I put midi on the track(using a midi item) that's when it completely locks up as described above.

(The same thing does not happen in standalone. It doesn't work with sequencers nor with midi sent from reaper)

Here's the patch:

[cloud generator.zip](https://github.com/DISTRHO/Cardinal/files/9072299/cloud.generator.zip)

**Comment by dromer** [comment]
Works for me in Reaper 6.61 for all plugin variants (LV2, VST2/3)

**Comment by dromer** [comment]
@TheGuyWhoo assuming this is fixed. Please report if otherwise.
