### ISSUE TITLE
SV BD-9

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#291]
Not that I use it much but SV RD9 is crashing Ableton, not everytime but happens 2 times out of 4. 

Ableton live Mac Catalina AU (Intel)
thanks

**Comment by dromer** [comment]
Do you mean `Bass Drum 9` by `SV Modular` ?

**Comment by steveparkerdj** [comment]
Yes that one.

**Comment by steveparkerdj** [comment]
I don't use other plugin formats so I can't tell. It normally crashes when I try to input any jack cable

**Comment by falkTX** [comment]
should be fixed in 22.11, please confirm

**Comment by dromer** [comment]
@steveparkerdj can you please confirm the fix so we can close the issue?
