### ISSUE TITLE
Intezone

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#292]
Interzone from Valey is crashing ableton Live 11 MAC catalina AU intel
only by selecting it , crashes immediately 
thanks

**Comment by dromer** [comment]
There have been various issue reported with the Intel AU. Can you try the latest 22.07? compare with Universal package.

Also, do VST2 and VST3 load fine for you?

**Comment by steveparkerdj** [comment]
yes, i already done with the new 22/07 and vet 2 3 and AU  and crash continues.

**Comment by dromer** [comment]
Intel or Universal package?

**Comment by steveparkerdj** [comment]
my mac is intel but I've tried both intel and universal package

**Comment by dromer** [comment]
Ok thnx. The Intel only build has some more issues at the moment, so thnx for checking.

**Comment by falkTX** [comment]
should be fixed in 22.11, please confirm

**Comment by falkTX** [comment]
assuming fixed, closing.
