### ISSUE TITLE
FL Studio MIDI compatibility possibly broken

### ISSUE THREAD

**Issue by Pojoquiet** [DISTRHO/Cardinal#294]
I haven't seen anyone discussing this so it's likely I'm the one at fault here but I can't seem to make the midi out from cardinal work with fl studio. I've tried routing the midi channels manually to different vst synths and samplers but nothing seems to work.

Trying the midi input into cardinal also didn't work (although I am using my PC keyboard as the midi controller as I don't have an actual controller at hand right now). So, in FL Studio, Cardinal doesn't accept midi in or out is the conclusion I arrived at.

If anyone could help me figure out if I'm doing anything wrong or if it's an issue that needs to be submitted to the dev team I'd appreciate it.

Thank you

**Comment by falkTX** [comment]
Cardinal Synth is working fine under FLStudio here.
Using FLStudio 20.9.2 and Cardinal 22.06 (both VST2 and VST3 work)

https://www.youtube.com/watch?v=QWYyseJKKsY has some details on how to use MIDI plugins in FLStudio.

Seems pretty easy, tested here by sending MIDI from Cardinal Synth VST3 into Cardinal Synth VST2.
The VST3 version has MIDI output port set to 2:

![image](https://user-images.githubusercontent.com/1334853/178747264-63a69d8c-eb05-454e-b2a2-492947a5c3d2.png)

Then the Cardinal Synth VST2 receives those notes on the same port 2:

![image](https://user-images.githubusercontent.com/1334853/178747427-1172ef3b-4761-49aa-9ae9-517966b7ffd7.png)

So all is working as far as I can see and test and verify.
Please confirm.

**Comment by Pojoquiet** [comment]
It worked! I can't seem to get the VST3 version to work (no midi in or out) but the VST2 works perfectly so at least to play around it's more than enough. Thank you!

**Comment by falkTX** [comment]
You are using 22.06? older versions didnt have this working

**Comment by Pojoquiet** [comment]
Yes it's 22.06 on 20.7.2 FL however.
I'm happy to only use the VST2 version but I really can't understand why the the VST3 isn't working. Even trying with different vsts and patcher only the VST2 version is recieving and sending midi info.

**Comment by falkTX** [comment]
Could be a bug on FLStudio, something only happening with VST3.
Recommend to update.

Considering this works on other hosts without issues (even shown on video), I am closing this ticket.
