### ISSUE TITLE
Suggestion: A module creator tool, Description on comments

### ISSUE THREAD

**Issue by arRk-byte** [DISTRHO/Cardinal#300]
Making the rack interface must be simple like in the Voltage Modular Module Creator, for UI/UX simplicity.

It has a Code Editor to add features to the interface of the module,

and a Node Editor, so people that don't know how to code can make their own modules,

Yeah, I won't explain everything I want in the creator, basically make it new-friendly while can make a lot of modules

**Comment by falkTX** [comment]
I think you need to find a different tool then.

**Comment by dromer** [comment]
I think this is completely out of scope for this project.

Maybe suggest it for the general VCV community and resulting modules may feed back into this project (if compatible).
