### ISSUE TITLE
22.06 MacOS 10.14.6 - VST & AU does not open dialog for File->Open or File->Save or any

### ISSUE THREAD

**Issue by mrniceguy1234** [DISTRHO/Cardinal#301]
It does not open any dialog when it seems like it should. Tested with Renoise and Reaper. Does not validate for Logic.

**Comment by falkTX** [comment]
Known issue, use the macos-universal build to get file dialogs.
Already fixed in latest builds, fix will be in 22.07

**Comment by mrniceguy1234** [comment]
I can confirm the latest build fixes this for vst, but the AU version still has the problem
