### ISSUE TITLE
Cardinal VST3 not loading on Cubase

### ISSUE THREAD

**Issue by DomeAlessi** [DISTRHO/Cardinal#302]
Hello!

I am running Cubase 12 on Windows and I would like to use the VST3 version of Cardinal but for some reason the plugins (both the synth and the FX) are not loading as Inserts. Even if the plugins appear to be loaded in the plugin manager when i actually try click them to use them they will not show in the inserts list.

Anyone else experiencing this problem?
Thank you!

**Comment by jasonfernandezmusic** [comment]
VST3 not working here either - macOS 12.4 with Cubase 12 (rosetta)

**Comment by falkTX** [comment]
Fixed in d5d593a3e7db5facab90f7be5ff3b26b50f652be
Will be part of next nightly/action builds and 22.07 release
