### ISSUE TITLE
Host params map stuck to param 1 

### ISSUE THREAD

**Issue by dinegredin** [DISTRHO/Cardinal#309]
Hello I'm trying to map some parameters but it seems that only the parameter 1 can be mapped.
I didn't find the way to map other parameter.
Is it an issue or am I doing it the wrong way?
I've tried to move the parameter knob inside my host before clicking "unmapped" but only the first parameter is proposed.
I'm running the AU version of cardinal inside logic pro x  on mac os intel 10.13.6

**Comment by falkTX** [comment]
you should be able to click the mapping to open a little menu below it, and then move the param slider that appears right besides the smooth and invert options.

**Comment by falkTX** [comment]
no worries, I am closing the issue as invalid then.

**Comment by abulka** [comment]
> you should be able to click the mapping to open a little menu below it, and then move the param slider that appears right besides the smooth and invert options.

@falkTX I think it would be a good idea to put this vital piece of information in the [doco](https://github.com/DISTRHO/Cardinal/blob/main/docs/CARDINAL-MODULES.md#host-parameters-map) as I too was stuck for a very long time trying to figure out how to map something other than parameter 1.  

IMO it is not discoverable that the grey backround highlight is actually a slider - it just looks like a grey heading.
![image](https://user-images.githubusercontent.com/11467530/206679255-9ab522f9-8744-48b0-87d3-d79e9b20e4d7.png)
at least on my Mac. I wonder if a little slider handle could be added or something?

I think its also worth considering whether parameter 1 should always mapped, then later the user has to explicitly change it. Perhaps it could auto increment?

Finally, I feel that it is unintuitive that right clicking should delete a mapping - if I'm desperately hunting around trying to get a menu to change things, I would naturally be right clicking to get to a menu - only to have things be deleted.
