### ISSUE TITLE
22.06 Save function not working in AU - does not open file selector window

### ISSUE THREAD

**Issue by zmixnyc** [DISTRHO/Cardinal#311]
22.06 Save function not working in AU - does not open file selector window.

I can save and load presets using the Logic file system, but selecting "Save" within Cardinal's GUI does not open a file selector dialog window as expected.

**Comment by falkTX** [comment]
known issue, has been reported multiple times, only present in macos-intel but not in macos-universal builds.
already fixed in nightly/action builds and will be part of 22.07 later today
