### ISSUE TITLE
AU format is out of tune

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#315]
all sound source modules are out of tune, when i use a a C4 note from my keyboard all modules give me a B3,
meaning its one Seminole bellow .
mac catalina AU intel ableton

**Comment by falkTX** [comment]
try other plugin versions, see if it has same results

**Comment by steveparkerdj** [comment]
I just tested with VST3 and it's Tuned but not on AU

**Comment by falkTX** [comment]
This is hopefully fixed by f76d93112738771f597c684a06347676cb8f90ee

Please give the build https://github.com/DISTRHO/Cardinal/actions/runs/3078628693 a try once it finishes, thanks!

**Comment by falkTX** [comment]
Nevermind that, I found the issue, really fixed in 43306dd2bc2f54766522deb43c870c2133595fcc
Builds starting with https://github.com/DISTRHO/Cardinal/actions/runs/3079078208 will have the fix.

**Comment by dromer** [comment]
@steveparkerdj please confirm the above fix so we can close the issue ^

**Comment by dromer** [comment]
Lack of feedback. Assuming fixed.
