### ISSUE TITLE
HOST Midi

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#316]
When I insert a host midi I can pick channel midi 1 and works normal but if I had a new host midi to use for example with my beatstep pro on channel 2 there's no way I can make this work out. 
Only way I managed to get this working is inserting another Cardinal on my daw and have one for beatstep pro ch1 and the other on ch2.

But shouldnt I be able to have both channels working inside the same plugin?
I can do that with for example Softube Modular. 

Thanks

**Comment by dromer** [comment]
Please mention plugin formats, OS and DAW/host versions as basic info so people can try to reproduce your problem.

I've successfully used different channel both input and output in the past with various versions (not all hosts).

Is the track in your DAW set to "all" midi channel?

**Comment by steveparkerdj** [comment]
DAW Ableton live Mac Catalina intel 
Yes I've tried all possible ways in the midi menu 

I can easily make it work but with 2 diferent cardinals instances. (1 per channel on DAW)

**Comment by dromer** [comment]
Which plugin formats? (vst/vst3/au)
Also try the Universal package, which is a bit bigger but includes intel compat build.

**Comment by steveparkerdj** [comment]
I've tried with Au vat3 vst2

**Comment by steveparkerdj** [comment]
When I use 2 host midis the second overlaps the triggers, plus I don't get any voltage for pitch 

From my experience with other apps , all we have to do in Ableton is creat another midi channel in the mixer , creat another host midi module, set the channel number and it's done. 

I've tried changing settings in the Cardinal menu nothing fixes it. 

Thanks

**Comment by steveparkerdj** [comment]
It worked with universal package... In this version something appears on Ableton channel for the other midi channels, something that didn't appear in intel version. 

Thanks.

**Comment by falkTX** [comment]
err dont just close it, what exactly is different?
to be quite honest, I didnt expect anything to be different there.

macos-intel builds target 10.8 while macos-universal 10.12, but seems weird this would influence such internal things in cardinal

**Comment by steveparkerdj** [comment]
In this version I was able to setup properly 
And easily. On the other was just not working. I can post a pic of what now shows up on my Ableton in the channel mix section about Cardinal if you want.
