### ISSUE TITLE
Request: Add remaining Lilac modules

### ISSUE THREAD

**Issue by RedstoneParadox** [DISTRHO/Cardinal#323]
Currently, the Lilac Accumulator and Comparator modules are not in Cardinal, just the Looper.

**Comment by dromer** [comment]
Please don't open issues for adding modules. We have this discussion thread: https://github.com/DISTRHO/Cardinal/discussions/63
And this wiki page: https://github.com/DISTRHO/Cardinal/wiki/Possible-modules-to-include
