### ISSUE TITLE
Liquid Filter brings my PC to its knees and it begs for help, I pat it and say "there there" but it doesn't improve things... lol.

### ISSUE THREAD

**Issue by MrJC11** [DISTRHO/Cardinal#324]
Hello,

I have been away from Cardinal for awhile but I have come back and tried to load EtherPad from the demo / example projects as a test and Liquid Filter seems to quickly bring my PC to its knees and the performance meter is through the roof for that particular module. I have tried both VST2/3 versions (bizzarely I have no main variant of the plugin in VST2 for some odd reason). It then forces resets. 

Anyone else having this problem / know how to solve it? 

Thanks.

EDIT: By the way, this is with me using Reaper.

**Comment by MrJC11** [comment]
![image](https://user-images.githubusercontent.com/67632441/180108115-01d6e237-a15a-4777-95b2-11674952fe47.png)

**Comment by falkTX** [comment]
does it always happen with it by itself or other modules, or is it specific to that patch?

**Comment by MrJC11** [comment]
I have just been testing further with a simpler patch of my own and it seems to be working fine. Why is that patch so heavy though?

**Comment by MrJC11** [comment]
Ah! Nice one. That would make sense. No worries. :D.

**Comment by MrJC11** [comment]
Oh btw, when I wire aftertouch to the frequency CV in it also hammers the performance.

**Comment by dromer** [comment]
Thnx for testing and reporting!

> bizzarely I have no main variant of the plugin in VST2 for some odd reason

Btw, this is because VST2 does not support CV ports (only LV2 and VST3 have a Main variant)

**Comment by MrJC11** [comment]
Ah I see. No problem. I will keep testing things. I don't know if it is somewhat related to the same issue but... yes. CVs are hammering it.

![image](https://user-images.githubusercontent.com/67632441/180110701-20a209d7-71c6-4d03-a06a-cf8dc390be60.png)

**Comment by ThePython10110** [comment]
It does seem to be the CVs, especially the Gain input. On my computer, connecting anything to the Gain input increases the CPU usage by about 10x, Resonance is 2x, and frequency and FM barely change it. The easiest way to "fix" the example patch is to use the envelope to control a VCA before the filter, instead of connecting it to the Gain input.

**Comment by dromer** [comment]
Have you tested this on main VCV Rack? If this is an issue upstream it should of course be fixed there.

**Comment by ThePython10110** [comment]
> Have you tested this on main VCV Rack? If this is an issue upstream it should of course be fixed there.

This does not happen in VCV Rack 2.1.2 (Windows 10).

**Comment by dromer** [comment]
So can you please give a simple example patch that we can use for testing?
I don't see any spikes on liquid filter on linux.

**Comment by ThePython10110** [comment]
> So can you please give a simple example patch that we can use for testing? I don't see any spikes on liquid filter on linux.

GitHub can't upload .vcv files, so I just changed the file extension to .txt. Change it back to .vcv before opening it.
It may be specific to Windows. I don't know.

[Liquid Filter Test.txt](https://github.com/DISTRHO/Cardinal/files/9312171/Liquid.Filter.Test.txt)

**Comment by dromer** [comment]
You can use the export file function, it is just a decompressed json.

I'll try this out.

**Comment by dromer** [comment]
Works fine:

![](https://i.imgur.com/HZsR7yQ.png)

**Comment by ThePython10110** [comment]
> Works fine
Maybe it _is_ a Windows-only bug.

**Comment by falkTX** [comment]
Could be due to missing flush-denormals-to-zero CPU flags.

I dislike setting those on the plugin side, it messes up with global state which is never a good thing in plugins.
But we can enable it on standalone, and use it as a test..
Will do a build with this soon

**Comment by falkTX** [comment]
latest release (and even before) now disables denormals when processing plugins. closing ticket as we confirm that was the issue
