### ISSUE TITLE
polyphony 

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#328]
somehow i can't comment on previous post , so the problem is  in the aaron static modules 
when i use the modules i can only get 4 voices polyphony 
cheers

**Comment by steveparkerdj** [comment]
https://user-images.githubusercontent.com/105745595/180605931-d9b42bc7-fb53-44df-a10d-8b12d42bfc49.mp4

example here

**Comment by falkTX** [comment]
please dont open another ticket about. it was converted into a discussion.
find it at https://github.com/DISTRHO/Cardinal/discussions/327
