### ISSUE TITLE
New Cardinal HOST connection module is nice but...

### ISSUE THREAD

**Issue by vcvrackideas** [DISTRHO/Cardinal#33]
but can you please make clock a way faster than it is acting now? 24 ppqn is the best but probably x4 would work fine. Impromptu clocked takes a lot of time to achieve proper bpm with a whole clock.

**Comment by falkTX** [comment]
It is still WIP as clearly seen by the unfinished GUI.
I will see what I can add regarding faster multipliers.

**Comment by falkTX** [comment]
Ok this is done now.

![image](https://user-images.githubusercontent.com/1334853/139507981-c7db9af4-0623-4e55-91bc-7d768665388b.png)

Let me know if it works good for you

**Comment by vcvrackideas** [comment]
Thank you so much! Connecting clock to CLKD bpm input in P4 mode works perfectly especially when Playing is also connecting to the RUN input. Getting pretty weird Resets random signals in Ableton still but I don't really care about this because Clock and Play inputs are more then enough imo.

Offtopic: I assume you have removed save ability of patches because it can interrupt something in most systems right? And import and save sections also don't react 
and the only one issue I have in windows ableton so far is a crash when quit a DAW. But I'm so happy with tight clock sync, tested with metronom and befaco kickall) Thank you again.

**Comment by falkTX** [comment]
> Getting pretty weird Resets random signals in Ableton still but I don't really care about this because Clock and Play inputs are more then enough imo.

I got the same in FLStudio, so I assume the reset implementation is just broken. best to not use it for now.



> I assume you have removed save ability of patches because it can interrupt something in most systems right? And import and save sections also don't react

not really, I had to remove the way vcv does things which do not work well for plugins.
DPF does not have a file-save mode yet, so in return cardinal doesn't have one either.
I will add an export function later on.

**Comment by falkTX** [comment]
Doing some cleanup, since we have clock as cv source now, going to close this ticket.
