### ISSUE TITLE
Cardinal-win64-22.07.zip does not contain CardinalSynth.vst or CardinalFX.vst

### ISSUE THREAD

**Issue by ThiccMomSwag** [DISTRHO/Cardinal#338]
Forgive me, I'm sure I'm missing something, but I've been struggling to figure out how to install the VST2 version of Cardinal to integrate into Reason, and I can't seem to find anyone online who can help, beyond pointing me to this .zip file to find two nonexistent folders. I literally made a github account to ask this so I'm entirely out of the loop about how to ask for help or access files. Please halp! <3 <3 <3

**Comment by falkTX** [comment]
There is a Cardinal.vst folder that includes the vst2 dll for fx and synth variants.

**Comment by ThiccMomSwag** [comment]
Oh jeez, there we go. Thanks so much, I figured it had to be something obvious. I'm now ready for the weekend, tysm <3 <3
