### ISSUE TITLE
e340 cloud

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#341]
Cloud generator is crashing app in Ableton live 11 Mac Catalina Au & vat 
Thanks

**Comment by falkTX** [comment]
I cant reproduce it, was this fixed in 22.11 as well? please confirm, thanks

**Comment by dromer** [comment]
@steveparkerdj please confirm this issue with the latest release as well :)

**Comment by dromer** [comment]
Lack of feedback so assuming this is fixed.
