### ISSUE TITLE
Befaco modules should't be light in light mode

### ISSUE THREAD

**Issue by armandvedel** [DISTRHO/Cardinal#343]
The Befaco modules are black IRL so maybe they shouldn't invert colors in light mode.

**Comment by falkTX** [comment]
that doesnt matter. mutable instruments are light mode IRL, so because of it they shouldnt have dark mode option?

for befaco we need to get permission anyhow, Manu didn't reply yet to our query.
first we see the reply, then either have it as option or not.

**Comment by armandvedel** [comment]
Well its fine by me but my point was that they could black by default and not have a dark mode. There is no real need for an "extra" light mode.

**Comment by falkTX** [comment]
> There is no real need for an "extra" light mode.

I have seen quite some people disagree.

I dont like it and wont use it myself, but for some it is very handy and much more readable than the dark version, so we do it.

**Comment by armandvedel** [comment]
OK well the way it is now there is no way to have both "IRL" mode for Mutable and Befaco. Anyway just sayin!

**Comment by falkTX** [comment]
Right, good point.

Is it better to have forced consistency of colors, or mimic the real hardware as much as possible?

Personally I never seen any module IRL, so I always prefer the color consistency.
It is all software and virtual, it does not need to match hardware. Skeuomorphic design is not always good.

**Comment by armandvedel** [comment]
I guess for branding it's good to have it be consistent with hardware. Modular people are picky!

**Comment by dromer** [comment]
We would have to add options in the menu for each module to set the specific panel mode. Ideally there is a standard method for doing this (so far the few modules that have a dark/light mode made their own implementations), but if we'd have to add this to every one that doesn't have a manual override it would cause a lot of extra work.
