### ISSUE TITLE
Polyphony doesn't seem to work (Live 11.1.6)

### ISSUE THREAD

**Issue by SexyPolisheHero** [DISTRHO/Cardinal#344]
So as the title indicates - I've installed latest Cardinal and went 1:1 with Venus Theory tutorial to get some basic knowledge how to operate on that. The problem is, he flawlessly play multiple sounds, while I'm being stuck in the monophonic. I've discovered that RMB on Host MIDI can let me enable Polyphony, but it still only sustains the last key being triggered.
I'm attaching how it looks on my side. Any tips/ideas?
![image](https://user-images.githubusercontent.com/66160150/183267059-cc6cbdf1-c116-4348-93c8-3b5e66d967a9.png)

**Comment by steveparkerdj** [comment]
From the looks of it I can say ... That synth is not polyphonic

**Comment by falkTX** [comment]
problem solved! 😅

**Comment by SexyPolisheHero** [comment]
Sorry for not being thorough enough, as this was my first date with this beauty :) Cheers!
