### ISSUE TITLE
Component Version: 22.5.0 (0x160500) crashing Logic AU validation

### ISSUE THREAD

**Issue by zmixnyc** [DISTRHO/Cardinal#352]
validating Audio Unit CardinalSynth by DISTRHO:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'DcnS' - 'Dstr'
--------------------------------------------------
Manufacturer String: DISTRHO
AudioUnit Name: CardinalSynth
Component Version: 22.5.0 (0x160500)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
[34m[0.001 info CardinalPlugin.cpp:235 Initializer] [0mCardinal Unknown v2.1.2
[34m[0.002 info CardinalPlugin.cpp:236 Initializer] [0mMac 12.6
[34m[0.035 info CardinalPlugin.cpp:237 Initializer] [0mBinary filename: /Library/Audio/Plug-Ins/Components/CardinalSynth.component/Contents/MacOS/CardinalSynth
[34m[0.035 info CardinalPlugin.cpp:238 Initializer] [0mBundle path: (null)
[34m[0.035 info CardinalPlugin.cpp:239 Initializer] [0mSystem directory: /Library/Application Support/Cardinal
[34m[0.035 info CardinalPlugin.cpp:240 Initializer] [0mUser directory: /Library/Application Support/Cardinal
[34m[0.035 info CardinalPlugin.cpp:241 Initializer] [0mTemplate patch: /Library/Application Support/Cardinal/template-synth.vcv
[34m[0.035 info CardinalPlugin.cpp:242 Initializer] [0mSystem template patch: /Library/Application Support/Cardinal/template-synth.vcv
[34m[0.035 info CardinalPlugin.cpp:256 Initializer] [0mInitializing plugins
[34m[0.142 info CardinalPlugin.cpp:259 Initializer] [0mInitializing plugin browser DB
[34m[0.152 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/ComponentLibrary/Rail.svg
[34m[0.246 info Rack/src/patch.cpp:273 load] [0mLoading patch /Library/Application Support/Cardinal/template-synth.vcv
[34m[0.248 info Rack/src/patch.cpp:339 loadAutosave] [0mLoading autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0010/patch.json
[34m[0.248 info Rack/src/patch.cpp:486 fromJson] [0mPatch was made with Rack v2.1.1, current Rack version is v2.1.2
[34m[0.253 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/ADSR.svg
[34m[0.254 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/ComponentLibrary/ScrewBlack.svg
[34m[0.254 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/port.svg
[34m[0.254 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/button-off.svg
[34m[0.254 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/button-on.svg
[34m[0.254 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/knob-marker.svg
[34m[0.254 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/knob.svg
[34m[0.255 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/knob-marker-small.svg
[34m[0.255 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/knob-small.svg
[34m[0.255 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/components/ADSR-bg.svg
[34m[0.256 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/VCA-1.svg
[34m[0.259 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Fundamental/res/VCO.svg
[34m[0.261 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Cardinal/res/HostAudio.svg
[34m[0.261 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/ComponentLibrary/PJ301M.svg
[34m[0.262 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Cardinal/res/HostMIDI.svg
[34m[0.263 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Cardinal/res/HostParameters.svg
[34m[0.264 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/Cardinal/res/HostParamsMap.svg
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Text Editor
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV ADSR
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCA
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCO
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Audio 2
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host MIDI
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters
[34m[0.264 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters Map
[34m[0.264 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/ComponentLibrary/Plug.svg
[34m[0.264 info Rack/src/window/Svg.cpp:28 loadFile] [0mLoaded SVG /Library/Application Support/Cardinal/ComponentLibrary/PlugPort.svg
Time to open AudioUnit:         350.170 ms
[34m[0.267 info Rack/src/patch.cpp:211 saveAutosave] [0mSaving autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0010/patch.json
[34m[0.274 info Rack/src/patch.cpp:339 loadAutosave] [0mLoading autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0010/patch.json
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Text Editor
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV ADSR
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCA
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCO
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Audio 2
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host MIDI
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters
[34m[0.277 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters Map
[34m[0.278 info Rack/src/patch.cpp:211 saveAutosave] [0mSaving autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0010/patch.json
WARM:
[34m[0.301 info Rack/src/patch.cpp:273 load] [0mLoading patch /Library/Application Support/Cardinal/template-synth.vcv
[34m[0.302 info Rack/src/patch.cpp:339 loadAutosave] [0mLoading autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.302 info Rack/src/patch.cpp:486 fromJson] [0mPatch was made with Rack v2.1.1, current Rack version is v2.1.2
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Text Editor
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV ADSR
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCA
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCO
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Audio 2
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host MIDI
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters
[34m[0.304 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters Map
Time to open AudioUnit:         25.667  ms
This AudioUnit is a version 2 implementation.
[34m[0.305 info Rack/src/patch.cpp:211 saveAutosave] [0mSaving autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.307 info Rack/src/patch.cpp:339 loadAutosave] [0mLoading autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Text Editor
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV ADSR
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCA
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCO
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Audio 2
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host MIDI
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters
[34m[0.309 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters Map
[34m[0.310 info Rack/src/patch.cpp:211 saveAutosave] [0mSaving autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.311 info Rack/src/patch.cpp:211 saveAutosave] [0mSaving autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.313 info Rack/src/patch.cpp:339 loadAutosave] [0mLoading autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Text Editor
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV ADSR
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCA
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCO
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Audio 2
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host MIDI
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters
[34m[0.316 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters Map
FIRST TIME:
Time for initialization:        0.016 ms

* * PASS
--------------------------------------------------
VERIFYING DEFAULT SCOPE FORMATS:
Input Scope Bus Configuration:
 Default Bus Count:0

Output Scope Bus Configuration:
 Default Bus Count:1
    Bus Name: Output
    Default Format: AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved

* * PASS
--------------------------------------------------
VERIFYING REQUIRED PROPERTIES:

* * PASS
--------------------------------------------------
[34m[0.316 info Rack/src/patch.cpp:211 saveAutosave] [0mSaving autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.318 info Rack/src/patch.cpp:339 loadAutosave] [0mLoading autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Text Editor
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV ADSR
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCA
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget VCV VCO
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Audio 2
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host MIDI
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters
[34m[0.320 info Rack/src/app/RackWidget.cpp:327 fromJson] [0mCreating module widget DISTRHO Host Parameters Map
VERIFYING RECOMMENDED PROPERTIES:
  VERIFYING PROPERTY: Latency
    PASS

* * PASS
--------------------------------------------------
VERIFYING OPTIONAL PROPERTIES:
  VERIFYING PROPERTY Tail Time
    PASS
  VERIFYING PROPERTY Bypass Effect
    PASS

* * PASS
--------------------------------------------------
VERIFYING SPECIAL PROPERTIES:

VERIFYING CUSTOM UI
Cocoa Views Available: 1
  JUCE_AUCocoaViewClass_30527374993e8a72
    PASS

HAS FACTORY PRESETS

VERIFYING CLASS INFO
[34m[0.321 info Rack/src/patch.cpp:211 saveAutosave] [0mSaving autosave /var/folders/88/0g82_jxd13s_wkhbgwjc40lw0000gn/T/Cardinal.0011/patch.json
    PASS

TESTING HOST CALLBACKS
    PASS

* * PASS
--------------------------------------------------
PUBLISHED PARAMETER INFO:

# # # 39 Global Scope Parameters:

* * PASS
--------------------------------------------------
FORMAT TESTS:

Reported Channel Capabilities (explicit):
      [0, 2]  

No Input, Output Chans:
0-1   0-2   0-4   0-5   0-6   0-7   0-8
      X                                   

* * PASS
--------------------------------------------------
RENDER TESTS:

Output Format: AudioStreamBasicDescription:  2 ch,  44100 Hz, Float32, deinterleaved
Render Test at 512 frames

validation result: crashed validation

**Comment by falkTX** [comment]
This has already been reported in #335 and #194
