### ISSUE TITLE
Open Demo/Example project- some crash Logic

### ISSUE THREAD

**Issue by RossoRacer** [DISTRHO/Cardinal#353]
Etherpad, Gabberswing and Interverb all cause Logic Pro to crash...

Crash log below.

[Untitled.zip](https://github.com/DISTRHO/Cardinal/files/9380607/Untitled.zip)

**Comment by rickympls** [comment]
Etherpad & Interverb crash for me as well.  I can open Gabberswing without crashing.
This was already reported in #272

**Comment by falkTX** [comment]
this should be fixed in 22.11, please confirm

**Comment by RossoRacer** [comment]
Yep, works fine now.

**Comment by falkTX** [comment]
cool, thanks for checking!
