### ISSUE TITLE
Host Time doesn't send Trigger Signals in Logic Pro 10.7.2 

### ISSUE THREAD

**Issue by leowieber** [DISTRHO/Cardinal#358]
Hi, thanks for making this plugin, I really love it ! 

I am encountering the issue that the host Signal isn't sending anything out (the lights are not blinking as well) 
the display is working in time with logic tho. 

Any Idea What it could be ? 

Thanks a lot for your time !

**Comment by taijireality** [comment]
I'm having the same issue/

**Comment by falkTX** [comment]
This bug seems quite weird to me, is the host time module always with "playing" light up?

**Comment by taijireality** [comment]
No - only time code is running when DAW is in play mode, none of the outputs are lighting up.

**Comment by falkTX** [comment]
and this is with 22.07? the lack of transport info on AU was an issue in 22.06

**Comment by leowieber** [comment]
I just checked and I am on 22.06, thanks for pointing this out ! 
I will download 22.07 !

Thanks for your time !

**Comment by leowieber** [comment]
Ok it works on 22.07, thanks again for your response !!!

**Comment by dromer** [comment]
Always try at least the latest release before reporting bugs, duh.
