### ISSUE TITLE
VST3 Not working in Ableton Live 11 on MacOS

### ISSUE THREAD

**Issue by jeatzr** [DISTRHO/Cardinal#359]
Cardinal VST3 version is not detected in Ableton 11 as a plugin

FX and Synth versions are OK.

<img width="304" alt="Captura de Pantalla 2022-08-31 a las 14 56 27" src="https://user-images.githubusercontent.com/90786962/187683616-4900aff3-383c-476e-b159-82babd4313bc.png">

**Comment by falkTX** [comment]
yep, known "issue" and wont be fixed. Ableton does not support VST3 CV ports so it cannot load the plugin
