### ISSUE TITLE
Patch export

### ISSUE THREAD

**Issue by dromer** [DISTRHO/Cardinal#36]
It's currently possible to import Rack patches, but it would be nice if we could also export patches so we can exchange with other users.

**Comment by falkTX** [comment]
To add a note on why here, it is simply DPF lacking such an API for the moment.
Even the file browser open is a sorta new thing, the save part is just missing there. Shouldn't be hard to do since native platform APIs usually are very similar for open and save actions.

**Comment by dromer** [comment]
Perfect, let us know when anything needs to be added for this.

**Comment by falkTX** [comment]
This one is done now
