### ISSUE TITLE
Add README to releases artifacts

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/Cardinal#363]
I noticed that during the [Cardinal One Synth Challenge](https://sites.google.com/site/kvrosc/2022/osc-163-cardinal) a common question was: "What are these different plugin versions?".

I suggest adding the README or at least the [Plugin variants section](https://github.com/DISTRHO/Cardinal#plugin-variants) to the build artifacts.

**Comment by falkTX** [comment]
Fixed in a5c1cbb361125f58b14bbb966b1190fef62f66c3
