### ISSUE TITLE
Favourites, zoom settings etc not carrying over in instances.

### ISSUE THREAD

**Issue by scotttswan** [DISTRHO/Cardinal#367]
In Bitwig loading multiple Cardinal VST's my favourites don't carry across to new instances or previously loaded instances of Cardinal.

Bitwig  4.3.4
Cardinal 22.07

**Comment by falkTX** [comment]
yep, known "issue" and wont be fixed.
Cardinal saves no global config on disk ever. every part of the state is saved in the host.

at some point I had favorites disabled, but it would be a bit confusing like this for you. but it was requested to have it enabled even if limited in scope/usage, which is how it is now.
