### ISSUE TITLE
Midi out CV-Cc is possible? 

### ISSUE THREAD

**Issue by vcvrackideas** [DISTRHO/Cardinal#37]
Hi, recently I tried to choose cv-cc module to get some cc automation in Ableton but it seems doesn't work. I don't exactly remember but it can behaves similar in other midi out modules

**Comment by falkTX** [comment]
maybe it works if you remove the midi out module first?

for now in cardinal you can only have kind of 1 midi out module at a time.

**Comment by dhstsw** [comment]
Cardinal Host Params won't work on Ableton Live the way it's implemented now.
In Live you can't (from the DAW) set arbitrary automation channels to send automation.
The plugin must first 'comunicate' to Ableton it's existence (usually one just touch or move the parameter and Live aknowledge it).
As it is, Host Params is strictly monodirectional (only receiving), so it won't work with Live.

**Comment by falkTX** [comment]
Is there no built-in / generic plugin view?
That is very odd design decision if so.

I can make clicking/dragging send the current value I guess, but it is IMO quite silly that we need such a thing.
Are plugins without a custom GUI not supported at all in Ableton? so weird..

**Comment by dhstsw** [comment]
Yup, plugins with custom gui are supported.
To "enable", for example, the automation lane for the Cutoff, one has to simply move the cutoff in the plugin.
In some case (i guess it depends in how the plugin has been implemented) there's a "middle step":  enable the "configure" window in Ableton Plugin instance (see below), hit the configure button, touch the parameter in the custom plugin gui to enable the corresponding lane. Some are like this, some are not.
Anyway, just a "click box" for every lane (just maybe "click the number") in Host Params should work.
![image](https://user-images.githubusercontent.com/59790194/145202395-08b65069-e434-443c-bec6-eb7ac9665b99.png)

**Comment by dhstsw** [comment]
Hi,

the "Fake parameter change when clicking host parameter module build #382" solved the issue with Ableton Live, now i can automate.

Thanks.  :)

**Comment by falkTX** [comment]
Cool! Glad to know it works!
I only tested on FLStudio, works there. On Bepoke it doesnt but we reported an issue for it (it is for Bespoke to fix).
In any case, this specific ticket is not about this.

**Comment by falkTX** [comment]
You can now use multiple modules that make use of midi drivers, done in 95c1d3ccfbf688b723e82321e7b1d6db7ee7130e
I consider this fixed.
