### ISSUE TITLE
Add Aetrion-modular Chord Vault

### ISSUE THREAD

**Issue by disconcert** [DISTRHO/Cardinal#379]
This is a useful module to record chords from keyboard controller. 
It was GPL only but I asked the dev to change to + (don't know if that was the reason).

https://github.com/aetrion-music/aetrion-modular

**License**
The aetrion brand and logo are copyright (c) 2022 Mirko Melcher ([m@aetrion-music.com](mailto:m@aetrion-music.com)), all rights reserved.

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

All graphics in the res and res_src directory are copyright © 2022 Mirko Melcher ([m@aetrion-music.com](mailto:m@aetrion-music.com)). All graphics in the res and res_src, other than the aetrion logo, are licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/).

**Comment by dromer** [comment]
Please don't create issues for adding modules, there is this discussion: https://github.com/DISTRHO/Cardinal/discussions/63 and this wiki-page: https://github.com/DISTRHO/Cardinal/wiki/Possible-modules-to-include

**Comment by falkTX** [comment]
yep, already on the wish list.
22.09 already adds a few new modules, focus now is on getting the light panels done and a few issues to fix. contributions welcome.

**Comment by disconcert** [comment]
My bad.
I can contribute with the light panels... where can I see which are done / needed?

**Comment by dromer** [comment]
https://github.com/DISTRHO/Cardinal/issues/378 << but this is all mainly done in software. we don't create separate panel artwork, but instead modify the colors during rendering.
