### ISSUE TITLE
ShapeMaster Pro Plugin

### ISSUE THREAD

**Issue by synapt1c0llapse** [DISTRHO/Cardinal#380]
How can I get this Pro plugin in Cardinal? Or it's only available in LV2less VCV Rack 2 Pro?

**Comment by falkTX** [comment]
That "Pro" plugin is not opensource, thus never going to be in cardinal

**Comment by synapt1c0llapse** [comment]
Thnq 4 quick answer Filipe and for all you work on KX, so needful for all mankind!
Best regards from trancemaker of besieged Russia ;)
