### ISSUE TITLE
No MIDI input in native version (v22.09, Windows 10)

### ISSUE THREAD

**Issue by ThePython10110** [DISTRHO/Cardinal#384]
For some reason, Cardinal doesn't respond to either of my MIDI devices. I have rebooted (just in case), as well as clicked "Enable/Reconnect MIDI" multiple times. The plugin versions and even the web version work fine, and I'm too lazy to learn how to use Jack to test the Jack version.

**Comment by falkTX** [comment]
Good catch, windows midi support was not enabled on such builds.
Sadly now too late for 22.09 release.

Anyhow, fixed in 4d9081762db2d57344d4795be2d50016a68a42ad
Will be part of next release
