### ISSUE TITLE
problems moving plugin window to another screen.

### ISSUE THREAD

**Issue by scotttswan** [DISTRHO/Cardinal#386]
in Bitwig and reaper.
latest release version.

steps to reproduce:
1: add cardinal Instance.
2: click show plugin window.
3: move the cardinal plugin window to another monitor
4: click show plugin window.
5: click show plugin window.

What happens:
The Cardinal window appears as a blank white screen not responding.

**Comment by falkTX** [comment]
what OS? are the screens perhaps using different scale factors? or something that is different between them?

**Comment by scotttswan** [comment]
Windows 10

no, i do have a different scale factor on my laptop screen but this is between two monitors that have the same scale factor. 

It does the white screen / not responding on all 3.

**Comment by scotttswan** [comment]
If i disconnect all my monitors the instance screen that is broken can be opened but as soon as i reconnect the monitors and try and open it again bitwig remembers where the cardinal was and its white again.

**Comment by scotttswan** [comment]
the instance of cardinal sound does work whilst its not trying to display its screen.

**Comment by scotttswan** [comment]
can replicate with other plugins in bitwig so closing as its probably a bitwig bug
