### ISSUE TITLE
Native version occasionally ignores Note Off messages

### ISSUE THREAD

**Issue by ThePython10110** [DISTRHO/Cardinal#389]
Sometimes, MIDI notes get stuck on for no obvious reason. I checked, and it doesn't happen with the plugin or web versions, just the native one.

(Windows 10, Cardinal-win64-acfba568)

**Comment by BrunoDSL** [comment]
Can confirmed this issue also happens in the latest release as well.

**Comment by falkTX** [comment]
Fixed in 442365e7e8d0c9dda89d1332632f5bfffaf2b614
