### ISSUE TITLE
Plugin request: dbRackModules, dbRackSequencer, and FormulaOne

### ISSUE THREAD

**Issue by ThePython10110** [DISTRHO/Cardinal#390]
All 3 have GPL-3.0 licenses.
[dbRackModules](https://github.com/docb/dbRackModules)
[dbRackSequencer](https://github.com/docb/dbRackSequencer)
[Formula One](https://github.com/docb/dbRackFormulaOne)

**Comment by falkTX** [comment]
Dont open tickets for requests, use the discussions tab instead.
Thanks
