### ISSUE TITLE
Possible to exclude particular modules from module browser?

### ISSUE THREAD

**Issue by brylie** [DISTRHO/Cardinal#391]
How can I disable or hide specific modules from the module browser? Note: this is the opposite of adding to favorites.

**Comment by dromer** [comment]
Use the filter functions?

**Comment by brylie** [comment]
For clarification, say I don't want Module X to be displayed at all, without explicitly filtering it. There is a similar feature on the1.x Module Browser module where I could specify that certain modules will be hidden. On Rack 2.x, I am able to uninstall specific modules. However, with Cardinal how can I hide or uninstall specific modules?

**Comment by falkTX** [comment]
This is not supported. And since we dont save global state on disk, there would be no way to save such info anyhow.

**Comment by brylie** [comment]
OK, I was thinking there may be some way to read an exclusion list from a text file, for example.
