### ISSUE TITLE
Module request: Lindenberg Research/LRTRack

### ISSUE THREAD

**Issue by avianArsonist** [DISTRHO/Cardinal#396]
https://github.com/lindenbergresearch/LRTRack
I'd really like to see this added if the licensing permits, there's some excellent filters in there (along with other modules).

**Comment by falkTX** [comment]
the module as they exist as releases in vcv library today are not opensource, so they cant be used in cardinal.
I already asked the dev, he is willing to open the source if we pay for it.
See https://github.com/lindenbergresearch/LRTRack/issues/65

realistically that is not happening though, better to focus our efforts into modules that are more welcoming to opensource.
