### ISSUE TITLE
Keyboard repeat flag is ignored on Windows

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#40]
Tested on FLStudio inside a VM.
Curiously FLStudio on macOS works well.

**Comment by vcvrackideas** [comment]
if this about not working hotkeys in Windows I can confirm that for Ableton too

**Comment by falkTX** [comment]
no, I detected at least in FLStudio that typing a key can easily make it input multiple characters.

the hotkeys do not seem to be working on any system at the moment.
