### ISSUE TITLE
Portable version of CardinalNative for Windows?

### ISSUE THREAD

**Issue by bandithedoge** [DISTRHO/Cardinal#400]
Hi, I'm trying to run CardinalNative from a USB drive. The .zip releases don't have CardinalNative in them so I tried extracting the installers and running it from there, but it seems like it expects resources at `C:\Program Files\Common Files\Cardinal` no matter what. Is there a way to make it load resources from another directory? If not, how difficult would be to compile and distribute a portable version?

**Comment by falkTX** [comment]
You should be able to create a "resources" folder on the same path where Cardinal.exe exists, and Cardinal will use those resources first before trying the system-wide ones.

Let me know if this works, I only have used this locally and did not try with the release builds, so not 100% it works as-is..

**Comment by bandithedoge** [comment]
Unfortunately this doesn't work either. Could it be because I'm running it through Wine? I'll only be able to test it on a real Windows machine tomorrow.

![image](https://user-images.githubusercontent.com/26331682/194401438-bb4adf3b-d43e-4ced-b199-0aa7919130b3.png)

![image](https://user-images.githubusercontent.com/26331682/194401566-2f9f8ef3-0338-44f6-8b08-b60103af7f95.png)

**Comment by falkTX** [comment]
Cardinal doesnt work under wine, there is something that libzstd or libarchive uses that doesnt work under wine, dont know why yet.
But from how you placed the files it was supposed to work...

**Comment by bandithedoge** [comment]
Just checked on a real Windows PC, same result.

**Comment by bandithedoge** [comment]
Would it be possible to let users override the resources directory with, say, a CLI argument?

**Comment by dromer** [comment]
environment variable perhaps?

**Comment by bandithedoge** [comment]
That would work as well, although I think a CLI argument would be more handy for those portable situations. Or both, why not.

**Comment by flashblaze** [comment]
@bandithedoge were you able to get this working? I want to install Cardinal in a different drive other than C which I'm unable to do so due to the things which you've mentioned

**Comment by bandithedoge** [comment]
> @bandithedoge were you able to get this working? I want to install Cardinal in a different drive other than C which I'm unable to do so due to the things which you've mentioned

No, I ended up using Rack portable.

**Comment by flashblaze** [comment]
Hi @falkTX sorry for the late reply. I tried the actions build version a day after your comment and totally forgot to mention that it worked for me w/o any issues. Thanks a lot for this!

**Comment by falkTX** [comment]
Nice nice, I am closing the issue then, thanks for verifying
