### ISSUE TITLE
Save as / Export and Export uncompressed json options don't do anything in Cardinal standalone

### ISSUE THREAD

**Issue by tristanbay** [DISTRHO/Cardinal#401]
I can't save my patch in Cardinal standalone in the normal way. If I press File > Save as / Export... or File > Export uncompressed json, nothing happens. When I open Cardinal from the terminal, thre doesn't seem to be any errors there, either. What's going on? Is this is a bug or is it on my end? I'm on Artix Linux (no Systemd) and I think I downloaded Cardinal from the Arch community repo.

**Comment by falkTX** [comment]
This is a known "issue", and has been reported already.
See https://github.com/DISTRHO/Cardinal/blob/main/docs/FAQ.md#on-bsdlinuxx11-the-menu-item-save-asexport-does-nothing for details.
