### ISSUE TITLE
Frame rate locked at 40 fps

### ISSUE THREAD

**Issue by GBaige** [DISTRHO/Cardinal#402]
Using REAPER v6.67 and any variant of Cardinal VST3, the frame rate is locked at 40 fps, I'd like it to run at a higher frame rate

The update rate option only allows to cut the frame rate in half or in quarter

**Comment by falkTX** [comment]
this is unsupported, gui updates are driven by the host.
cardinal requests a 60fps idle loop, but hosts are free to run it at a slower pace.

**Comment by GBaige** [comment]
> this is unsupported, gui updates are driven by the host. cardinal requests a 60fps idle loop, but hosts are free to run it at a slower pace.

You're right... I just tried it out on another DAW (Renoise) and the refresh rate there is higher.

**Comment by GBaige** [comment]
@falkTX I tried the vst3 variant on Renoise and unlike the vst2 variant, this one updates at half the refresh rate (30fps), is this still due to the host?

**Comment by falkTX** [comment]
Yes. Hosts sometimes have different rates per plugin format. I know FLStudio rate limits VST2 plugins quite hard (max 20fps) but VST3 allows up to 60fps.
