### ISSUE TITLE
Parameters with VST3

### ISSUE THREAD

**Issue by vitreo12** [DISTRHO/Cardinal#409]
Hello!

I have been happily using Cardinal within the SuperCollider programming language using the wonderful [VSTPlugin](https://git.iem.at/pd/vstplugin) extension.

I have noticed that Cardinal parameters are not working the same way between the VST2 and VST3 versions. While they seem to be correctly exposed in the VST2 version, I only see them as being "shadowed" by the MIDI controls in the VST3 one. What I mean is that I can seem to access them as MIDI CC, but not as parameters using the Parameter Host module, which I can otherwise correctly use in the VST2 version.

 Is this a known issue?

**Comment by falkTX** [comment]
All formats should work the same way. the vst3 and midi cc weirdness comes from vst3 not supporting MIDI and needing workarounds to achieve similar results to MIDI.

Some hosts handle this better than others, I have seen hosts automatically hiding the special MIDI CC related params which makes them easier to use.

If the VST2 version works, keep using that one. Besides CV ports (which no host whatsoever supports right now) and host-side UI resizing, when it comes to Cardinal the VST3 version brings nothing extra vs VST2.
VST3 is an awful standard, we are better using old VST2 or switching to alternatives such as CLAP or LV2.

From my POV this is not an issue with Cardinal, just a side-effect from VST3 being weird.

**Comment by vitreo12** [comment]
I see, thanks!

I would prefer to use the VST3 version since it provides me with more audio inputs to do audio rate modulation from the outside.

Would you perhaps reckon that the parameters are just shifted in order? Perhaps their indices start after all the MIDI ones? If this is the case, how many MIDI entries are overwriting parameters? I could just start writing parameter values starting from index 185 or something, if you know this value. Or is it more likely that MIDI is just overwriting parameters altogether?

**Comment by falkTX** [comment]
regular params in cardinal vst3 start after 130*16 entries.
(128 midi ccs + pitchbend + channel pressure, for 16 channels)

**Comment by vitreo12** [comment]
Great stuff! Got it now to work by indexing parameters 2080 (130*16) onwards :)

Thanks a lot, I'll be closing this for now
