### ISSUE TITLE
Finalize VST3 implementation

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#41]
It is incomplete from DPF

**Comment by falkTX** [comment]
So mostly works for first release, but known not to work:
- audio buses setup
- keyboard handling is flaky
- cv not implemented, though ports are tagged as cv ports already

likely others

**Comment by falkTX** [comment]
Before anyone asks, seems the VST3 doesnt work on Ableton.
Don't know why yet.

**Comment by rafaelferreiraql** [comment]
Modwheel/MIDI CC support seems to not work in VST3 as well (at least on my Reaper Win8 64bit setup).

**Comment by hmturnbull** [comment]
This is probably a known issue already, but I figured I'd mention it in case it helps with this issue.  I use Studio One 5.5.2 (Windows 64bit), and the VST3 version of Cardinal lacks any interface whatsoever.  VST2 seems to be working, so there's no rush.  I just thought I'd mention this in case it helps.

![Cardinal Synth - VST3 Studio One 5](https://user-images.githubusercontent.com/52052397/168376981-58b442d7-809d-4158-b829-dedd715ae348.jpg)

**Comment by alfonso73** [comment]
Hi, if i try to grab the bottom-right triangle to resize the Cardinal window nothing happens. The triangle isn't draggable.

**Comment by falkTX** [comment]
Improvements coming in 22.06, to be released tomorrow.

MIDI CC input is now handled, and UI works better.
I was also able to load it in Ableton Live, though only FX and Synth variants. The "main" variant still does not load.

![image](https://user-images.githubusercontent.com/1334853/175807359-8800ab46-e5db-43f9-b24b-8de48d647278.png)

**Comment by hmturnbull** [comment]
When I tried to open the VST3 version in Studio One 5, Studio One crashed immediately.

**Comment by 807Recordings** [comment]
Last few days I been searching on this topic with no clear answer.
22.07 VST3 
Ableton Live 10.1.43
Big Sur 11.5.6
I can use Cardinal and play external Midi into the plugin however AU, or VST3 versions do not allow me to send out. Totally greyed out on Host Midi Module so not even an option to send internally.
Midi Time works to sync Sequencers from the host (Ableton), and of course I can use external keyboard to play synths.

Is this a limitation or something obvious I missed?

**Comment by falkTX** [comment]
AU MIDI out does not work at the moment, but VST3 MIDI out for sure works. I had it running just a few days ago while testing for other things.

**Comment by 807Recordings** [comment]
![Screenshot 2022-07-20 at 17 56 56](https://user-images.githubusercontent.com/109671413/180028419-cd69c845-d976-401b-9467-8c2522153091.png)
Please see this is greyed out.

**Comment by falkTX** [comment]
that is a label, for separating options related to input and output.
so basically you have:
1. input only options
2. output only options
3. input + output options

**Comment by 807Recordings** [comment]
@falkTX Thanks for the fast reply, and I confirm it works now. Missed the obvious, but I couldn't find any documentation.
Suddenly I do not miss my Doepfer MAQ 16/3 anymore :D

**Comment by bandithedoge** [comment]
VST3 generally works well in Ableton on Windows 10, although delay compensation is broken. It always shows 0 samples even on more complex patches and goes out of sync with the rest of the project.

![image](https://user-images.githubusercontent.com/26331682/182311913-17f5b3a9-40c1-4cb7-b3f4-628b1da6a5fe.png)

![image](https://user-images.githubusercontent.com/26331682/182311991-58c64968-e0a4-4d43-90e5-d406188f6ca1.png)

**Comment by mxmilkiib** [comment]
I keep forgetting to ask; are there any VST3 hosts that implement the VST3 version of CV ports (like LV2 has)?

**Comment by falkTX** [comment]
It is part of the spec, so I suspect there is at least one...
But I dont know of any myself.
Carla will get there eventually, but it is not ready yet.

**Comment by falkTX** [comment]
As of latest nightly, I consider VST3 support stable.
For those not wanting to use nightlies / action builds, wait until 22.09 official release for all the fixes
