### ISSUE TITLE
Multi-stereo in/outputs don't seem to work

### ISSUE THREAD

**Issue by rafaelferreiraql** [DISTRHO/Cardinal#411]
Using Reaper x64 on Windows 10, Cardinal version 22.10, VST3.

Not sure if it's a Cardinal issue or just me being a noob, but I can't get Cardinal to work with in/outs for anything other than Channels 1 and 2. I do know how to use multi-in/outs in Reaper, and I can get VeeSeeVSTRack to do that easily (in the same track, even), but not Cardinal.

**Comment by falkTX** [comment]
FX and Synth variants of Cardinal have only stereo.
Only the "main" variant has more IO than this, but also CV ports which sadly is unsupported by most VST3 hosts.

**Comment by steveparkerdj** [comment]
I tried today on Ableton with vst3 and all  8channels work perfectly (I was able to send diferente sounds to different seperate channel mixers on live)

**Comment by falkTX** [comment]
yeah, there was a silly code mistake leading to this. it was obvious once someone pointed it out to me... 🤦 
great that it all works in the end
