### ISSUE TITLE
100% guaranteed crash if I try loading any Valley plugin (terrorform, plateau...)

### ISSUE THREAD

**Issue by 6884** [DISTRHO/Cardinal#413]
Hi,

as per the title, in Ableton live 11.0.12 and I think a newer version as well, on OSX 10.15.7

Boom, immediate crash, no questions asked ¯\_(ツ)_/¯

**Comment by falkTX** [comment]
can confirm, seems intel macos builds also need memory alignment stuff, but weirdly the macos ARM builds dont   need  it (so I didnt see the issue  until now).

anyhow,  fixed on latest builds and on the  upcoming 22.11  release.
