### ISSUE TITLE
Graphical glitch when zooming in on sample using cANARd sampler, VST3

### ISSUE THREAD

**Issue by GBaige** [DISTRHO/Cardinal#428]
When zooming in on sample using left-click and drag, the sample window will appear to stretch outside of the module's bounds.

![image](https://user-images.githubusercontent.com/115324169/202918673-f6dd66dd-3b4d-457c-abb3-d57563e64222.png)

**Comment by dromer** [comment]
The same issue is in Rack2 and likely it's an issue with the module itself.
Would be better if you report this upstream: https://github.com/sebastien-bouffier/Bidoo

**Comment by GBaige** [comment]
Opened new issue in Bidoo's repo. Thanks!
