### ISSUE TITLE
Aaron Static's ChordCV display glitches

### ISSUE THREAD

**Issue by Yoppez** [DISTRHO/Cardinal#431]
Tested on Windows 11 with Cardinal 22.10 both Native and Jack

Video of how it looks on my machine:
https://user-images.githubusercontent.com/44178021/203320081-64163497-af5a-426a-b69d-ef68a4cc995c.mp4

All the other modules from Aaron Static are displayed correctly, this is the only one that have these glitches.

Edit:
Tested on Linux, the same glitch appears there too.

**Comment by dromer** [comment]
That's very strange, I do not see this glitching here at all (Linux, Debian 11, Fluxbox).

Which window-manager and/or graphics card do you use?

**Comment by Yoppez** [comment]
> Which window-manager and/or graphics card do you use?
On Linux I used kwin on Wayland, the graphics card is an AMD RX 6800

> does the same happen on the web version for you? in https://cardinal.kx.studio/
Nope, on the web version seems OK.

**Comment by Yoppez** [comment]
Also I tested the same plug-in on VCV Rack, and it is fine on there too.

**Comment by dromer** [comment]
@Yoppez do you still see this on latest nightly builds?

**Comment by Yoppez** [comment]
Unfortunately I cannot test it with the system that I used when I had this problem, but in the system that I'm using right now it works fine.

**Comment by dromer** [comment]
Thank you for confirming.
(as good as any)
