### ISSUE TITLE
22.11 VST 2 and VST 3 version don't work in Ableton on Windows 11 (Standalone works fine)

### ISSUE THREAD

**Issue by cuevasclemente** [DISTRHO/Cardinal#445]
When I try to use Cardinal on Windows 11 in Ableton Live 11, neither the VST 2 nor VST 3 plugins work. But the standalone application works fine. The plugin isn't even loading, I don't get into an interface, just the blank window, as shown in the screenshot.

I've gotten Cardinal to work in Ableton a long time ago on a different machine in Windows 11, not sure if I had to do anything special.

![image](https://user-images.githubusercontent.com/6854890/204938977-15f7f048-3aeb-430f-a09e-5f3c8f61040d.png)

**Comment by falkTX** [comment]
first time I see this issue, considering standalone works but plugin does not...
can you try the same cardinal version on another host/daw please?

**Comment by cuevasclemente** [comment]
Yes, I tried it in Reaper for Windows and it actually works just fine, leading me to believe that something weird might be happening specifically with Ableton or my version of Ableton (here's a screenshot of it working in Reaper): 
![image](https://user-images.githubusercontent.com/6854890/205164521-c7a64eb4-4017-4cf1-b73b-3cb2e42e48b5.png)

I'm curious what might be worth investigating next.

**Comment by falkTX** [comment]
You can try https://github.com/DISTRHO/DPF-Plugins/releases win64 builds, as those use the same framework as Cardinal when it comes to plugin support. See the screenshots in https://github.com/DISTRHO/DPF-Plugins for how the GUIs are supposed to look like.

**Comment by cuevasclemente** [comment]
Hey, I reinstalled Ableton and that seemed to resolve it. Thanks for the advice. No idea how this could have happened but maybe someone in the future might see this and try this. This was the only external VST this happened with which is part of the reason why I thought it might have been a Cardinal Issue. Thanks again!

**Comment by dromer** [comment]
This seems to be resolved and hasn't been reported by anyone else.
