### ISSUE TITLE
Building on Windows / msys2

### ISSUE THREAD

**Issue by stoermelder** [DISTRHO/Cardinal#446]
I did a fresh checkout of the main branch and trying to build on Windows. What I'm doing wrong?
```
Compiling CarlaPluginLV2.cpp
In file included from CarlaPluginLV2.cpp:25:
../../utils/CarlaLv2Utils.hpp:75:10: fatal error: lilv/lilvmm.hpp: No such file or directory
   75 | #include "lilv/lilvmm.hpp"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:125: ../../../build/backend/Debug/CarlaPluginLV2.cpp.o] Error 1
make[2]: Leaving directory '/home/Ben/Cardinal/carla/source/backend/plugin'
make[1]: *** [Makefile:112: /home/Ben/Cardinal/carla/build/modules/Debug/carla_plugin.a] Error 2
make[1]: Leaving directory '/home/Ben/Cardinal/carla'
make: *** [Makefile:163: carla] Error 2
```

**Comment by falkTX** [comment]
Buildinng Cardinal requires a filesystem with symlink support, as a few files placed in git are symlinks in order to avoid duplicate files.
Windows still does not support this.

**Comment by stoermelder** [comment]
Ok, so no development on Windows possible?

**Comment by falkTX** [comment]
might be possible under WSL, not sure.

I personally never run windows, and common contributors to the project are in the same position.
so there is very little interest on changing this at the moment.

**Comment by stoermelder** [comment]
Ok, thanks for letting me know.
