### ISSUE TITLE
VST3 version not reported correctly in Steinberg Cubase

### ISSUE THREAD

**Issue by TheAndyMac** [DISTRHO/Cardinal#448]
The VST3 SDK version information is being reported in Cubase (10.5.30, 11.0.41 an 12.0.52) as "Travesty 3.7.4" rather than "VST 3.7.4" which means that the plugin is not listed as a VST3 plugin in the Cubase plugin insert menus and is also captured in their exported plugin information as "Other Plugins" rather than "VST3 Plugins". 

Having tested on other hosts (Cakewalk, Cantabile 4, Gig Performer 4.5, VST Live and WaveLab) it seems to be very specific to the way Cubase uses this information, but it does make it confusing using Cardinal in Cubase, and maybe could cause issues when Steinberg remove VST2 support in the future, depending on how they identify acceptable VST3 plugins.

**Comment by dromer** [comment]
Of course Cubase/Steinberg/Yamaha tries to prohibit anything other than their own SDK to be used ... uhg.

**Comment by falkTX** [comment]
dont think that is the case, not intentionally. they are likely lazy and just use the string from "sdk_version" as a shortcut to decide where to place plugins.
they likely did not expect anyone to be using something other than their VST3 SDK to make VST3 plugins :sweat_smile:

**Comment by falkTX** [comment]
Fixed in fdfe20b606791d437c4ad3a44da8bf21986dcdee
