### ISSUE TITLE
Add Sapphire Elastika to Cardinal?

### ISSUE THREAD

**Issue by cosinekitty** [DISTRHO/Cardinal#449]
I would like to submit my [Sapphire](https://github.com/cosinekitty/sapphire) plugin, particularly its module [Elastika](https://github.com/cosinekitty/sapphire/blob/main/Elastika.md), as a candidate for inclusion in Cardinal. Elastika was recently featured in a [video by Omri Cohen](https://www.youtube.com/watch?v=DEoMeNHOVgE), and with the resulting attention, people are starting to ask me if it can be added to Cardinal. So here I am.

Some quick facts:

* Sapphire is licensed GPLv3+.
* It uses a few very simple knob and slider graphics that would have to be replaced for licensing reasons. Hopefully this is minor.
* All other artwork in the panel design falls under GPLv3+.

I will be happy to do as much of the porting work as would be helpful. I already have Cardinal building and running on my Linux system, and I'm reading the developer documentation now. I just wanted to post this issue to find out if a pull request would be welcomed, or is there another route to including a new module in Cardinal?

Thank you!

**Comment by falkTX** [comment]
Add it to the list https://github.com/DISTRHO/Cardinal/wiki/Possible-modules-to-include

The issue tracker is not meant to be used for requesting modules.
