### ISSUE TITLE
CLAP plugin is not recognized by REAPER in Linux

### ISSUE THREAD

**Issue by gautrstafr** [DISTRHO/Cardinal#454]
Hi All, I've been using CLAP versions of Surge XT and some CHOW FX. I've been looking to use more CLAP plugins so decided to give Cardinal a try. 

I installed release v22.11 and even though the VST2 and VST3 are recognized and loaded into Reaper, LV2 and CLAP versions are not recognized by REAPER.

**Comment by falkTX** [comment]
LV2 main variant uses CV ports which is not supported by reaper, so it is normal it wont load there. the synth and fx should though.
For CLAP, this has been working since ever, so I wonder if the issue is something else.

**Comment by dromer** [comment]
@falkTX here on Linux the LV2 main does load. I've even routed cv ports between two instances (quite a hassle compared to jack or carla).

All CLAP variants also load here:

![](https://i.imgur.com/q43aesi.png)

**Comment by gautrstafr** [comment]
@dromer is there anything special you did with the install? I just downloaded version 22.11 tarball, extracted and moved the clap folder to my clap path where REAPER is scanning.

**Comment by gautrstafr** [comment]
![image](https://user-images.githubusercontent.com/104796852/206330034-9d0baa82-0634-454b-860d-427504c4dd96.png)

just got it working, figured out I had a typo on the clap and lv2 paths in my home folder. Managed to get it recognized
