### ISSUE TITLE
Can't find Surge XT modules in Cardinal

### ISSUE THREAD

**Issue by mestretheo** [DISTRHO/Cardinal#457]
Sorry if it's too dumb, but I installed Cardinal v22.11 using the Cardinal-win64-22.11-installer.exe but it seems it don't bring along the Surge XT modules. Are they somewhere else? What I'm doing wrong? If a kind soul could explain to me I'll immensely appreciate.

**Comment by dromer** [comment]
SurgeXT is not part of the 22.11 release.

Use the nightly builds from the `Actions` tab, build it yourself or wait until 22.12 is released.

**Comment by mestretheo** [comment]
Oh, really? I was wondering why those 'Add surgext' in the DISTRHO/Cardinal public page were there. I hope those devs put Surgext as part of the modules. They're wonderful for educational purposes.

Thank you very much, dromer.

**Comment by falkTX** [comment]
they are... already been added, will be part of 22.12 release or you can use the nightly/actions builds.

**Comment by mestretheo** [comment]
Great! Looking foward for 22.12. I'm not skilled enough to make builds on my own, but thanks for the tip. Better wait.
