### ISSUE TITLE
Please add Atelier Palette module if possible

### ISSUE THREAD

**Issue by vcvrackideas** [DISTRHO/Cardinal#46]
https://github.com/Xenakios/Atelier
I just can't live without it. Plaits on supersteroids ;-)

**Comment by falkTX** [comment]
This is a challenging one since it is basically the same as an existing plugin, just with some variations.
So let's make a deal..

I will add this one. But once the file->export is in place, I will ask you to make a CC-0/public-domain patch to be included with the Cardinal plugin. Deal? :)

**Comment by vcvrackideas** [comment]
huh, no questions!) Choose a genre please and amount of modules (biggest, moderate or minimum ;-)

**Comment by falkTX** [comment]
Now everything in there in the latest builds, both Atelier and file->export.
Added mscHack too.

For patch ideas, to try to give you some inspiration I can mention a few things... (not strict rules in any way)
1. something (very?) simple yet sounding good~okay
2. does not use much cpu so it will run on most PCs without problem
3. alike a template to build stuff on top

My idea is to try to get a few patch files that would be useful to have as demos or starting points.
Thanks
