### ISSUE TITLE
Reaper crashes by selecting LyraeModules in Cardinal plugins browser

### ISSUE THREAD

**Issue by danodan** [DISTRHO/Cardinal#468]
I use Cardinal as VST with Reaper. Everytime I pick-up LyraeModules in the plugin browser (brand selection control), the preview of the plugins is interrupted brutally and the whole Reaper crashes. For a blink of the eye you can see that 2 plugins preview images remain black, before it crashes. I tried VSTi, VST3, VST3i but nothing change. I tried both Cardinal-linux-x86_64-22.12 and Cardinal-linux-x86_64-22.11 and the result is the same. I use it on Manjaro linux and Reaper version is 6.72.
I've tried every other brand and all are showing up, the only with this problem is LyraeModules.
This is the output of reaper
![reaperoutput](https://user-images.githubusercontent.com/28441328/209874418-eb45b5a2-c8f4-4074-9e30-97b6bf86dd4d.jpg)

**Comment by dromer** [comment]
Odd, works for me:

![](https://i.imgur.com/Tl67BYJ.png)

**Comment by danodan** [comment]
I removed all the svg files related to the module Vega, inside its res folder. Now it shows up. 
![2022-12-29_09-17-19](https://user-images.githubusercontent.com/28441328/209923827-9c1cb4cb-02ae-4aad-bb3c-b552728be180.png)
The problematic files:
![image](https://user-images.githubusercontent.com/28441328/209924130-a469230b-6aa3-4b02-9c86-ab4ac9eb079a.png)

For me it's ok now, is not a module that I use.
