### ISSUE TITLE
Bogaudio LFO reset not working

### ISSUE THREAD

**Issue by gigamesh** [DISTRHO/Cardinal#471]
I'm likely making a noob mistake, but I can't seem to get any LFO to reset no matter what I provide as an input. Shouldn't this make it restart its waveform every time I hit a key?

patch: https://www.dropbox.com/s/xkxy9uag7yy4woq/lfo-reset.vcv?dl=0

![image](https://user-images.githubusercontent.com/32403632/210188349-c2b17d4c-3743-4866-a699-9837156a0834.png)

**Comment by gigamesh** [comment]
@falkTX Sorry I should have clarified: I tried several LFOs I couldn't get the reset to work on any of them. Patching from the MIDI gate should theoretically work, right?

**Comment by dromer** [comment]
I think this works correctly in the latest builds.
