### ISSUE TITLE
Using Surge XT modules will cause garbage/leftover directories to be created under the Documents directory

### ISSUE THREAD

**Issue by GBaige** [DISTRHO/Cardinal#485]
![image](https://user-images.githubusercontent.com/115324169/216522893-62b7f8c5-dd73-4a48-ba3d-c8f1682ebd1b.png)

**Comment by falkTX** [comment]
That is how the module works. one of the few ones where extra dirs make sense, because you can place extra wavetables in there

**Comment by GBaige** [comment]
That makes sense; I understand I can just delete the directories if I don't use/need them, but it'd be nice to have an option to not create them.
