### ISSUE TITLE
Add airwindows  module

### ISSUE THREAD

**Issue by hornyjailfish** [DISTRHO/Cardinal#488]
Bunch of airwindows plugins in one module relesed recently 

https://github.com/baconpaul/airwin2rack

License from readme:
This is MIT licensed, like Airwin, but the combined work with rack is of course GPL3 as distributed here.

The clipper airwindows graphic is freely distributed by airwindows

the jakarta and fira mono font are both openSIL https://tokotype.github.io/plusjakarta-sans/

**Comment by falkTX** [comment]
such requests should be done in a discussion, please do not use issue tickets as module requests
https://github.com/DISTRHO/Cardinal/discussions/63 already contains quite a lot of them, and the wiki page formalizes them a bit more.
