### ISSUE TITLE
Abnormally Hight Cpu usage on "idle" modules. ( Reaper, standalone(native), Windows 7/10 )

### ISSUE THREAD

**Issue by Ongomato** [DISTRHO/Cardinal#490]
Some modules exhibit significant increase in CPU usage after not receiving any input for a short period of time(2-4 seconds). Especially problematic on heavy modules. 
This happens in Reaper on all plug-in formats, and in a standalone native build, both on windows 7 and 10. 
Doesn't happen in other DAWs ( FL studio, Ableton, Bitwig )

![2023-02-08-15-55-49](https://user-images.githubusercontent.com/37831257/217580660-96c65fdd-131b-4e9b-85ac-eb53b65c0988.png)

**Comment by dromer** [comment]
We've seen a couple odd issues with Reaper related to transport.
Do you see this a difference in cpu usage when you have transport idle VS running?

**Comment by Ongomato** [comment]
Just checked, transport doesn't seem to affect this in any way. 
I get exactly the same CPU usage as in standalone version.

**Comment by falkTX** [comment]
This is likely related to denormals.
I hate the idea of messing up with global state from within the plugin, but for this I dont think we have a choice.

@Ongomato do you know how to get the latest github action builds? I can do a test build fix if you are willing to give it a try.

**Comment by Ongomato** [comment]
Sure, i can test if it works.

**Comment by falkTX** [comment]
ok pushed a test build in https://github.com/DISTRHO/Cardinal/actions/runs/4127770798
should be ready in ~1h from now.

**Comment by Ongomato** [comment]
Tried the test build just now and it looks like the fix worked, the issue is gone.
Thank you.

**Comment by falkTX** [comment]
Thanks for checking!

Will add this as part of the 23.02 release

**Comment by falkTX** [comment]
This was an old bug we forgot to close, doing that now
