### ISSUE TITLE
22.12 "Favorites" modules not saving

### ISSUE THREAD

**Issue by mauvehead** [DISTRHO/Cardinal#492]
**v22.12:**  My "Favorites" modules are not saving when reopening the AU. My "Favorites" are retained during the duration of a given project session but as soon as I close and reopen a project then my "Favorites" are forgotten.

I'm on a 2021 MBP M1Max (18,4), Monterey 12.6.3, LPX 10.7.7 (via Rosetta). 

Please advise. Thanks!

**Comment by dromer** [comment]
See https://github.com/DISTRHO/Cardinal/issues/277

Favorites are saved per plugin inside your DAW session, as part of the plugin state.

There is currently no Cardinal settings being stored on the system, so nowhere to store such favorites either.

**Comment by falkTX** [comment]
yeah, this is "feature not a bug", though not directly intentional.

personally I would not even show the favorites as a thing that is available, but some people like to have such option even if it is limited
