### ISSUE TITLE
Feature request: expose the host song position / "long phase"

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/Cardinal#494]
I would like the Host Time module to include a CV output for the "phase within the song", for lack of a better word.
It would be an output similar to the Bar Phase, but on a much longer time scale.
Ideally the exact length should be user editable within the module, expressed in number of bars.

Use case:

I was making a generative patch that is synced to Ardour and I wanted to automate some parameters on a longer time frame.
I ended up using the Host Time Bar Phase trough a [div](https://zzc.github.io/en/clock-manipulation/divider) to give me a 128 bar phase signal which was used to drive the phase of a shapemaster.

This worked OK, but I could only ever start the song from the beginning, plus I needed some semi convoluted logic to sync the "long phase" to the bars of the host.

**Comment by dromer** [comment]
Why not just set an automation for one of the host parameters and make that run from low to high over the course of your track?

**Comment by magnetophon** [comment]
I didn't think of that, great idea!

**Comment by dromer** [comment]
Haha, no problem! This way you can easily change the curve to follow your track. And the added benefit that anywhere in the track it's position will be deterministic ;)
