### ISSUE TITLE
Scrolling left-right should be inverted

### ISSUE THREAD

**Issue by c-ham** [DISTRHO/Cardinal#503]
cf. https://github.com/DISTRHO/Cardinal/issues/102#issue-1091352050

The same thing happens to me as described in this post. Currently when my fingers go to the left, the display moves to the left (which is weird and confusing). But when my fingers go up, the display moves down (per the usual convention). I didn't see an option to invert the left-right movement and I think that scrolling left-right should be in the inverted direction by default, like in other apps. Or at least there should be an option to change it easily in the menu.

I'm running the VST3 plugin in Windows 11, Live 11.

**Comment by GBaige** [comment]
Can confirm left-right trackpad gestures are inverted, REAPER v6.78, Cardinal VST3 (main) 23.02; I almost exclusively use middle-mouse-click with an external mouse to scroll, but the left-right trackpad gestures are inverted.

E.g. gesturing to scroll to the bottom-left would result in a scroll to the bottom-right.

**Comment by dromer** [comment]
Can also confirm. And an important side-note: in VCVRack this behavior is correct

**Comment by dromer** [comment]
Should be fixed in https://github.com/DISTRHO/Cardinal/commit/ba9ad5f2e5d1108ed56855c668505b08120a76ef

**Comment by falkTX** [comment]
Closing, will be part of 23.04 release

**Comment by ndstephens** [comment]
If the horizontal scroll direction could ever become a user preference that would make for a great addition.  Personally I struggle with moving my fingers on the trackpad to the right, yet the modules on the screen go to the left.  Really enjoying the software.  Thanks for all the great work.
