### ISSUE TITLE
cardinal crashes and key command errors w/ ableton

### ISSUE THREAD

**Issue by ethrence** [DISTRHO/Cardinal#516]
hey, been using cardinal for a few months now and have noticed a few bugs appear since the last 2 updates.

first issue is ctrl+d to duplicate a module and the backspace to delete a module command have a strange issue where only one of them will work at a time (if backspace works on the vst2 version of cardinal synth then ctrl+d will not and vice versa, this appeared 2 updates back and i didnt care enough to say anything)

i went to check as to which versions certain commands would work on earlier but can no longer open the vst2 versions of cardinalsynth or cardinalfx without them crashing ableton 

none of the vst3 versions allow me to use ctrl+d and only backspace works

also i think i saw someone talking about this earlier but surge modules crash cardinal everytime i open one lol

for context im running ableton live 11.2.6 on windows 10 w/ a ryzen 7 5700x

**Comment by oiwn** [comment]
just noticed that keybindings does no work in REAPER, and come to issues to check.

Options named "Send all keyboard input to the plugin" right click at plugin inside FX window.

But i still can't print . (dot) for module values

**Comment by falkTX** [comment]
the surge module crashes have been fixed in 23.07, regarding weird keyboard input stuff please refer to #304 where discussion around it should happen.
closing this ticket.
