### ISSUE TITLE
Zzc module pack for phase daw output

### ISSUE THREAD

**Issue by vcvrackideas** [DISTRHO/Cardinal#52]
Hi, Zzc modules have been updated recently, just in case https://github.com/zezic/ZZC

**Comment by falkTX** [comment]
Since @zezic has been involved somewhat, we can just ask.
Are those v2 ready? Should we add them to Cardinal now?

**Comment by zezic** [comment]
@falkTX Yes, they should be V2 ready now. But let me fix this issue: https://github.com/zezic/ZZC/issues/82
I will post with update to this thread when its ready.

**Comment by zezic** [comment]
So, yes, @falkTX, I just fixed the https://github.com/zezic/ZZC/issues/82 and **now** current ZZC master should be compatible with v2 (tag v2.0.1) and now it has support for the Rack's room brightness and light bloom controls.
I can add PR by myself, but I think you will do it better and faster! Feel free to ask for tweaks in case of any problems.

**Comment by falkTX** [comment]
Thanks, will do soon.
Do your plugins make use of `osdialog`? That is the only tweak needed for Cardinal, from what I saw there is no use of external files so this should be fine..

**Comment by zezic** [comment]
Plugins included in **v2.0.1** are **not** dependent on osdialog.

But I'm preparing a wavetable player for a future release and currently I use osdialog to select files in it. I can add the preprocessor defines to support various file selecting libraries if you suggest me some alternative to osdialog, or, maybe, point me to an example of how to do it properly inside Cardinal. That way my plugins will be compatible with Cardinal out of the box.

**Comment by falkTX** [comment]
Should be done now in https://github.com/DISTRHO/Cardinal/commit/4682417dbd8b6f9409426ed3d12ba5adafe0e69d though there might be some extra LTO things to do, I only went at it by eye for now.

**Comment by falkTX** [comment]
LTO build completes ok, headless one fails but that is a separate issue.
Closing this ticket then.
