### ISSUE TITLE
stocaudio modules are included in Cardinal but the license is GPL-3.0-only according to their GitHub page

### ISSUE THREAD

**Issue by GBaige** [DISTRHO/Cardinal#525]
The [VCV Library](https://library.vcvrack.com/stocaudio) lists stocaudio as GPL-3.0-or-later, as does the module info within Cardinal; but the [GitHub page](https://github.com/aptrn/stocaudio-modules) it links to, states the license is GPL-3.0-only.

Was an exception made for this plugin or is the license stated in the GitHub page misleading/erroneous?

**Comment by falkTX** [comment]
there is no "only" or "or later" when defining the current active license. these only vs or-later are always defined elsewhere.
the license is gpl3, whether "or later" is allowed is not part of the license document. this is normal

**Comment by dromer** [comment]
For reference: Rack modules list their precise license identifier in the plugin.json -> https://github.com/aptrn/stocaudio-modules/blob/master/plugin.json#L5 
This is their "officially" announced license that should be used as the reference for such cases.
