### ISSUE TITLE
How do I install the Mini variants?

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/Cardinal#528]
They get built, but not installed, as far as I can tell.
Do I need to do anything different?
I've looked at the makefile, but I don't see where ``APP_EXT`` gets defined.

Here's the relevant part of the output: https://gist.github.com/magnetophon/c33baec34794e428071bf20fe94e0099

**Comment by falkTX** [comment]
Indeed, I forgot to add it in https://github.com/DISTRHO/Cardinal/blob/main/Makefile#L272

Since you are packaging and testing this, a patch-fix would be appreciated.
Should be simple enough just following the rest of the "install" make rule

**Comment by falkTX** [comment]
The `$(APP_EXT)` comes from DPF, it just expands to ".exe" on windows and nothing for other platforms.

I can fix this myself for 23.04 in case you have troubles coming up with a patch-fix.

**Comment by magnetophon** [comment]
What do you mean by patch-fix, if not a PR?

**Comment by falkTX** [comment]
an actual patch file? it doesnt have to be a PR, good patch or just inline diff in the comments works too.
it is just faster for you to verify this now since you are already dealing with packaging it.

**Comment by magnetophon** [comment]
Thanks!
