### ISSUE TITLE
The location of the source changed in release 23.02

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/Cardinal#529]
Small nitpick, and I wasn't gonna mention it, but since you will probably do a bugfix release anyway, due to https://github.com/DISTRHO/Cardinal/issues/528, you might want to fix this in the same go.

The location was: 
```https://github.com/DISTRHO/Cardinal/releases/download/${version}/cardinal+deps-${version}.tar.xz```
and now it is:
```https://github.com/DISTRHO/Cardinal/releases/download/${version}/cardinal-${version}+deps.tar.xz```

**Comment by falkTX** [comment]
is this solved for 23.07 release?

**Comment by magnetophon** [comment]
Yes, thank you!
