### ISSUE TITLE
Cardinal crashes when used in Reaper in Arch Linux

### ISSUE THREAD

**Issue by vijaymarupudi** [DISTRHO/Cardinal#531]
Specifically, I load up Cardinal it loads fine initially. When I right click, and search with the strings "eg" or "env", it crashes (when I type the 'g' and the 'v'). I suspect one of those modules that appears in the search results causes the crash.

Oddly, Cardinal works fine outside of the DAW (standalone). Two months ago, I did not have this problem.

* It crashes when used as either an LV2 or a CLAP plugin
* It does not crash when used standalone
* `strace` doesn't show any failed system call
* I've tried the Arch Linux packaged build and built it from `main` today, both still crash.
* Does not crash when using Ardour

**Comment by chakravala** [comment]
Not for me, I'm using Reaper, Arch Linux, LV2, when I try these search strings it doesn't crash for me.

**Comment by vijaymarupudi** [comment]
Not sure why, but it seems to work for me now! Weird. Closing!
