### ISSUE TITLE
Some Valley modules crash upon loading on release builds; issue not present in regular builds (Windows-only issue?)

### ISSUE THREAD

**Issue by GBaige** [DISTRHO/Cardinal#532]
Tested on REAPER v6.78, Cardinal VST3 (main) a42ca2c, Windows 11, all Valley modules load without issues.

Tested on REAPER v6.78, Cardinal VST3 (main) 23.02, Windows 11, certain Valley modules such as Dexter crash.

Issue possibly related to #502 where enabling LTO was the culprit for Surge XT modules crashing on Windows builds?

**Comment by falkTX** [comment]
LTO is no longer enabled by default as it was causing issues like these, plus both VCV and module developers do not check/test for it anyway.
Closing the ticket as solved.
