### ISSUE TITLE
Bigger UI font

### ISSUE THREAD

**Issue by rncar** [DISTRHO/Cardinal#537]
In VCV Rack we have `pixelRatio` in the `settings.json` file.
Where is this setting in Cardinal ?

**Comment by falkTX** [comment]
there isnt, the ratio comes as exposed from the host or system scaling if standalone.

**Comment by rncar** [comment]
I use Linux, What settings follow Cardinal to the UI scale? 
Thanks falkTX for your quick response.

**Comment by rncar** [comment]
`export DPF_SCALE_FACTOR=1.6`

works perfect in my system.
