### ISSUE TITLE
MIDI Out Not Working (Ableton 11)

### ISSUE THREAD

**Issue by IsaacFox** [DISTRHO/Cardinal#540]
Hello,

I am trying to send MIDI out from Cardinal to the rest of Ableton, but it won't detect a signal. Any suggestions? I tried sending through a clock, then tried using DGate, also the Euclidean sequencer, and Note Seq.

Thank you,
Isaac

**Comment by dromer** [comment]
Are you using the synth or fx plugin?

Could be that Ableton doesn't allow this for either of the plugin type.

**Comment by dromer** [comment]
I just tried this and it works.

Loaded Cardinal Synth on two tracks, then the second track receives midi from the first one.
However the trick seems to be that you have to arm both the tracks, otherwise Ableton won't correctly run them at the same time.
