### ISSUE TITLE
Audio Core Module Does not provide same options as Desktop version does

### ISSUE THREAD

**Issue by jp-gorman** [DISTRHO/Cardinal#55]
Tested version : SHA - 4a85fc8

Scenario:
Audio Control to have available audio devices that I have in normal Desktop VCV Rack 2

Expected:
To have same audio devices, sample rates and block sizes as are available on Desktop VCV Rack 2

Actual:
Only had "1-2 out", one sample rate and one  block size.

Again, I don't know the ins and out of the software, so no idea if these are a side effect of the integration or what, so just reporting. Missing HDMI support was a big one as with Rack on the large screen HDMI is what I used.
Can I assume these are meant to be provided as options given they work on the dekstop version Version ?

**Comment by falkTX** [comment]
This is expected, audio goes through the host and nothing else.
The removal of desktop audio is done on purpose in order to simplify the audio threading.

That said, on systems with JACK installed (and running) it is possible to get this to work as regular standalone as Cardinal (through DPF) uses JACK as a kind of plugin API.
The standalone is mainly for testing and development purposes though.

Getting desktop audio into and out of Cardinal is out of scope for the project.

**Comment by jp-gorman** [comment]
I'm currently running on OSX 10.15.6 and am still a newb at VCV. I threw an LCO into a VCO via scope into audio (1/2) on Cardinal and can hear the VCO via the "plugin device - 1-2 output" in the audio module. I see nothing while monitoring on Reaper channel (but mute on reaper silences it so it must be coming through somehow).

"This is expected, audio goes through the host and nothing else." - Does this mean I need to route via "Cardinal carla plugin host Audio 1" or some other means to capture the output. it appears the audio can be heard and muter in reaper when the audio is patched to the plugin 1-2 audio module.

I'm pretty sure this is my inexperience here, but some input would be great on how I should expect to use the Cardinal modules - thx.

**Comment by falkTX** [comment]
You can ignore Carla stuff.

What is likely going on here is the host silently stopping the audio going to the Cardinal plugin as a CPU saving feature.
Some hosts will simply skip processing audio for FX plugins when they have nothing to send to it.
I know renoise does this, calling it "smart disable".
