### ISSUE TITLE
Wrong way to look up Documents dir on Linux

### ISSUE THREAD

**Issue by jn64** [DISTRHO/Cardinal#553]
It seems like Cardinal is looking for the env var `XDG_DOCUMENTS_DIR`:

https://github.com/DISTRHO/Cardinal/blob/a51cb460bc958b60c7b40c0d27943a136fe1f49b/src/CardinalCommon.cpp#L497-L500

`XDG_DOCUMENTS_DIR` is not a known env var in the [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (unlike say `XDG_CONFIG_HOME`)

I think this was mistakenly taken from `user-dirs.dirs(5)`. `XDG_DOCUMENTS_DIR` is a variable only used inside the user-dirs.dirs file, not an env var. This file is meant to be sourced by shell scripts. I know of some programs (e.g. JUCE) parse this file to get the various user folders.

The result is that Cardinal is looking in `~/Documents`, even though my documents folder is `~/docs`:

```sh
# ~/.config/user-dirs.dirs
XDG_DESKTOP_DIR="$HOME"
XDG_DOCUMENTS_DIR="$HOME/docs"
XDG_DOWNLOAD_DIR="$HOME/downloads"
XDG_MUSIC_DIR="$HOME/music"
XDG_PICTURES_DIR="$HOME/pics"
XDG_PUBLICSHARE_DIR="$HOME/public"
XDG_TEMPLATES_DIR="$HOME/templates"
XDG_VIDEOS_DIR="$HOME/vids"
```

**Comment by falkTX** [comment]
well that makes it kinda useless.

for storing documents the "config" dir is wrong, we dont want hidden configuration files here.
the fallback is basically the same as VCV Rack btw

**Comment by falkTX** [comment]
so if I understood this right we need to basically:
1. check if `XDG_CONFIG_HOME` is set, fallback to `$HOME/.config` if not
2. read `$_CONFIG_DIR/user-dirs.dirs` and try to parse it without errors
3. use a `XDG_DOCUMENTS_DIR` inside it if available, otherwise fallback to `$HOME/Documents` (or maybe use localization to find fallback docs path, but that becomes too much)

**Comment by falkTX** [comment]
both of those implementations don't bother to check for `#` that would make something a comment, or duplicated env vars where the last one is what should end up being used, or prefixes added to the var like `PLEASE_IGNORE_XDG_DOCUMENTS_DIR=/not/this/one`.

both seem to use an awful way for parsing, no error checking done at all besides checking if the folder exists...

that at least makes it easier on our side, as the bar is quite low for a quick and dirty implementation

**Comment by jn64** [comment]
Quick and dirty will do IMO. If the user has a malformed file, a lot of things will break before they get to Cardinal.

**Comment by EnigmaCurry** [comment]
I think you can just exec `xdg-user-dir DOCUMENTS` to get the correct directory path

**Comment by falkTX** [comment]
yes, but exec within a plugin is frowned upon as it duplicates file descriptors and other things.
anyway the parsing of the file is not that complex
