### ISSUE TITLE
Dependancies not listed in build instructions

### ISSUE THREAD

**Issue by riban-bw** [DISTRHO/Cardinal#556]
The build instructions in https://github.com/DISTRHO/Cardinal/blob/main/docs/BUILDING.md does not list autoreconf as a dependency. Builds fail if this package is not installed. Need to add to the Debian dependencies:

```
dh-autoreconf
```
and similar for other platforms

**Comment by falkTX** [comment]
That is only needed if you use the default vendored libraries. For packaging distros tend to use the `SYSDEPS=true` option which skips the need for autoconf/automake stuff.

The only weird real dependency is `cmake`, due to surge-xt things.

Need to find a nice way to describe the situation in that file... :thinking:

**Comment by riban-bw** [comment]
Should `SYSDEPS=true` be the default?

**Comment by falkTX** [comment]
No, because it puts the burden on the builder to provide a few extra libs.
If we want the build to be as simple as possible, the dependencies also need to be as little as possible.

**Comment by riban-bw** [comment]
There is already a section in the build instructions for dependencies for `SYSDEPS=true`. Should you just add dh-autoreconf to that section?

**Comment by falkTX** [comment]
dh-autoreconf is debian specific though, correct would be either autoconf or automake, not really sure now, maybe it needs both

**Comment by riban-bw** [comment]
Indeed but there is a dedicated section in the page for Debian dependencies for SYSDEPS=true into which this specific dependency can be added.

**Comment by riban-bw** [comment]
Also missing dependency: libfftw3-dev
