### ISSUE TITLE
Some Surge XT modules cause horrible noise at startup

### ISSUE THREAD

**Issue by rafaelferreiraql** [DISTRHO/Cardinal#565]
Whenever I open a project with certain Surge XT effect modules (I can think of Distortion and Delay, but there are probably others), it bursts into horrible noise in any track with Cardinal using them. It can be reverted every time by simply unplugging and re-plugging certain cables on the VST (in my experience, seems to be the cables connected directly to audio out), but it's super annoying to be blasted with a jumpscare every time i work on a project using these modules.

Windows 10 64-bit, Reaper 6.79, Cardinal VST3 23.07.

**Comment by dromer** [comment]
Can you try the latest nightly build? There have been some updates to Surge modules since your report.

**Comment by rafaelferreiraql** [comment]
> Can you try the latest nightly build? There have been some updates to Surge modules since your report.

Ok this is embarassing and I should've said it when I realized it. I found out the horrible noise was not by Surge, but the mscHack mixers.

**Comment by dromer** [comment]
@rafaelferreiraql is this still an issue with those mixers and do you see the same result in VCV Rack?

**Comment by rafaelferreiraql** [comment]
> @rafaelferreiraql is this still an issue with those mixers and do you see the same result in VCV Rack?

Tried just now to invoke the bug to happen on 24.04 CardinalFX, nothing happened. Not sure if I've done something wrong but no horrible noise at project startup.

**Comment by falkTX** [comment]
Likely fixed with the update, lets assume fixed then. Please let us know if it happens again and we will reopen this ticket, thank!
