### ISSUE TITLE
Pressing F9 in Cardinal crashes FL Studio instantly

### ISSUE THREAD

**Issue by Vospi** [DISTRHO/Cardinal#570]
VST3, Windows 10 x64, latest legit non-beta FL Studio. Cardinal v23.07.

If I'm not focused on Cardinal, then F9 works fine (it's supposed to open FL Studio mixer).
Patch didn't seem to matter, the default patch crashed, even a completely empty patch crashed.

Both CardinalSynth and CardinalFX lead to the same result.

**Comment by dromer** [comment]
Hmm, I get a segfault when pressing F9 on standalone.

**Comment by Vospi** [comment]
This is a crippling issue for me. Every time I try to go to my mixer with F9 (a habit of over 20 years), I get an irreversible crash of my whole project, not just Cardinal patch. Please, please fix it.

If I can be of any assistance as a tester, I'd be happy to do so, too.

**Comment by falkTX** [comment]
Fixed in 08763a2318f86a2351364299d8868581560b1b83
