### ISSUE TITLE
Copy-pasting modules doesn't seem to work anymore

### ISSUE THREAD

**Issue by Vospi** [DISTRHO/Cardinal#571]
I'm using this build on Windows, VST3, FL Studio 21:
https://github.com/DISTRHO/Cardinal/actions/runs/5997176313

1) Ctrl-C -> Ctrl-V on a module doesn't seem to have any effect.
2) Copy-pasting a module via top Edit menu doesn't seem to have any effect.

Ctrl-D works without issue. Plugin has control over keystrokes. Other plugins in my DAW process Ctrl-C Ctrl-V without issue.

**Comment by falkTX** [comment]
does copy/pasting work on the text editor module?
wondering if this is an issue of the host capturing those keys or not.
try also with the standalone if you can, thanks

**Comment by Vospi** [comment]
The text editor module didn't respond to them as well.
But! Even just using a Cardinal's menu (Rightclick, Copy, Paste) doesn't do anything for me. Neither for the modules nor the text. :)

**Comment by dromer** [comment]
For me this doesn't work in any version, but I'm very sure that it did not too long ago.

And I mean even copy/paste within the same instance does not work (standalone or plugin).

**Comment by dromer** [comment]
Correct. On standalone I see this in the console:
`[8.034 warn Rack/src/app/RackWidget.cpp:571 pasteClipboardAction] Could not get text from clipboard.`

**Comment by rafaelferreiraql** [comment]
I'm failing to Ctrl+C Ctrl+V, perhaps because of host intervention (Ctrl+D works tho), but with the edit menu it seems to work just fine to me. (23.07 VST3, Reaper, Windows)

**Comment by falkTX** [comment]
This got broken by mistake in 23.09, should be fixed now with the latest builds.

We should very likely do a 23.10 release as this issue seems quite important to have fixed in a stable release.
Let's see what other things we manage to fix too, and then go for it..

**Comment by Vospi** [comment]
Oh, I love it! Thank you so much!

**Comment by falkTX** [comment]
Fixed in 23.10 release
