### ISSUE TITLE
Low mouse wheel sensitivity

### ISSUE THREAD

**Issue by tapochqa** [DISTRHO/Cardinal#572]
Mac OS 10.15.7, Cardinal 23.07. The mouse is Logitech G-102. 

Scrolling speed is unbearably low. I need like 10 full turns to navigate through the scene.

**Comment by tapochqa** [comment]
What I do: scroll the mouse wheel outside of any knobs one full 360° turn. 

What should happen: the whole rack moves vertically reasonably far, like in any other program. 

What happens: the whole rack moves vertically at the very short distance, making scrolling uncomfortable.

**Comment by henning** [comment]
Does that still exist with the latest version? 

One idea: pressing control makes the knobs be more sensitive/move faster.

Maybe that works on the scrolling of the whole rack too?

**Comment by tapochqa** [comment]
> Does that still exist with the latest version?

Yes it does.

> One idea: pressing control makes the knobs be more sensitive/move faster.
> 
> Maybe that works on the scrolling of the whole rack too?

No it doesn't work.

**Comment by scotttswan** [comment]
In Windows, with bitwig scalling switched off and in a second monitor (2k monitor)  i get the same issue.  zooming is very slow,  scrolling up and down is slow too.   holding the scroll wheel and panning is grand.   

can we get a sensativity option to help with this?

**Comment by cosinekitty** [comment]
I have the same issue in Debian Linux. Using the mouse wheel to scroll the brand plugin filter takes an extremely long time. Like an entire rotation just to get a couple of millimeters of movement.

**Comment by dromer** [comment]
Every since the recent DPF update scrolling is unusable.

I think there might be a bug :thinking:

**Comment by justindelay** [comment]
Can confirm the issue on Debian.
