### ISSUE TITLE
fixing unless_modules repo

### ISSUE THREAD

**Issue by unlessgames** [DISTRHO/Cardinal#574]
So I just saw a removed merge request on gitlab about memory leaks in my module, I couldn't restore that request but [made the exact changes](https://gitlab.com/unlessgames/unless_modules/-/commit/12346b2aaa2190bd04649f56fd23e4a607ee691f) and removed an additional log from another module that was left in by accident. 

Not sure how exactly this works with the removed merge and submodules but if you want/need to get back in sync with the repo then it contains the fixes from the request now.

Last commit is

https://gitlab.com/unlessgames/unless_modules/-/commit/5a9a1727436f95fbe28e77fcd91e38e38418a58f

Thanks for reporting/fixing the leaks btw!

**Comment by falkTX** [comment]
right, sorry I deleted my gitlab account since I was not using it much at all.
I will prepare a document regarding updating included modules (but it is just a matter of updating the git submodule within the cardinal repo)

thanks for merging the changes

**Comment by falkTX** [comment]
this was fixed in 7cc1309a686cb2068650564765acdbe1b1f6bcc5, modules are updated now!
