### ISSUE TITLE
Versioning of the Apps and Install Package. 

### ISSUE THREAD

**Issue by paul-cossey** [DISTRHO/Cardinal#575]
Hi, folks 

We've been asked to install Cardinal for one of our customers. But we've come across some inconstancies with the release version number listed on GitHub and the version numbers of the installed Apps, plugins and package receipts. 

Would it be possible for these (or at least some of these) to match the release number on GitHub?

For example CardinalNative.app and CardinalJACK.app don't have any version numbers in the info.plist. Usually these would be defined with the key `CFBundleShortVersionString` (or `CFBundleVersion`) currently there are no version numbers listed at all. 

Most of the plugins/VST's have a version number of 1.0. The only ones that don't are:

```
 <pkg-ref id="studio.kx.distrho.cardinal-components" packageIdentifier="studio.kx.distrho.plugins.cardinal.components" installKBytes="349772">
        <bundle-version>
            <bundle CFBundleShortVersionString="23.7" CFBundleVersion="23.7" id="com.DISTRHO.CardinalFX" path="CardinalFX.component"/>
            <bundle CFBundleShortVersionString="23.7" CFBundleVersion="23.7" id="com.DISTRHO.CardinalMIDI" path="CardinalMIDI.component"/>
            <bundle CFBundleShortVersionString="23.7" CFBundleVersion="23.7" id="com.DISTRHO.CardinalSynth" path="CardinalSynth.component"/>
        </bundle-version>
```
But the issue with those is `23.7` doesn't match the GitHub release of `23.07`

All the installer package receipts are at version 0 too. 
<img width="818" alt="Screenshot 2023-09-05 at 11 20 02" src="https://github.com/DISTRHO/Cardinal/assets/16046272/8154e2a4-9bc4-457c-a085-789fb889b8f3">

These is an excellent post here on packaging guidelines for App developers: https://github.com/n8felton/proper-packaging-principles 

Thanks, please feel free to reach out of you have any questions or if you need to me clarify further 😃

**Comment by falkTX** [comment]
> We've been asked to install Cardinal for one of our customers

What do you mean by customers here?

the version from the AU is due to juce taking out the 0 prefix, and using 0 as the version for all others is intentional as that allows to more easily replace all package contents when reinstalling the macOS pkg (otherwise we need to deal with tagging individual files/binaries, too much hassle)

the standalones can easily have the version info sure, that is a good point.
the rest shall remain as-is for the time being.

**Comment by paul-cossey** [comment]
> What do you mean by customers here?

We're a managed service provider, and have been asked by a Uni we look after to install Cardinal on a teaching lab. 

> the standalones can easily have the version info sure, that is a good point.

Awesome! thank you, versioning on standalone App's will be perfect for our needs.

**Comment by falkTX** [comment]
> > What do you mean by customers here?
> 
> We're a managed service provider, and have been asked by a Uni we look after to install Cardinal on a teaching lab.

There might be problems here, Cardinal is affected by the many modules having a "non-commercial" clause on their artwork, making Cardinal also unusable for anything that is deemed "commercial".
Universities usually take money in the form of tuition or entry fees, or maybe just donations if this is a one-off class.
Such practices are not allowed.

The same applies to most VCV Rack modules, but they just hand-wave the problem and ignore it most of the time.
I suggest to NOT do the same here.

**Comment by falkTX** [comment]
Are the latest builds ok now?

**Comment by paul-cossey** [comment]
Looks good, thanks @falkTX 😄

**Comment by falkTX** [comment]
ok closing the ticket then
