### ISSUE TITLE
Ship with plugin presets when available

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#58]
Currently this is missing

**Comment by jypma** [comment]
I've created a simple Kick drum, using the host automation parameters for some variability:
[Cardinal_Synth_Kick.tar.gz](https://github.com/DISTRHO/Cardinal/files/7865248/Cardinal_Synth_Kick.tar.gz)

(saved as LV2 plugin in Ardour, since for me nothing happens when selecting "Save as..." from within Cardinal)

**Comment by falkTX** [comment]
Thanks for that, but I didnt mean cardinal plugin presets here, but rather the module presets included in each plugin.
Cardinal does not provide a way to expose them, nor does it ship with already existing ones from each respective plugin vendor.

what license do you apply to that patch you made? can be it CC0?

**Comment by jypma** [comment]
Sure thing, CC0 is fine. Shall we set up another place to collect those?

**Comment by falkTX** [comment]
I think starting a discussion around it would be great.
But it is a bit too early for that, I need to go through each individual module/plugin license to see if they are ok for use in cardinal.
There is still a chance I need to remove some modules

**Comment by Hoopeman** [comment]
Do you know if you can install Plugins manually like Autinn's are licensed License: GPL-3.0-or-later should you be able to? Thanks in advance.

 https://library.vcvrack.com/Autinn/Bass

**Comment by falkTX** [comment]
no, please read the readme before asking questions

**Comment by Hoopeman** [comment]
sorry i'm not speak english and is possible I wrong in a some letters
