### ISSUE TITLE
favourites not saving in presets any more

### ISSUE THREAD

**Issue by MaZe6K** [DISTRHO/Cardinal#584]
Hey there!

I used to save a preset, to allow me to have my favourites list recalled, and in the previous version it worked out fine, the favourites were saved with the preset.

But now recalling that preset, as well as making a new preset and loading that, doesn't recall the favourites list.

Bit of a bummer to me.

**Comment by MaZe6K** [comment]
* by preset I mean preset in the DAW, namely bespoke synth

**Comment by MaZe6K** [comment]
* currently on 23.9, by previous version I mean 23.7 - Windows 10, bespoke, FL

**Comment by dromer** [comment]
Do you mean favorites in the module browser?

These kind of settings are now stored globally for all instances, instead of being part of the plugin state.
This was a big feature request by users because they wanted to have the same settings (and favorites) accessible between different sessions.

**Comment by MaZe6K** [comment]
oh ok,that's cool.

but... it doesn't seem to work, when I restart the DAW the favourites are gone again.

or do I need to manually save it somehow?

**Comment by dromer** [comment]
Works for me:

![](https://i.imgur.com/UwYlBuR.png)

**Comment by falkTX** [comment]
Could be dependent on the DAW too, perhaps they never close the plugin DLL handle and thus Cardinal never saves the last settings.
An alternative we can try is to save user settings when UI is closed too. I can prepare a test build for this.

**Comment by MaZe6K** [comment]
For me it doesn't work with FL Studio, Bespoke Synth and Renoise as DAWs. (Win10)
Just tested again with all three: run DAW, load up Cardinal, select a few favourites, close DAW, open again, load up Cardinal - no favourites.

**Comment by falkTX** [comment]
Fixed in 23.10 release

**Comment by MaZe6K** [comment]
Thanks!

I was thinking it wasn't, but just figured out that it works now if I also install the standalone - this is the first time I installed the standalone, so maybe it would have worked correctly before.

So yeah, seems to only work when standalone is installed, I used to just install the VST3 and nothing else.
