### ISSUE TITLE
Logic woes

### ISSUE THREAD

**Issue by gooddosh** [DISTRHO/Cardinal#591]
Hello. I have a couple problems while trying Cardinal for the first time in Logic Pro on Ventura 13.6.

1st problem: I am unable to type anything within the Cardinal plugin, so I can't search for modules. The keys always map to the DAW and never in the plugin, even though it is selected.

2nd problem: I can't run the plugin at all on my external monitor (1070p via HDMI). Everything zooms in heavily and the menus are no longer reachable. I can work on my laptop screen as a workaround.

When I test the stand-alone application, I have the same external monitor problem, and I keep getting permission popups for the Microphone, which I have already granted (access by the software to the audio interface).

Any help is appreciated.

**Comment by gooddosh** [comment]
Went with VCV Rack Pro.

**Comment by falkTX** [comment]
this is not a competition, and issue is still there, please dont close it.

we can come back to this a bit later when I have some time again.

**Comment by gooddosh** [comment]
I take your point. Apologies for closing it previously. VCV Rack Pro fixed issue #1 but still has issue #2.

**Comment by Tygo-lex** [comment]
I have the same problem as you, at me it's heavily zoomed out. I also can't (like you said No1) type anything, so i keep copying and paste-ing it back and ford.

**Comment by falkTX** [comment]
how is the situation for this with 24.04 release?

**Comment by falkTX** [comment]
24.05 is out now with a few more fixes on top. assuming issue is fixed unless told otherwise
