### ISSUE TITLE
Ableton Live 11.3 - Monitoring Stops while editing any parameter

### ISSUE THREAD

**Issue by Samyama1** [DISTRHO/Cardinal#594]
Anytime I edit anything Monitoring stops.

Monitring (listening to the sound) works with the armed track normally. It still works when I open Cardinal (unsing as VST3 in a MIDI track), BUT as soon as I move/change ANY parameter the Monitoring stops.

When I close the device, monitoring comes back... 

Any Clue?

**Comment by dromer** [comment]
Sounds like an Ableton bug? It's not like Cardinal tells the host it should disable the Monitor.

What about VST2 version?

**Comment by luzpaz** [comment]
@Samyama1 ping

**Comment by Samyama1** [comment]
> Sounds like an Ableton bug? It's not like Cardinal tells the host it should disable the Monitor.
> 
> What about VST2 version?

hey, I could get some sound out of it with some standard templates, so probably the problem was me myself =P

**Comment by Samyama1** [comment]
> @Samyama1 ping

pong

**Comment by dromer** [comment]
@Samyama1 so is there an issue or not? :thinking:

**Comment by Samyama1** [comment]
Apparently nop... tkx!!

**Comment by Samyama1** [comment]
Apparently nop... I still have to try more tho, but thanks!

**Comment by Samyama1** [comment]
> @Samyama1 so is there an issue or not? 🤔

Actually, the issue remains, as soon as I change any paramenter, move any knob, sound goes away... when I close cardinal (back to ableton session view) sound comes back...

**Comment by stelladrinkwater** [comment]
what OS and version of ableton are you using?

**Comment by Samyama1** [comment]
> what OS and version of ableton are you using?

Im using Sonoma 14.1.1 and Ableton 11.3.13 BUT NOW IT WORKS!

I have no idea what happened but it's working.. lol

**Comment by Samyama1** [comment]
It's working!
