### ISSUE TITLE
unless_modules bug fix

### ISSUE THREAD

**Issue by unlessgames** [DISTRHO/Cardinal#596]
I've been notified that a recent Rack version broke the rendering on some of my knobs, I fixed those in the latest commit in my repo at 0106e455400a9e8bf3bbbb0abde4418e7614c5aa

Not sure how updates here are handled in general, let me know if I should make a pull request.

**Comment by dromer** [comment]
We haven't updated to the latest Rack2 version yet, but thank you for the heads up.
You could just do a PR with your submodule updated (if that is all that is needed).

If compatible with the current version of Rack2 that we use then it should be relatively easy to get it in.

**Comment by falkTX** [comment]
a document to explain how to update submodules is well overdue, but let me try to summarize the steps:

1. create a cardinal fork through github
2. clone that fork with `--recursive` (or change git remote to that new fork if you have already cloned cardinal before, can be done using `git remote remove origin; git remote add origin git@github.com:DISTRHO/Cardinal.git`)
3. make sure all cardinal code and submodules are updated, to reduce risks of merge conflicts (can be done using `git pull; git submodule update --init --recursive`)
4. create a new branch for preparing the plugin module update (`git checkout -b update-unless` or similar)
5. go into your plugin module folder and update it (like `cd plugins/unless_modules; git checkout main; git pull`). note that the active commit on that module folder is going to be the one used by cardinal at the end.
6. ping us if any new modules were introduced, so we can not only add it but also check for function/symbol name conflicts with other modules (this last step is automated). PS: it shouldn't be on single module devs to ensure global compat with other modules, as official Rack does not care, it is Cardinal's job here to ensure they all work together nicely
7. go back to the main/root Cardinal folder, commit your changes and push then to the branch
8. open a pull request against the official Cardinal github project

**Comment by unlessgames** [comment]
@dromer it should be compatible with Rack 2.3 I just wasn't aware of the problem until now.

@falkTX thanks for the info, I created a pull request and added a slightly modified version of your explanation to the wiki below, hope it's alright!

https://github.com/DISTRHO/Cardinal/wiki/Publishing-plugin-updates

**Comment by dromer** [comment]
Since this is merged we can close the issue.
