### ISSUE TITLE
Too big to fit in window: Logic Pro

### ISSUE THREAD

**Issue by Tygo-lex** [DISTRHO/Cardinal#616]
DAW: Logic Pro DAW
Version: up to date 
macOS Version: Sanoma MacBook: M2 (arm)

![Scherm­afbeelding 2024-02-24 om 14 57 58](https://github.com/DISTRHO/Cardinal/assets/120052774/40352da8-3033-4205-8f9a-accfc2efdb9a)

I tried but nothing works.

Every time i want to use **Cardinal** i will be pushed back from this handy plugin.

**Comment by dromer** [comment]
Hmm, could this be a scaling issue?

It looks like Logic is trying to embed a window ~4x the size of the actual plugin.

**Comment by falkTX** [comment]
well the AU support in DPF is being implemented, so this will change soon anyhow.

I think I am 80% done at this point, will have news on that soon

**Comment by Tygo-lex** [comment]
Does that mean that I need to install the VST3 version?
And credit to you, I am a web developer that makes EDM music for hobby. And as a developer you keep supporting and respecting the people that support all open source projects. I want do also commit to open source projects like you. You and many more form the community.
Thanks to the WHOLE open source community, we respect you!

**Comment by dromer** [comment]
> Does that mean that I need to install the VST3 version?

It means that the current AU builds (which are kind of a hack that use a JUCE wrapper) will be replaced by one that will hopefully have less bugs :)

**Comment by dromer** [comment]
@Tygo-lex can you check the 24.05 release AU build to see if it renders correctly/better?

**Comment by Tygo-lex** [comment]
> @Tygo-lex can you check the 24.05 release AU build to see if it renders correctly/better?

Yes it works perfectly, thanks for the help:)
