### ISSUE TITLE
Compatibility with AAX or Metaplugin...

### ISSUE THREAD

**Issue by sumotoy** [DISTRHO/Cardinal#619]
I would like to use this amazing plug on ProTools but for some reason it's not compatible with Metaplugin (for open inside Protools), Transvst not work, Blue Cat's audio patchwork works but ha issues with Midi.
There's a plan to add even just a AAX wrapper to Cardinal?
I'm actually on Win 10/11 but even OSX

**Comment by dromer** [comment]
It is a proprietary format that only works in a single DAW.

There is no intention to support it.
