### ISSUE TITLE
Plugin search fuzzy matching is imprecise

### ISSUE THREAD

**Issue by jamshark70** [DISTRHO/Cardinal#623]
If I open VCV Rack 2 and search plugins for "vcf," I get 47 modules and they're pretty much all filters, maybe a little noise in the results but not much.

If I open Cardinal and search the same, I get 231 modules including VCOs, LFOs, envelopes, mixers, distortion modules, Dexter... etc etc. It's quite hard to pick the filters out by hand.

"Tag: Filter" does much better, but is less convenient than typing in a search key -- i.e. 1. Right click, type "vcf" = fast. 2. Right click, then click a menu, then scroll down and find the keyword and click on it = slower.

Just wondering if there's a way to improve that.

**Comment by dromer** [comment]
I don't think we make any changes to the Rack search code.

When I type `vcf` I get 45 modules, on the latest build.

**Comment by falkTX** [comment]
isnt just a matter of the plugins you have installed? the behaviour should be exactly the same between Rack and Cardinal on this.

**Comment by jamshark70** [comment]
OK, it must have been a one-off bug in an older version. I upgraded to the latest and it's better. Sorry for noise.
