### ISSUE TITLE
Build and ship Carla binaries on Windows

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#65]
Otherwise nothing about Carla will work.

We can ignore this on macOS and Linux, and require Carla to be installed system-wide in there.

**Comment by falkTX** [comment]
have an idea for this..
to keep things consistent, dont ship with carla binaries (the zip download would get pretty big), but instead create a folder for where the binaries should be placed with a README.txt explaining where to get them.
then on carla side I just need to prepare a separate download.

so windows users can go to the carla page, fetch the binaries and place them on the CardinalSynth.vst/carla folder.
a bit of manual work but still not too much.

**Comment by CarloCattano** [comment]
Looking forwards to try Cardinal on windows !

**Comment by falkTX** [comment]
Cardinal already works on Windows, and Carla too.
This ticket is about allow both, Carla inside Cardinal.

**Comment by CarloCattano** [comment]
Oh I see ! I did not find any binaries and looked into Actions etc with no luck . 
Tried to compile manually but had hit few walls right away and lost inertia

**Comment by falkTX** [comment]
you just click on any successful build in https://github.com/DISTRHO/Cardinal/actions/workflows/build.yml and go to the bottom, builds will be there.
I will setup a FAQ document soon for stuff like this.

**Comment by CarloCattano** [comment]
**facepalm** for some reason I was only seeing the IRC workflow , maybe too much coffee 
Much appreciated as usual!

**Comment by falkTX** [comment]
Done in #192
