### ISSUE TITLE
Lomas Sampler "The lost samples " after update (SOLVED)

### ISSUE THREAD

**Issue by subderground** [DISTRHO/Cardinal#652]
### Version

24.04

### Plugin type

VST3

### OS

Win 11

### DAW / Host (if applicable)

Reaper

### Description

(Tested with LV2 & VST3)
Each time I've updated Cardinal, Lomas Sampler module lost the sample file/folder path of my presets/projects. I've tried to find a file where Cardinal normaly put this kind of  infos; but no success ! Can you tell me where it is ? Or perheaps is it a bug from Cardinal or Lomas Module ?
Many thanks.

EDIT: Now I use the Cardinal "installer" version and the **problem is solved** ! :-)))))

**Comment by falkTX** [comment]
closing ticket since you marked it as solved
