### ISSUE TITLE
port rkukau plugins?

### ISSUE THREAD

**Issue by RustoMCSpit** [DISTRHO/Cardinal#657]
### Description

https://github.com/ryukau/VSTPlugins/issues/2

**Comment by dromer** [comment]
I'm not sure what your question is, but unless there is a project implementing these this is not going to happen.

**Comment by RustoMCSpit** [comment]
> I'm not sure what your question is, but unless there is a project implementing these this is not going to happen.

it was a suggestion if you wanted to

**Comment by dromer** [comment]
We can integrate such a project if it exists, but this is completely out of scope for Cardinal to do.

**Comment by RustoMCSpit** [comment]
> Do note that Ryukau plugins do not have compatible license with Cardinal, so this will actually not be possible to begin with.

it's under gpl3?

**Comment by RustoMCSpit** [comment]
> We can integrate such a project if it exists, but this is completely out of scope for Cardinal to do.

right so cardinal needs vcv to port it and then it forks that

**Comment by dromer** [comment]
> it's under gpl3?

It needs to be `GPL3-or-later`.

**Comment by RustoMCSpit** [comment]
> > it's under gpl3?
> 
> It needs to be `GPL3-or-later`.

?? whats the difference...?

**Comment by RustoMCSpit** [comment]
> > it's under gpl3?
> 
> It needs to be `GPL3-or-later`.

contact the dev to change their licensing, im not following on what the difference is

**Comment by dromer** [comment]
> im not following on what the difference is

https://spdx.org/licenses/GPL-3.0-or-later.html

It means that the code can be used with GPLv3 or any later version of the GPL (ie. v4 or v5 etc.)
This needs to be explicitly mentioned by the author, otherwise it's `GPLv3-only` which is not wanted in the Cardinal project.

**Comment by RustoMCSpit** [comment]
> > im not following on what the difference is
> 
> https://spdx.org/licenses/GPL-3.0-or-later.html
> 
> It means that the code can be used with GPLv3 or any later version of the GPL (ie. v4 or v5 etc.) This needs to be explicitly mentioned by the author, otherwise it's `GPLv3-only` which is not wanted in the Cardinal project.

i see, so whatever the future of gpl is? so it is compatible but it isnt wanted. please contact the devs to change their licensing and talk about integration

**Comment by dromer** [comment]
No, as I said this is completely out of scope for Cardinal.

If you want to see that code integrated you'll have to do the work.

**Comment by RustoMCSpit** [comment]
> No, as I said this is completely out of scope for Cardinal.
> 
> If you want to see that code integrated you'll have to do the work.

oh alright fair nuff sorry forgot

**Comment by RustoMCSpit** [comment]
https://github.com/ryukau/VSTPlugins/tree/master/common/dsp

for anyone who sees this, this is where the DSP is

**Comment by dromer** [comment]
@RustoMCSpit you might have better luck asking on the VCV forums: https://community.vcvrack.com/c/development/8

**Comment by RustoMCSpit** [comment]
> And what you linked is only the shared bits, not the plugin DSP.

oh whoops lol! as this project is gpl, can vcv do it?

**Comment by RustoMCSpit** [comment]
> @RustoMCSpit you might have better luck asking on the VCV forums: https://community.vcvrack.com/c/development/8
> 
> And what you linked is only the shared bits, not the plugin DSP.

could you link the actual dsp sorry
