### ISSUE TITLE
AU crashing Ableton 

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#662]
### Version

24.04

### Plugin type

AU

### OS

Catalina 

### DAW / Host (if applicable)

Ableton 11

### Description

I get a serious crash on Ableton 11 with the last update on every time I open cardinal.
System OS Catalina

**Comment by eulmour** [comment]
**Version**
24.04

**Type**
AU

**OS**
macOS Monterey 12.7.2

**Host**
Logic Pro 10.7.9

**Description**

I also encountering the crash. This happens immediately when opening the plugin (Synth and FX versions)

Steps to reproduce:
1. Having version 23.10 installed
2. Installing new version 24.04 on top of the previous version (AU install option is checked)
3. Once installed, I opened the DAW
4. Tried to load CardinalSynth

The AU validation report:
```
validating Audio Unit CardinalSynth by DISTRHO:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'DcnS' - 'Dstr'
--------------------------------------------------
Manufacturer String: DISTRHO
AudioUnit Name: CardinalSynth
Component Version: 23.10.0 (0x170A00)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
[34m[0.000 info CardinalCommon.cpp:578 Initializer] [0mCardinal Unknown 23.10, compatible with Rack version 2.3.0
[34m[0.000 info CardinalCommon.cpp:579 Initializer] [0mMac 12.6
[34m[0.000 info CardinalCommon.cpp:580 Initializer] [0mBinary filename: /Library/Audio/Plug-Ins/Components/CardinalSynth.component/Contents/MacOS/CardinalSynth
[34m[0.000 info CardinalCommon.cpp:582 Initializer] [0mBundle path: (null)
[34m[0.000 info CardinalCommon.cpp:588 Initializer] [0mSystem directory: /Library/Application Support/Cardinal
[34m[0.000 info CardinalCommon.cpp:589 Initializer] [0mUser directory: /Users/roman/Documents/Cardinal
[34m[0.000 info CardinalCommon.cpp:590 Initializer] [0mTemplate patch: /Users/roman/Documents/Cardinal/templates/synth.vcv
[34m[0.000 info CardinalCommon.cpp:591 Initializer] [0mSystem template patch: /Library/Application Support/Cardinal/patches/templates/synth.vcv
[34m[0.000 info CardinalCommon.cpp:605 Initializer] [0mInitializing plugins
libc++abi: terminating with uncaught exception of type rack::Exception: Manifest contains module Burst but it is not defined in plugin


validation result: crashed validation
```

**Solution**

I noticed that in the Logic plugin manager, the plugin version was displayed as 23.10, not 24.04.
So I managed to fix this by manually deleting the old versions from /Library/Audio/PlugIns/Components and installing pkg again.

**Comment by falkTX** [comment]
I was able to reproduce the issue and the fix, so I am quite sure 24.05 will fix it for others.
we can just wait a few more hours for the official release, any time now.
if it gets too late I might do it on sunday though.

**Comment by falkTX** [comment]
ok please try the latest just released 24.05 thanks

**Comment by eulmour** [comment]
@falkTX @dromer I tested 24.05 (AU) for about an hour, no crashes for me

**Comment by steveparkerdj** [comment]
Still crashing the system.... Sorry Kate repl

**Comment by dromer** [comment]
@steveparkerdj there have been some AU fixes in the latest nightly.

Please try again :)

**Comment by steveparkerdj** [comment]
I can't update you on this since I'm now on new OS system and bug is gone. 
One thing tho I can't zoom in or out with my Mac keys anymore is there an issue on this?
Regards

**Comment by dromer** [comment]
What kind of mac keys? (I don't have a mac keyboard)

Zoom normally happens with Option+scroll.
