### ISSUE TITLE
MIDI not working in Logic 

### ISSUE THREAD

**Issue by pippux** [DISTRHO/Cardinal#667]
### Version

24.04

### Plugin type

AU

### OS

Mac OS 13.6.6

### DAW / Host (if applicable)

Logic 10.8.1

### Description

Fresh 24.04 install on an i7 iMac. When opening the AU in Logic I see randomly one of these behaviours
1) no MIDI signal at all
2) MIDI gate works, but the pitch is fixed, no matter what note is sent
3) both pitch and gate state are fixed, no matter what MIDI is sent.
Also velocity seems to be always fixed.
Audio in and out works.

Also, went back to 23.10 and everything works perfectly out of the box.

Update (see below about hardware and software versions): I reinstalled 24.04 to answer falkTX's question and now both Logic and GB crash when Cardinal loads.

**Comment by falkTX** [comment]
do you have other AU hosts that you can try in? garageband is free and should behave similarly, please check if you can reproduce the same issues there too.

that way I can try a fix as I have garaband but not logic pro.

**Comment by pippux** [comment]
Hi, I have just re-installed 24.04 and now both Logic and Garage Band (10.4.8) crash as soon as I load Cardinal.
So there are definitely some issues. 
On the other hand I have tried to install it on a MacBook M2 Pro with Mac OS 13.4.1 and it works correctly on Garage Band 10.4.7, so hardare, OS version and DAW version are different.
My main system is an i7 (I'll update the main post with this info too).
Thanks for the support and for the amazing work on the project.

**Comment by pippux** [comment]
Further Update: 24.04 crashes also the standalone version of Kushview Element.

**Comment by falkTX** [comment]
please try the latest just released 24.05 thanks

**Comment by pippux** [comment]
Installed 24.05, I will edit this later but essentially:
Upgrading with 23.10 already installed crashes Logic and GB. Installing from scratch does not crash the daws
From a quick check it seem to work on Garage Band.
Still the problem is not completely fixed.
  When an instance is loaded in Logic, the first MIDI note triggers a constant note with fixed pitch. But when MIDI is reset from Logic everything seems to work. It is still annoying and I will probably roll back to 23.10, but at least now there is a workaround and I can check the new features.

Thanks
    f

**Comment by lamech** [comment]
As a second source of data: everything I can think of to test with MIDI input to Cardinal works fine here.

My system:

Cardinal 24.5
Logic 11.01
MacBook Pro M2 8GB 
MacOS Ventura 13.6.7

So it may be some difference in our systems.

Hth!

**Comment by falkTX** [comment]
please re-check with the latest 24.12 release, thanks!

**Comment by pippux** [comment]
Everything seems to work. Thanks a lot!
