### ISSUE TITLE
file handling issue [SOLVED]

### ISSUE THREAD

**Issue by HagenBarz** [DISTRHO/Cardinal#673]
### Version

24.05

### Plugin type

Native / JACK

### OS

Arch Linux

### DAW / Host (if applicable)

Reaper

### Description

I can not open nor save a patch. "Open Demo/ example project" works as expected.
I have no idea what goes wrong here. No dialog window pops up to chose or to save a patch.
The same holds true for the plugins (LV2 and VST).
What did I miss?

wm is xfce4 (no fancy configuration)

**Comment by falkTX** [comment]
see https://github.com/DISTRHO/Cardinal/blob/main/docs/FAQ.md#on-bsdlinuxx11-the-menu-item-save-asexport-does-nothing

you need to have a working xdg-desktop-portal service running.

**Comment by HagenBarz** [comment]
Thank you for the hint.
At the end it seems that simply a missing conf file caused the issue. The following solved my problem.

> Copy the /usr/share/xdg-desktop-portal/gtk-portals.conf file into ~/.config and rename it to xfce-portals.conf.

This means in my case (xfce4) I have to install xdg-desktop-portal-gtk as well.
