### ISSUE TITLE
[Feature request] Offer a MIDI Fx version of the Cardinal AU

### ISSUE THREAD

**Issue by lamech** [DISTRHO/Cardinal#681]
### Description

Generating freaky control signals via modular structures is the coolest. In order to generate MIDI correctly in Logic, you have to expose a MIDI FX version of your AU plugin. Reaktor does this, the Reason Rack does it, etc.  Didn't there used to be a MIDI FX Cardinal AU that is no longer offered? I can't remember. Please either bring it back or offer one. I believe all you have to do is check the MFX box in Projucer: https://forum.juce.com/t/tutorial-getting-set-up-to-build-logic-pro-x-midi-fx-plugins/15019/5

As with prior issues of mine, I'm happy to help you test if you don't have Logic.

My system:

MacBook Pro M2
8G RAM
MacOS Ventura 13.6.7
Cardinal 24.05
Logic Pro 11.0.1

**Comment by dromer** [comment]
> check the MFX box in Projucer:

We don't use JUCE to build Cardinal.

**Comment by lamech** [comment]
Interestingly, with the [new Logic 11 internal midi routing feature](https://support.apple.com/en-euro/guide/logicpro/lgcp1efa7c4d/11.0/mac/13.5), you may not need a separate MIDI FX anymore.

I was able to set up a quick example using the "Random Progress Pluck" demo with a Host MIDI module added (Screenshot 1). I am sending v/oct and gate, as well as patching an LFO to velocity out. I have the volume of the 2 Cardinal sequencers turned all the way down (Screenshot 1), so I can hear the Retro synth on track 2 playing the notes being sent by Cardinal from track 1 via the "Internal MIDI In" menu in the Track inspector on track 2 (Screenshots 2 & 3). 

Note: if I send the LFO signal to Mod Wheel or Pitchbend (Screenshot 4), that does show up in the second track as the correct CC data, but it appears to interfere with NoteOff messages because I get a lot of stuck/hung notes. I'll open a separate issue for that if I can't figure out how to resolve it, but otherwise it seems to me this issue can be closed.

<img width="1226" alt="Screenshot 1" src="https://github.com/user-attachments/assets/a30b0f57-3645-4bdd-8c94-67efa02f3182">
<img width="1208" alt="Screenshot 2" src="https://github.com/user-attachments/assets/31eee6f0-74f6-42a6-836c-2b19ddc72c12">
<img width="1207" alt="Screenshot 3" src="https://github.com/user-attachments/assets/3f340819-b4c4-42da-959a-9df365884ab4">
<img width="1223" alt="Screenshot 4" src="https://github.com/user-attachments/assets/a51b7fda-67e8-4236-a11b-7701c4c21ba3">
<img width="1395" alt="Screenshot 5" src="https://github.com/user-attachments/assets/d65fc8ec-6b65-4551-b4a1-05dda41c4355">

**Comment by falkTX** [comment]
I am closing this ticket as "wont fix", as in my opinion there are enough variants of Cardinal already, dont want to add more.
Related to this though, MIDI handling was quite broken in AU version, corrected now in 24.12 as far as I can tell.
