### ISSUE TITLE
AU: HOST TIME isn't working

### ISSUE THREAD

**Issue by ladygang** [DISTRHO/Cardinal#689]
### Version

24.05

### Plugin type

AU

### OS

macOS Ventura 13.5

### DAW / Host (if applicable)

Ableton 12

### Description

i tried to use the host time module in cardinal, but time on the display stays and not changes when i pushed the playback button. i connected 'reset out' from host time with 'reset in' of a sequencer and 'step' with 'external clock' and there was no any signal from plugin.

**Comment by dromer** [comment]
What about VST2 and VST3?

**Comment by ladygang** [comment]
yeah, i figured out that issue may be in this way/
ill try right now


вт, 23 июл. 2024 г. в 22:06, dreamer ***@***.***>:
