### ISSUE TITLE
Remote OSC access between various CPU archs crashes Cardinal

### ISSUE THREAD

**Issue by Deftaudio** [DISTRHO/Cardinal#700]
### Version

24.05

### Plugin type

Native / JACK

### OS

Raspberry Pi OS 

### Description

Hello, I built Cardinal from the latest source, (as well is from 24.05 sources) on Raspberry Pi OS (up to date). 
It seems running stable in Jack version except OSC connection. Everytime I connect from MacOS client (running the same exact version) the Pi app crashes with an error

`cardinal [dpf] assertion failure: "threadContext != nullptr" in file override/context.cpp, line 77 Segmentation fault`

Would you please suggest, is it a supported use case when the editor and server are on different OS/CPU architectures? Or I could only connect from a Cardinal instance running on another RPi?

**Comment by dromer** [comment]
OSC over the network should most certainly not be dependent on the architecture.

**Comment by Deftaudio** [comment]
Would you suggest any way to debug it further? 
I think the next thing that I can try running the second copy of Cardinal on the same OS and use one as a client while another one as a server.

**Comment by dromer** [comment]
Ok I just tried this locally between two Cardinal instances and I see this in the console:

```
[dpf] Cardinal OSC unhandled message "/screenshot" with types "b"
[dpf] assertion failure: "threadContext != nullptr" in file override/context.cpp, line 77
Segmentation fault
```

**Comment by falkTX** [comment]
This should be fixed in 47d4e08f4939946364d5edb216b88b0c57dbd384
Please confirm

**Comment by dromer** [comment]
Engine menu is now missing OSC controls:

![2024-09-22_08-52](https://github.com/user-attachments/assets/93c39d82-85f1-4d2e-a228-7b7c47f64db7)

**Comment by falkTX** [comment]
> Engine menu is now missing OSC controls:
> 
> ![2024-09-22_08-52](https://private-user-images.githubusercontent.com/1185977/369669649-93c39d82-85f1-4d2e-a228-7b7c47f64db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTIyMDMsIm5iZiI6MTcyNjk5MTkwMywicGF0aCI6Ii8xMTg1OTc3LzM2OTY2OTY0OS05M2MzOWQ4Mi04NWYxLTRkMmUtYTIyOC03YjdjNDdmNjRkYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMDc1ODIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjIyYWJjM2E3YWQzMTY0MjgyMTg4MmI3ZGFlYTQxZGJmNGUzZDA1YmE4NjNiYTY5NTlkYWZhOWJjOWI2ZmU1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.aw7RO5jHm0eGVKK2WgMxzGw2RKnGlfU7wEcIQar-6Mc)

is this your own build? are you sure you just dont have liblo-dev by mistake?

in my own tests I saw these options there.
also they are not there on plugin versions which is normal, but standalone will have it.

**Comment by dromer** [comment]
This is on jack standalone. Local build from current main.

It always worked before afaik.

**Comment by falkTX** [comment]
I tried before pushing and it was working fine. that is how I tweaked the defaults, to have it auto-deploy by default otherwise it seems as nothing is happening

**Comment by dromer** [comment]
Ok false alarm. Confirm it works!

**Comment by Deftaudio** [comment]
I build from source on two RPi and confirm it's working as expected - I can push a template to the remote session. 
However, I can't control from macOS to RPi. The instance on macOS fails right after it connects to the IP. On the server side I see a hello message received. If I do that in opposite order, so RPi as a client controls macOS server, then RPi instance crashes with segfault. 
Please, advise. 

p.s. I wasn't able to combine from source on Mac, it's not seamless as on Linux. (several plugins fails including Surge and finally DPF doesn't build modules like for JACK) So instead I used a night build image on macOS from here https://github.com/DISTRHO/Cardinal/actions/runs/10974804201

**Comment by falkTX** [comment]
Try to do a debug build so we can investigate the crash, the building doc from this repo has details.

but even on regular builds, do you get any backtrace through gdb? any logs printed on the command-line?

for the macos build issues please open a new ticket for that

**Comment by Deftaudio** [comment]
I haven't the latest upstream to compare to this commit. But on this one there is no any useful info other than a segfault. 
In order to try a DEBUG build I need somehow compile it on macOS. I'll bring this question in another issue, but would it be possible to ask a night build with debug flag on?

**Comment by falkTX** [comment]
DEBUG for macOS, or for arm64 linux?

**Comment by Deftaudio** [comment]
Filipe, debug for macOS, please.

**Comment by Deftaudio** [comment]
I'm sorry for the follow up. I looked at the build yaml for macOS and was able to compile it from source. Interestingly, now I don't see OSC menu at all. Below is how I did it. Please, suggest if I missed anything, thank you. 

```
brew install libsndfile autoconf automake meson
git clone https://github.com/DISTRHO/Cardinal.git --recursive

export CFLAGS="-DMAC_OS_X_VERSION_MAX_ALLOWED=MAC_OS_X_VERSION_10_12 -mmacosx-version-min=10.12 -arch x86_64 -arch arm64"
export CXXFLAGS="${CFLAGS}"
export PATH="/usr/local/opt/ccache/libexec:${PATH}"

source deps/PawPaw/local.env macos-universal-10.15
make features
make NOOPT=true DEBUG=true -j 10
```
