### ISSUE TITLE
Sound Preview

### ISSUE THREAD

**Issue by ThoXin** [DISTRHO/Cardinal#704]
### Description

A hotkey that can be pressed when hovering over any signal to output that signal to the output to preview what the sound wave sounds like in that part of the chain.

**Comment by dromer** [comment]
These kind of additions to the Rack engine are out of scope for the Cardinal project.

While it is a neat thought experiment for a feature, this kind of divergence from Rack is not what the Cardinal project is about.

It might be possible to develop a plugin that provides such functionality (as I believe that Rack plugins are able to modify the runtime to some extend). Maybe ask this on the VCVrack community forum.
