### ISSUE TITLE
Wave preview

### ISSUE THREAD

**Issue by ThoXin** [DISTRHO/Cardinal#705]
### Description

A Oscilloscope window that pops out when you press a hotkey over any signal to visualize the sound wave in that part of the chain.  Possibly with the ability to scroll after holding down to change the scale on horizontal axis.

**Comment by dromer** [comment]
These kind of additions to the Rack engine are out of scope for the Cardinal project.

While it is a neat thought experiment for a feature, this kind of divergence from Rack is not what the Cardinal project is about.

It might be possible to develop a plugin that provides such functionality (as I believe that Rack plugins are able to modify the runtime to some extend). Maybe ask this on the VCVrack community forum.
