### ISSUE TITLE
Trackpad dragging extremely sensitive

### ISSUE THREAD

**Issue by quantumech3** [DISTRHO/Cardinal#712]
### Version

24.09

### Plugin type

Native / JACK, AU, VST3

### OS

MacOS Ventura 13.6.7

### DAW / Host (if applicable)

Ableton/Standalone

### Description

When I use 2 fingers to drag and navigate around my rack it is now super sensitive. I am only moving my hand a tiny bit and the navigation jumps around as shown in the gif (the gif is not sped up).
![ezgif-7-a7de08309c](https://github.com/user-attachments/assets/baa34884-8539-4e68-bed0-a54bce9f6e74)

**Comment by quantumech3** [comment]
Apologies I forgot to say that this issue did not exist in the previous version of Cardinal. I believe it might be a regression.

**Comment by dromer** [comment]
We did make changes to scroll sensitivity as it was extremely slow on other systems, but the expected behavior was that it was now the same for all.

But somehow it seems it "overshoots" with this setting on your version of macOS. 
There is a suspicion of where this is coming from at least.

Thanks for reporting!

**Comment by dromer** [comment]
@quantumech3 do you get the same behavior with the scroll wheel on a USB mouse?

**Comment by quantumech3** [comment]
Yes I have this same problem with the scroll wheel on my Logitech g902

**Comment by TomAuger** [comment]
Can confirm the same issue as OP described. 16" MBP M3 Pro Max Sequoia 15.0. Default trackpad speed settings.

**Comment by TheVoiceOfQ** [comment]
Just want to say hello, and say that this issue happens to me too.  I'm on 15" MBA M3.  default track speed settings.  Cardinal is awesome.

**Comment by winescout** [comment]
I really appreciate coming across this thread, and knowing that this issue is surfaced.  Same for me on an M1/Sequoia.  The arrow keys are a short term work around.

**Comment by sciencesque** [comment]
Same issue here - MacBook Pro M1 Max, 15.1.1 Sequoia. My sincere thanks to the Cardinal developers!

**Comment by dromer** [comment]
Have you all tried the latest nightly builds?

This should've been solved in the latest pugl update in DPF.

**Comment by winescout** [comment]
Woot.  Confirmed that in "Log number of modules and plugin collections on start #2067" build the scroll issue is resolved on an M1/Sequoia.  Thankyou so much.
