### ISSUE TITLE
[Feature request] Have 8 audio I/O ports on Cardinal FX as well

### ISSUE THREAD

**Issue by rafaelferreiraql** [DISTRHO/Cardinal#721]
(I do not know if this is relevant but I'm using Reaper, Cardinal VST3)

As per #626 , using Cardinal "Main" adds the dry signal to its output (at least on my DAW). Since no word has been given on whether there are any plans to revert this or not (and it may be a bit too late, as it would be needed to introduce breaking changes again in order to revert back to 23.07 behavior), so I'd like to suggest this instead...

Since the dry signal mix behavior is undesired to me, I've been using CardinalFX ever since, but it lacks the 8 audio I/O goodness Cardinal Main offers, so I'd really like to have access to that, I can imagine there must be _some_ reason why Main is the only one which currently has that in the first place but I don't really know what it is.

Thanks for reading

**Comment by falkTX** [comment]
This is a "wont fix", the FX version will remain stereo for best compatibility with regular hosts.

The proper fix should go on the main variant, instead of adding more ports to the FX and Synth variants
