### ISSUE TITLE
24.09 Native and Jack crashes in Mac Os Catalina

### ISSUE THREAD

**Issue by Blaafot** [DISTRHO/Cardinal#724]
### Version

24.09 and 24.04

### Plugin type

Native / JACK

### OS

Mac Catalina

### Description

24.09 and 24.04 native and jack crashes on opening on my Mac Os Catalina.  They work well as plugins in Live11 and Bitwig5.

But I also had crashes on Live11 and Bitwig5 connecting remote to my Mod Duo X using the Cardinal plugins. This has worked well before, and is a new issue since 24.09

**Comment by dromer** [comment]
For the jack version: are you running a jack server for it to connect to?

**Comment by Blaafot** [comment]
Yes I am running Jack. Should  I post the crash reports?

**Comment by Blaafot** [comment]
Sorry to waste your time. Seems the problem was I had the version 24.04 still as shortcut on the Programs toolbar. When I ran CardinalJack and CardinalNative from the folders through Navigator it works fine. I still have to check if the connection to ModDuoX and ModDwarf using Cardinal plugin still causes problems. will report back on that.
