### ISSUE TITLE
Load Sample: file explorer window open

### ISSUE THREAD

**Issue by offthesky** [DISTRHO/Cardinal#76]
any module that allows loading (or saving) a sample: cf player, bidoo canard, etc - when right clicking/choosing the option to load/save, the open file window doesn't appear.

cardinal vsti b16f9558 in ableton 11(latest), win 10(latest) macbook pro i7 (bootcamp)

also tested this in reaper, same issue.

**Comment by falkTX** [comment]
Yes, known issues, mentioned near the top of the readme.

Cardinal doesnt use osdialog because of its blocking nature, goes into custom code for proper async dialogs.
I need to write a small set of Cardinal-specific APIs and then patch the plugins to support it.
To be done soon

**Comment by falkTX** [comment]
cf modules now support the file actions.
due to async nature of some of these dialogs, they will appear as built-in which looks quite nice IMO.

![image](https://user-images.githubusercontent.com/1334853/145693313-842981d1-eb23-461e-8e63-10346edf7848.png)

will look into others soon.

**Comment by falkTX** [comment]
Ok so we have these modules that use osdialog:

- [ ] amalgamented armonics
- [ ] bidoo
- [ ] chowdsp
- [ ] fundamental
- [ ] mindmeld
- [ ] prism
- [ ] repelzen
- [ ] Valley

Just keeping a list here.
Let's leave the ticket open until we patch them.

**Comment by falkTX** [comment]
Bidoo is now done.
Adjusted cf based on things I noticed from Bidoo.

Patches to get this going are appreciated.
For reference this is how cf and bidoo were patched:
https://github.com/CardinalModules/cf/commit/51506f16bb65104b5efb5294ace5ee912a9abcc9
https://github.com/CardinalModules/Bidoo/commit/e55fcd2e1d7c0fef69d4919baac6f791172c89ca

**Comment by offthesky** [comment]
just now tested out cf player and bidoo emile & edsaros and they seem to work great, ty!!

**Comment by falkTX** [comment]
All done now in 3943e4c1e985199173fd3aee9db0e37bd7ba7f80, except chowdsp credits due to a crash, I will investigate this later.
