### ISSUE TITLE
[Licensing] DrumKit uses non-free code.

### ISSUE THREAD

**Issue by rl2939** [DISTRHO/Cardinal#762]
### Description

DrumKit is supposed to be licensed under the CC0 1.0. However, I took a look at DrumKit's [shadow.hpp](https://github.com/SVModular/DrumKit/blob/v2.0/src/component/shadow.hpp), and it looks like they are using code from a non-GPL3.0+ compatible license. I think this portion of the code, and any calls to this code, should be removed from our version of Drumkit. If this is not possible, I think we should replace these modules with something else (such as [the SickoCV modules](https://github.com/sickozell/SickoCV)).

The license in question:
```
/*
Shadow code taken and modified from https://github.com/lindenbergresearch/LRTRack

and is available under the following license:

Copyright (c) 2017-2018, Lindenberg Research / Patrick Lindenberg
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Commercial redistribution of the code, or parts, in any form
  must be granted by the author.

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of Lindenberg Research nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.


THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/
```

**Comment by falkTX** [comment]
huh thats very nasty. thanks for the finding.
It was added in https://github.com/SVModular/DrumKit/commit/0d20223f84753e46d28990a63b89cd14406ea32f

so lets either remove that part of the code that does shadow, or replace it.

from looking at other parts of the codebase the "DK*" classes all follow the same style, so I dont think we need to remove the class altogether, just the nvg drawing part.

**Comment by falkTX** [comment]
I did shadow for AIDA-X plugin before, a simple gradient is fine enough for this I think.
https://github.com/AidaDSP/AIDA-X/blob/main/src/aidadsp-ui.cpp#L398

**Comment by falkTX** [comment]
Resolved in https://github.com/CardinalModules/DrumKit/commit/cee0ec8896f5c0bba736117dc4ce21bd6449868c

Will be part of next update tomorrow

**Comment by rl2939** [comment]
Cool! Would it be possible to send the patch as a pull request to the upstream DrumKit project ?

**Comment by falkTX** [comment]
sure, but since they ignored other PRs I am not too confident they will accept this one either.

**Comment by falkTX** [comment]
https://github.com/SVModular/DrumKit/pull/20

**Comment by JerrySievert** [comment]
note that drumkit is licensed cc0 (except for the shadows), and is _not_ commercial code.

**Comment by falkTX** [comment]
it includes what is consider to be non-free code, so it had to be removed
