### ISSUE TITLE
AU: Cardinal Not taking clock from Live

### ISSUE THREAD

**Issue by BL441857** [DISTRHO/Cardinal#771]
### Version

24.12

### Plugin type

AU

### OS

15.1.1

### DAW / Host (if applicable)

Live V12.1.5

### Description

The Cardinal CLock is no longer recieving any clock or transport controls from Live. It works fine on my old Live but on my new mac it just doesnt trigger. Everything else about the patch looks to be the same.

**Comment by dromer** [comment]
Is this only with the AU version of the plugin?

Maybe you can try with VST2 or VST3 versions instead.

**Comment by BL441857** [comment]
I can install it but all my tracks use the AU version so it’s not a small task to migrate it to VST. AU works fine on 10.14 / Live 10 but I cannot stick to this any longer. 

Is it possible to test and see if you also have this issue?

I don’t tend to be on the last software but this is full studio migration so it’s the latest of everything. 

I’ll try VST and feedback

tks

Mark

**Comment by BL441857** [comment]
Hi, yes VST 3 works fine so I have a work around at least. Thanks for the great software and support. If it’s fixed at a later version it would be great to know.

Best regards

MArk

**Comment by dromer** [comment]
I tried the AU in FL and Reaper and in both the Host Time works correctly (both Instrument and FX versions of the plugin).

It seems to be a specific issue with Ableton then.
Since I don't have a license and they don't offer a trial version I'm not able to test this currently.

**Comment by dromer** [comment]
Ok, I can confirm that in Ableton the AU isn't responding to the host transport.
Seems to be the only DAW that is affected though.

**Comment by BL441857** [comment]
Ah OK well thanks for trying.  Bit of admin on side but at least I can save and reopen under vst.

tks

Mark

**Comment by falkTX** [comment]
I was able to fix it, just in time for next release on sunday

**Comment by BL441857** [comment]
Holy s**t that’s amazing. Thanks I’ll hold off. What a time saver this is thanks!!

Best

Mark
