### ISSUE TITLE
24.12 Stepwave , Meander, Orbits and Drumkit

### ISSUE THREAD

**Issue by subderground** [DISTRHO/Cardinal#773]
### Version

24.12

### Plugin type

VST3

### OS

win 11

### DAW / Host (if applicable)

Reaper

### Description

Hi, I just tested the v24.12 (installer) and I noticed that:

The updated modules "drumkit" & "orbits" are not included ?
The updated modules from "Meander" are available by "search" but not in the "brand list".
"CV Funk STEPWAVE" module doesn't stop while stopping the sequencer "with its Reaper DAW stop button". I don't know if it's a Cardinal "bug" or a conception problem inside the module itself.

Btw, many thanks for you work :-) Cardinal rocks !

**Comment by dromer** [comment]
DrumKit is under the SV Modular brand and the full name of Orbits is actually RareBreeds Orbits and we see it under the Rarebreeds brand.

With Step Wave the On/Off doesn't respond to a continuous signal but to a gate. If you want to control it using Host Time you'll need to do a little conversion from the Playing output to a gate on the On/Off input of Step Wave.

**Comment by falkTX** [comment]
we could also have an option on the host time module to behave as other modules expect the signal to be.

**Comment by subderground** [comment]
Thanks  for the infos 😇 Have a great day 🤩
