### ISSUE TITLE
the 64bit and 32bit win vst2 version, the browser doesn't load

### ISSUE THREAD

**Issue by offthesky** [DISTRHO/Cardinal#78]
a560b372 : finding this issue in reaper (latest) and ableton 9(latest) on my win10 32b tablet.  also tested the 32bit vst2 and 64bit vst2 in 64bit reaper on a macbook pro 17" (win 10, bootcamp) and same issue with both versions of the plugin.  it's as though the plugin isn't finding the resources folder. 

![cardinal 32bit blank browser](https://user-images.githubusercontent.com/95579081/145624685-673b54a4-b40b-4707-bec7-f4856cd94620.png)

last 32bit version i have that works is e87f3a03 (although many modules seem to cause crashes when reloading projects)

**Comment by offthesky** [comment]
also: same issue with 64bit vst2 of a560b372

**Comment by falkTX** [comment]
Did you move the dll without moving the whole vst folder?
We had someone reporting just the same thing yesterday.

**Comment by falkTX** [comment]
In either case I pushed a new fix for cases like this just now, wait for it to build and replace the DLL file.
It should work then.

**Comment by offthesky** [comment]
didn't move the dll, the resources folder is in the same folder as the CardinalSynth.dll.

also, i reverted back to b16f9558 x64 on this win10 x64 machine, but it is now having the same problem, whereas b16f9558 x64 was working just fine on this same machine just yesterday.

will try out the latest build here in a bit. fingers xd.

**Comment by falkTX** [comment]
Well the plugin (before the change I pushed a few moments ago) expects it to be in a "CardinalSynth.vst" folder, if you move "CardinalSynth.dll" and "resources" out of that folder somewhere else, the plugin misbehaves exactly as you described.

My point was to ask if you moved the contents of the "CardinalSynth.vst" folder, or the folder itself.
The 1st option leads to issues, hopefully fixed in the next build.

**Comment by offthesky** [comment]
ah ok i see! i was starting to manually rename the folders as CardinalSynth.vst-b16f955 and so on to be able to keep track of the different versions (rar+deleting the ones not in use). so that makes sense why things stopped working. thanks for all your help on this!

**Comment by falkTX** [comment]
closing this ticket since it is resolved now.
