### ISSUE TITLE
Bacon Music is missing several modules, despite them being in plugin.cpp.

### ISSUE THREAD

**Issue by rl2939** [DISTRHO/Cardinal#783]
### Version

24.12

### Plugin type

Native / JACK (& the web version) 

### OS

Unix & Unix-like

### Description

Several modules are missing in the Bacon Music collection, despite them being in plugin.cpp.
These include ChipYourWave, Open303, ALingADing, and KarplusStrongPoly. 
These are **not** the modules listed under "Used for testing or not practical".

**Comment by dromer** [comment]
See the plugin.json -> https://github.com/baconpaul/BaconPlugs/blob/2886a282a0f8518e0515b549e426428db332378c/plugin.json

These are "hidden", that means that patches that use them still work, but new patches cannot directly add them.
