### ISSUE TITLE
Feature Request: OSC receive/send support

### ISSUE THREAD

**Issue by DatanoiseTV** [DISTRHO/Cardinal#99]
It would be great if knobs and sliders could be not only mapped to MIDI CC, but also to a OSC Path, preferable bi-directional.

From the UI perspective, I'd imagine a right-click context menu which lists a OSC Path. Default could be /<module_name>/<idx>/<parameter_name>. The OSC port should be configurable via a setting.

**Comment by dromer** [comment]
I think midi-cc mapping currently doesn't work yet, but yes nice idea!

Building with `HAVE_LIBLO=true` there is an experimental OSC server available, however I think currently you can only push full patch configurations, not any individual controls.

**Comment by falkTX** [comment]
> I think midi-cc mapping currently doesn't work yet, but yes nice idea!

this already works, except for vst3

**Comment by falkTX** [comment]
Feature is enabled on latest git, started some basic documentation for it too https://github.com/DISTRHO/Cardinal/blob/main/docs/OSC-REMOTE-CONTROL.md

There is very little replies back, only if you try to load an entire file/patch as that can fail for many reasons.

If more is needed, you know what to do, contributions welcome and all that :)
